// Command genbuiltins writes ../builtins_gen.go: the names of the types and
// functions of pg_catalog, read from live servers. A migration may create a
// type or a function with such a name (CREATE TABLE text, CREATE FUNCTION
// round); pg_catalog comes first in every search_path, so an unqualified use
// of the name means the built-in, and the rewriter leaves it unqualified.
//
// The names are the union over the servers: the types of pg_type (array types
// such as _int4 included) with the type keywords that the grammar maps to
// pg_catalog (int, integer, double, ...), and the functions, aggregates and
// procedures of pg_proc.
//
//	. ../tools/env.sh && go run ./cmd/genbuiltins -versions "12 13 14 15 16" -out ../builtins_gen.go
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/4itosik/pg_migrate_research/poc/harness"
)

// typeKeywords are the type names of the grammar that are keywords and become
// a type of pg_catalog (the rules Numeric, Bit, Character, ConstDatetime,
// ConstInterval and JsonType of gram.y): a type a migration creates with such a
// name is never what the keyword means.
var typeKeywords = []string{
	"bigint", "bit", "boolean", "char", "character", "dec", "decimal", "double", "float", "int", "integer",
	"interval", "json", "national", "nchar", "numeric", "real", "smallint", "time", "timestamp", "varchar",
}

func main() {
	out := flag.String("out", "../builtins_gen.go", "output file")
	versions := flag.String("versions", "12 13 14 15 16", "PostgreSQL major versions, their servers are under $PG_ROOT/<major>")
	flag.Parse()
	root := os.Getenv("PG_ROOT")
	if root == "" {
		log.Fatal("PG_ROOT is not set: . tools/env.sh")
	}
	ctx := context.Background()
	types, funcs := map[string]bool{}, map[string]bool{}
	for _, k := range typeKeywords {
		types[k] = true
	}
	for _, v := range strings.Fields(*versions) {
		if err := os.Setenv("PG_BIN", filepath.Join(root, v, "bin")); err != nil {
			log.Fatal(err)
		}
		collect(ctx, v, types, funcs)
	}
	src, err := format.Source(render(*versions, types, funcs))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %s: %d types, %d functions", *out, len(types), len(funcs))
}

func collect(ctx context.Context, version string, types, funcs map[string]bool) {
	srv, err := harness.StartServer(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer srv.Stop()
	db, err := srv.NewDatabase(ctx, "genbuiltins")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Drop(ctx)
	rows, err := db.QueryStrings(ctx, `
		SELECT 'f|' || proname FROM pg_proc WHERE pronamespace = 'pg_catalog'::regnamespace
		UNION SELECT 't|' || typname FROM pg_type WHERE typnamespace = 'pg_catalog'::regnamespace`)
	if err != nil {
		log.Fatal(err)
	}
	nt, nf := 0, 0
	for _, r := range rows {
		kind, name, _ := strings.Cut(r, "|")
		switch kind {
		case "f":
			funcs[name] = true
			nf++
		case "t":
			types[name] = true
			nt++
		}
	}
	log.Printf("PostgreSQL %s: %d types, %d functions", version, nt, nf)
}

func sorted(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func render(versions string, types, funcs map[string]bool) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by oracle/cmd/genbuiltins; DO NOT EDIT.

// This file lists the names of the types and functions of pg_catalog
// (pg_type, pg_proc) on the servers of PostgreSQL %s,
// and the type keywords that the grammar maps to pg_catalog. It was
// generated with
//
//	. tools/env.sh && cd oracle && go run ./cmd/genbuiltins -versions "%s" -out ../builtins_gen.go
//
// Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
// Portions Copyright (c) 1994, Regents of the University of California
//
// PostgreSQL License: see LICENSE.PostgreSQL.

package pgschema

`, strings.Join(strings.Fields(versions), ", "), versions)
	list := func(name, doc string, names []string) {
		fmt.Fprintf(&b, "// %s %s\nvar %s = []string{\n", name, doc, name)
		line := 0
		for _, n := range names {
			q := fmt.Sprintf("%q,", n)
			if line > 0 && line+1+len(q) > 100 {
				b.WriteString("\n")
				line = 0
			}
			if line == 0 {
				b.WriteString("\t")
			} else {
				b.WriteString(" ")
			}
			b.WriteString(q)
			line += 1 + len(q)
		}
		b.WriteString("\n}\n\n")
	}
	list("builtinTypes", "are the type names of pg_catalog, with the array types and\n// the type keywords, sorted.", sorted(types))
	list("builtinFunctions", "are the names of the functions, aggregates and procedures\n// of pg_catalog, sorted.", sorted(funcs))
	return b.Bytes()
}
