//go:build wasm2go

// Package libpgquery is libpg_query compiled to WebAssembly and translated to
// Go by wasm2go: plain Go, no WebAssembly runtime, no cgo, nothing compiled at
// run time. libpg_query.go and libc.go are generated by ../../wasm2go/build.sh;
// this file is the API.
//
// The functions return the same bytes as the functions of the same name in
// github.com/wasilibs/go-pgquery/parser, whose C sources are translated.
package libpgquery

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"os"
	"sync"
	"time"
)

// Error is a libpg_query error (PgQueryError).
type Error struct {
	Message   string // exception message
	Funcname  string // source function of exception
	Filename  string // source file of exception
	Lineno    int    // source line of exception
	Cursorpos int    // char in query at which exception occurred, from 1
	Context   string // additional context
}

func (e *Error) Error() string { return e.Message }

// ParseToProtobuf parses SQL into a protobuf parse tree (pg_query.ParseResult).
func ParseToProtobuf(sql string) ([]byte, error) {
	return call(func(in *instance) ([]byte, error) {
		return in.bytesResult(sql, (*Module).Xpg_query_parse_protobuf, (*Module).Xpg_query_free_protobuf_parse_result)
	})
}

// ScanToProtobuf scans SQL into protobuf tokens (pg_query.ScanResult).
func ScanToProtobuf(sql string) ([]byte, error) {
	return call(func(in *instance) ([]byte, error) {
		return in.bytesResult(sql, (*Module).Xpg_query_scan, (*Module).Xpg_query_free_scan_result)
	})
}

// ParsePlPgSqlToJSON parses the PL/pgSQL functions of SQL into JSON.
func ParsePlPgSqlToJSON(sql string) (string, error) {
	return call(func(in *instance) (string, error) {
		m := in.m
		input := in.cstring(sql)
		defer m.Xfree(input)
		res := m.Xmalloc(8) // PgQueryPlpgsqlParseResult
		defer m.Xfree(res)
		m.Xpg_query_parse_plpgsql(res, input)
		defer m.Xpg_query_free_plpgsql_parse_result(res)
		if e := in.u32(res + 4); e != 0 {
			return "", in.err(e)
		}
		return in.str(res), nil
	})
}

// instance is one copy of the module with its own linear memory. It runs
// one call at a time; concurrent calls take different instances.
type instance struct{ m *Module }

var pool = sync.Pool{New: func() any { return newInstance() }}

func newInstance() *instance {
	h := &host{}
	m := New(h)
	h.m = m
	m.X_initialize()
	m.Xpg_query_init()
	return &instance{m: m}
}

// call runs f on a pooled instance. A panic means an assertion or abort in
// the C code: the instance may be broken, so it is dropped and the panic is
// returned as an error.
func call[T any](f func(in *instance) (T, error)) (res T, err error) {
	in := pool.Get().(*instance)
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("libpg_query: %v", r)
			return
		}
		pool.Put(in)
	}()
	return f(in)
}

// bytesResult calls a function returning a PgQueryProtobufParseResult or a
// PgQueryScanResult: {len, data, stderr_buffer, error}.
func (in *instance) bytesResult(sql string, fn func(*Module, int32, int32), free func(*Module, int32)) ([]byte, error) {
	m := in.m
	input := in.cstring(sql)
	defer m.Xfree(input)
	res := m.Xmalloc(16)
	defer m.Xfree(res)
	fn(m, res, input)
	defer free(m, res)
	if e := in.u32(res + 12); e != 0 {
		return nil, in.err(e)
	}
	n, data := in.u32(res), in.u32(res+4)
	return bytes.Clone(m.memory[data : data+n]), nil
}

// The memory slice can be replaced when the module grows its memory, so it
// is read from the module after every call.

// cstring copies s into the module memory as a C string.
func (in *instance) cstring(s string) int32 {
	p := in.m.Xmalloc(int32(len(s) + 1))
	mem := in.m.memory[uint32(p):]
	copy(mem, s)
	mem[len(s)] = 0
	return p
}

// u32 reads a 32-bit value (a pointer or a size) at address p.
func (in *instance) u32(p int32) uint32 { return binary.LittleEndian.Uint32(in.m.memory[uint32(p):]) }

// str reads the C string the pointer at address pp points to.
func (in *instance) str(pp int32) string {
	p := in.u32(pp)
	if p == 0 {
		return ""
	}
	mem := in.m.memory[p:]
	return string(mem[:bytes.IndexByte(mem, 0)])
}

// err reads the PgQueryError at address p.
func (in *instance) err(p uint32) error {
	q := int32(p)
	return &Error{
		Message:   in.str(q),
		Funcname:  in.str(q + 4),
		Filename:  in.str(q + 8),
		Lineno:    int(int32(in.u32(q + 12))),
		Cursorpos: int(int32(in.u32(q + 16))),
		Context:   in.str(q + 20),
	}
}

// host implements the WASI functions libpg_query imports. Only stdout and
// stderr exist; libpg_query writes to stderr only when an assertion fails.
type host struct{ m *Module }

const errnoBadf = 8

func (h *host) Xfd_close(fd int32) int32                              { return errnoBadf }
func (h *host) Xfd_fdstat_get(fd, stat int32) int32                   { return errnoBadf }
func (h *host) Xfd_read(fd, iovs, n, nread int32) int32               { return errnoBadf }
func (h *host) Xfd_seek(fd int32, off int64, whence, res int32) int32 { return errnoBadf }
func (h *host) Xproc_exit(code int32)                                 { panic(fmt.Sprintf("proc_exit(%d)", code)) }

func (h *host) Xclock_time_get(id int32, precision int64, res int32) int32 {
	binary.LittleEndian.PutUint64(h.m.memory[res:], uint64(time.Now().UnixNano()))
	return 0
}

func (h *host) Xfd_write(fd, iovs, n, nwritten int32) int32 {
	if fd != 1 && fd != 2 {
		return errnoBadf
	}
	mem := h.m.memory
	total := 0
	for i := int32(0); i < n; i++ {
		p := binary.LittleEndian.Uint32(mem[iovs+8*i:])
		l := binary.LittleEndian.Uint32(mem[iovs+8*i+4:])
		_, _ = os.Stderr.Write(mem[p : p+l])
		total += int(l)
	}
	binary.LittleEndian.PutUint32(mem[nwritten:], uint32(total))
	return 0
}
