// Code generated by libc-gen. DO NOT EDIT.

//go:build wasm2go

package libpgquery

func (m *Module) __throw_longjmp() { panic("emscripten_longjmp") }
func (m *Module) __catch_longjmp(sp int32) {
	if r := recover(); r == "emscripten_longjmp" {
		*m.X__stack_pointer() = sp
	} else if r != nil {
		panic(r)
	}
}
func (m *Module) _invoke_i(idx int32) int32 {
	defer m.__catch_longjmp(*m.X__stack_pointer())
	return (*m.X__indirect_function_table())[idx].(func() int32)()
}
func (m *Module) _invoke_ii(idx int32, v1 int32) int32 {
	defer m.__catch_longjmp(*m.X__stack_pointer())
	return (*m.X__indirect_function_table())[idx].(func(int32) int32)(v1)
}
func (m *Module) _invoke_iii(idx int32, v1 int32, v2 int32) int32 {
	defer m.__catch_longjmp(*m.X__stack_pointer())
	return (*m.X__indirect_function_table())[idx].(func(int32, int32) int32)(v1, v2)
}
func (m *Module) _invoke_iiii(idx int32, v1 int32, v2 int32, v3 int32) int32 {
	defer m.__catch_longjmp(*m.X__stack_pointer())
	return (*m.X__indirect_function_table())[idx].(func(int32, int32, int32) int32)(v1, v2, v3)
}
func (m *Module) _invoke_iiiii(idx int32, v1 int32, v2 int32, v3 int32, v4 int32) int32 {
	defer m.__catch_longjmp(*m.X__stack_pointer())
	return (*m.X__indirect_function_table())[idx].(func(int32, int32, int32, int32) int32)(v1, v2, v3, v4)
}
func (m *Module) _invoke_iiiiii(idx int32, v1 int32, v2 int32, v3 int32, v4 int32, v5 int32) int32 {
	defer m.__catch_longjmp(*m.X__stack_pointer())
	return (*m.X__indirect_function_table())[idx].(func(int32, int32, int32, int32, int32) int32)(v1, v2, v3, v4, v5)
}
func (m *Module) _invoke_v(idx int32) {
	defer m.__catch_longjmp(*m.X__stack_pointer())
	(*m.X__indirect_function_table())[idx].(func())()
}
func (m *Module) _invoke_vi(idx int32, v1 int32) {
	defer m.__catch_longjmp(*m.X__stack_pointer())
	(*m.X__indirect_function_table())[idx].(func(int32))(v1)
}
func (m *Module) _invoke_vii(idx int32, v1 int32, v2 int32) {
	defer m.__catch_longjmp(*m.X__stack_pointer())
	(*m.X__indirect_function_table())[idx].(func(int32, int32))(v1, v2)
}
func (m *Module) _invoke_viii(idx int32, v1 int32, v2 int32, v3 int32) {
	defer m.__catch_longjmp(*m.X__stack_pointer())
	(*m.X__indirect_function_table())[idx].(func(int32, int32, int32))(v1, v2, v3)
}
func (m *Module) _invoke_viiii(idx int32, v1 int32, v2 int32, v3 int32, v4 int32) {
	defer m.__catch_longjmp(*m.X__stack_pointer())
	(*m.X__indirect_function_table())[idx].(func(int32, int32, int32, int32))(v1, v2, v3, v4)
}
