// Code generated by oracle/cmd/genast from the node descriptions of
// libpg_query (pg_query.proto); DO NOT EDIT.
//
// The nodes follow PostgreSQL's src/include/nodes/parsenodes.h and
// primnodes.h.
//
// Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
// Portions Copyright (c) 1994, Regents of the University of California
//
// PostgreSQL License: see ../../LICENSE.PostgreSQL. The descriptions come
// from libpg_query (BSD-3-Clause, Copyright (c) 2015, Lukas Fittl;
// see ../../LICENSE.libpg_query).

package ast

// Children implements Node.
func (n *Alias) Children(f func(Node)) {
	for _, c := range n.Colnames {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *RangeVar) Children(f func(Node)) {
	if n.Alias != nil {
		f(n.Alias)
	}
}

// Children implements Node.
func (n *TableFunc) Children(f func(Node)) {
	for _, c := range n.NsUris {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.NsNames {
		if c != nil {
			f(c)
		}
	}
	if n.Docexpr != nil {
		f(n.Docexpr)
	}
	if n.Rowexpr != nil {
		f(n.Rowexpr)
	}
	for _, c := range n.Colnames {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Coltypes {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Coltypmods {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Colcollations {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Colexprs {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Coldefexprs {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Colvalexprs {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Passingvalexprs {
		if c != nil {
			f(c)
		}
	}
	if n.Plan != nil {
		f(n.Plan)
	}
}

// Children implements Node.
func (n *IntoClause) Children(f func(Node)) {
	if n.Rel != nil {
		f(n.Rel)
	}
	for _, c := range n.ColNames {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
	if n.ViewQuery != nil {
		f(n.ViewQuery)
	}
}

// Children implements Node.
func (n *Var) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
}

// Children implements Node.
func (n *Param) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
}

// Children implements Node.
func (n *Aggref) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Aggargtypes {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Aggdirectargs {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Aggorder {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Aggdistinct {
		if c != nil {
			f(c)
		}
	}
	if n.Aggfilter != nil {
		f(n.Aggfilter)
	}
}

// Children implements Node.
func (n *GroupingFunc) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Refs {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *WindowFunc) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
	if n.Aggfilter != nil {
		f(n.Aggfilter)
	}
	for _, c := range n.RunCondition {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *WindowFuncRunCondition) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *MergeSupportFunc) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
}

// Children implements Node.
func (n *SubscriptingRef) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Refupperindexpr {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Reflowerindexpr {
		if c != nil {
			f(c)
		}
	}
	if n.Refexpr != nil {
		f(n.Refexpr)
	}
	if n.Refassgnexpr != nil {
		f(n.Refassgnexpr)
	}
}

// Children implements Node.
func (n *FuncExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *NamedArgExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *OpExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *DistinctExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *NullIfExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *ScalarArrayOpExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *BoolExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *SubLink) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Testexpr != nil {
		f(n.Testexpr)
	}
	for _, c := range n.OperName {
		if c != nil {
			f(c)
		}
	}
	if n.Subselect != nil {
		f(n.Subselect)
	}
}

// Children implements Node.
func (n *SubPlan) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Testexpr != nil {
		f(n.Testexpr)
	}
	for _, c := range n.ParamIds {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.SetParam {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.ParParam {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlternativeSubPlan) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Subplans {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *FieldSelect) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *FieldStore) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
	for _, c := range n.Newvals {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Fieldnums {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *RelabelType) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *CoerceViaIO) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *ArrayCoerceExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
	if n.Elemexpr != nil {
		f(n.Elemexpr)
	}
}

// Children implements Node.
func (n *ConvertRowtypeExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *CollateExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *CaseExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
	if n.Defresult != nil {
		f(n.Defresult)
	}
}

// Children implements Node.
func (n *CaseWhen) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Expr != nil {
		f(n.Expr)
	}
	if n.Result != nil {
		f(n.Result)
	}
}

// Children implements Node.
func (n *CaseTestExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
}

// Children implements Node.
func (n *ArrayExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Elements {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *RowExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Colnames {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *RowCompareExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Opnos {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Opfamilies {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Inputcollids {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Largs {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Rargs {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CoalesceExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *MinMaxExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *SQLValueFunction) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
}

// Children implements Node.
func (n *XmlExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.NamedArgs {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.ArgNames {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *JsonFormat) Children(f func(Node)) {}

// Children implements Node.
func (n *JsonReturning) Children(f func(Node)) {
	if n.Format != nil {
		f(n.Format)
	}
}

// Children implements Node.
func (n *JsonValueExpr) Children(f func(Node)) {
	if n.RawExpr != nil {
		f(n.RawExpr)
	}
	if n.FormattedExpr != nil {
		f(n.FormattedExpr)
	}
	if n.Format != nil {
		f(n.Format)
	}
}

// Children implements Node.
func (n *JsonConstructorExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
	if n.Func != nil {
		f(n.Func)
	}
	if n.Coercion != nil {
		f(n.Coercion)
	}
	if n.Returning != nil {
		f(n.Returning)
	}
}

// Children implements Node.
func (n *JsonIsPredicate) Children(f func(Node)) {
	if n.Expr != nil {
		f(n.Expr)
	}
	if n.Format != nil {
		f(n.Format)
	}
}

// Children implements Node.
func (n *JsonBehavior) Children(f func(Node)) {
	if n.Expr != nil {
		f(n.Expr)
	}
}

// Children implements Node.
func (n *JsonExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.FormattedExpr != nil {
		f(n.FormattedExpr)
	}
	if n.Format != nil {
		f(n.Format)
	}
	if n.PathSpec != nil {
		f(n.PathSpec)
	}
	if n.Returning != nil {
		f(n.Returning)
	}
	for _, c := range n.PassingNames {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.PassingValues {
		if c != nil {
			f(c)
		}
	}
	if n.OnEmpty != nil {
		f(n.OnEmpty)
	}
	if n.OnError != nil {
		f(n.OnError)
	}
}

// Children implements Node.
func (n *JsonTablePath) Children(f func(Node)) {}

// Children implements Node.
func (n *JsonTablePathScan) Children(f func(Node)) {
	if n.Plan != nil {
		f(n.Plan)
	}
	if n.Path != nil {
		f(n.Path)
	}
	if n.Child != nil {
		f(n.Child)
	}
}

// Children implements Node.
func (n *JsonTableSiblingJoin) Children(f func(Node)) {
	if n.Plan != nil {
		f(n.Plan)
	}
	if n.Lplan != nil {
		f(n.Lplan)
	}
	if n.Rplan != nil {
		f(n.Rplan)
	}
}

// Children implements Node.
func (n *NullTest) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *BooleanTest) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *MergeAction) Children(f func(Node)) {
	if n.Qual != nil {
		f(n.Qual)
	}
	for _, c := range n.TargetList {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.UpdateColnos {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CoerceToDomain) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *CoerceToDomainValue) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
}

// Children implements Node.
func (n *SetToDefault) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
}

// Children implements Node.
func (n *CurrentOfExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
}

// Children implements Node.
func (n *NextValueExpr) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
}

// Children implements Node.
func (n *InferenceElem) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Expr != nil {
		f(n.Expr)
	}
}

// Children implements Node.
func (n *TargetEntry) Children(f func(Node)) {
	if n.Xpr != nil {
		f(n.Xpr)
	}
	if n.Expr != nil {
		f(n.Expr)
	}
}

// Children implements Node.
func (n *RangeTblRef) Children(f func(Node)) {}

// Children implements Node.
func (n *JoinExpr) Children(f func(Node)) {
	if n.Larg != nil {
		f(n.Larg)
	}
	if n.Rarg != nil {
		f(n.Rarg)
	}
	for _, c := range n.UsingClause {
		if c != nil {
			f(c)
		}
	}
	if n.JoinUsingAlias != nil {
		f(n.JoinUsingAlias)
	}
	if n.Quals != nil {
		f(n.Quals)
	}
	if n.Alias != nil {
		f(n.Alias)
	}
}

// Children implements Node.
func (n *FromExpr) Children(f func(Node)) {
	for _, c := range n.Fromlist {
		if c != nil {
			f(c)
		}
	}
	if n.Quals != nil {
		f(n.Quals)
	}
}

// Children implements Node.
func (n *OnConflictExpr) Children(f func(Node)) {
	for _, c := range n.ArbiterElems {
		if c != nil {
			f(c)
		}
	}
	if n.ArbiterWhere != nil {
		f(n.ArbiterWhere)
	}
	for _, c := range n.OnConflictSet {
		if c != nil {
			f(c)
		}
	}
	if n.OnConflictWhere != nil {
		f(n.OnConflictWhere)
	}
	for _, c := range n.ExclRelTlist {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *Query) Children(f func(Node)) {
	if n.UtilityStmt != nil {
		f(n.UtilityStmt)
	}
	for _, c := range n.CteList {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Rtable {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Rteperminfos {
		if c != nil {
			f(c)
		}
	}
	if n.Jointree != nil {
		f(n.Jointree)
	}
	for _, c := range n.MergeActionList {
		if c != nil {
			f(c)
		}
	}
	if n.MergeJoinCondition != nil {
		f(n.MergeJoinCondition)
	}
	for _, c := range n.TargetList {
		if c != nil {
			f(c)
		}
	}
	if n.OnConflict != nil {
		f(n.OnConflict)
	}
	for _, c := range n.ReturningList {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.GroupClause {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.GroupingSets {
		if c != nil {
			f(c)
		}
	}
	if n.HavingQual != nil {
		f(n.HavingQual)
	}
	for _, c := range n.WindowClause {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.DistinctClause {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.SortClause {
		if c != nil {
			f(c)
		}
	}
	if n.LimitOffset != nil {
		f(n.LimitOffset)
	}
	if n.LimitCount != nil {
		f(n.LimitCount)
	}
	for _, c := range n.RowMarks {
		if c != nil {
			f(c)
		}
	}
	if n.SetOperations != nil {
		f(n.SetOperations)
	}
	for _, c := range n.ConstraintDeps {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.WithCheckOptions {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *TypeName) Children(f func(Node)) {
	for _, c := range n.Names {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Typmods {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.ArrayBounds {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *ColumnRef) Children(f func(Node)) {
	for _, c := range n.Fields {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *ParamRef) Children(f func(Node)) {}

// Children implements Node.
func (n *A_Expr) Children(f func(Node)) {
	for _, c := range n.Name {
		if c != nil {
			f(c)
		}
	}
	if n.Lexpr != nil {
		f(n.Lexpr)
	}
	if n.Rexpr != nil {
		f(n.Rexpr)
	}
}

// Children implements Node.
func (n *TypeCast) Children(f func(Node)) {
	if n.Arg != nil {
		f(n.Arg)
	}
	if n.TypeName != nil {
		f(n.TypeName)
	}
}

// Children implements Node.
func (n *CollateClause) Children(f func(Node)) {
	if n.Arg != nil {
		f(n.Arg)
	}
	for _, c := range n.Collname {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *RoleSpec) Children(f func(Node)) {}

// Children implements Node.
func (n *FuncCall) Children(f func(Node)) {
	for _, c := range n.Funcname {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.AggOrder {
		if c != nil {
			f(c)
		}
	}
	if n.AggFilter != nil {
		f(n.AggFilter)
	}
	if n.Over != nil {
		f(n.Over)
	}
}

// Children implements Node.
func (n *A_Star) Children(f func(Node)) {}

// Children implements Node.
func (n *A_Indices) Children(f func(Node)) {
	if n.Lidx != nil {
		f(n.Lidx)
	}
	if n.Uidx != nil {
		f(n.Uidx)
	}
}

// Children implements Node.
func (n *A_Indirection) Children(f func(Node)) {
	if n.Arg != nil {
		f(n.Arg)
	}
	for _, c := range n.Indirection {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *A_ArrayExpr) Children(f func(Node)) {
	for _, c := range n.Elements {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *ResTarget) Children(f func(Node)) {
	for _, c := range n.Indirection {
		if c != nil {
			f(c)
		}
	}
	if n.Val != nil {
		f(n.Val)
	}
}

// Children implements Node.
func (n *MultiAssignRef) Children(f func(Node)) {
	if n.Source != nil {
		f(n.Source)
	}
}

// Children implements Node.
func (n *SortBy) Children(f func(Node)) {
	if n.Node != nil {
		f(n.Node)
	}
	for _, c := range n.UseOp {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *WindowDef) Children(f func(Node)) {
	for _, c := range n.PartitionClause {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.OrderClause {
		if c != nil {
			f(c)
		}
	}
	if n.StartOffset != nil {
		f(n.StartOffset)
	}
	if n.EndOffset != nil {
		f(n.EndOffset)
	}
}

// Children implements Node.
func (n *RangeSubselect) Children(f func(Node)) {
	if n.Subquery != nil {
		f(n.Subquery)
	}
	if n.Alias != nil {
		f(n.Alias)
	}
}

// Children implements Node.
func (n *RangeFunction) Children(f func(Node)) {
	for _, c := range n.Functions {
		if c != nil {
			f(c)
		}
	}
	if n.Alias != nil {
		f(n.Alias)
	}
	for _, c := range n.Coldeflist {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *RangeTableFunc) Children(f func(Node)) {
	if n.Docexpr != nil {
		f(n.Docexpr)
	}
	if n.Rowexpr != nil {
		f(n.Rowexpr)
	}
	for _, c := range n.Namespaces {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Columns {
		if c != nil {
			f(c)
		}
	}
	if n.Alias != nil {
		f(n.Alias)
	}
}

// Children implements Node.
func (n *RangeTableFuncCol) Children(f func(Node)) {
	if n.TypeName != nil {
		f(n.TypeName)
	}
	if n.Colexpr != nil {
		f(n.Colexpr)
	}
	if n.Coldefexpr != nil {
		f(n.Coldefexpr)
	}
}

// Children implements Node.
func (n *RangeTableSample) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	for _, c := range n.Method {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
	if n.Repeatable != nil {
		f(n.Repeatable)
	}
}

// Children implements Node.
func (n *ColumnDef) Children(f func(Node)) {
	if n.TypeName != nil {
		f(n.TypeName)
	}
	if n.RawDefault != nil {
		f(n.RawDefault)
	}
	if n.CookedDefault != nil {
		f(n.CookedDefault)
	}
	if n.IdentitySequence != nil {
		f(n.IdentitySequence)
	}
	if n.CollClause != nil {
		f(n.CollClause)
	}
	for _, c := range n.Constraints {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Fdwoptions {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *TableLikeClause) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
}

// Children implements Node.
func (n *IndexElem) Children(f func(Node)) {
	if n.Expr != nil {
		f(n.Expr)
	}
	for _, c := range n.Collation {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Opclass {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Opclassopts {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *DefElem) Children(f func(Node)) {
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *LockingClause) Children(f func(Node)) {
	for _, c := range n.LockedRels {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *XmlSerialize) Children(f func(Node)) {
	if n.Expr != nil {
		f(n.Expr)
	}
	if n.TypeName != nil {
		f(n.TypeName)
	}
}

// Children implements Node.
func (n *PartitionElem) Children(f func(Node)) {
	if n.Expr != nil {
		f(n.Expr)
	}
	for _, c := range n.Collation {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Opclass {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *PartitionSpec) Children(f func(Node)) {
	for _, c := range n.PartParams {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *PartitionBoundSpec) Children(f func(Node)) {
	for _, c := range n.Listdatums {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Lowerdatums {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Upperdatums {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *PartitionRangeDatum) Children(f func(Node)) {
	if n.Value != nil {
		f(n.Value)
	}
}

// Children implements Node.
func (n *SinglePartitionSpec) Children(f func(Node)) {}

// Children implements Node.
func (n *PartitionCmd) Children(f func(Node)) {
	if n.Name != nil {
		f(n.Name)
	}
	if n.Bound != nil {
		f(n.Bound)
	}
}

// Children implements Node.
func (n *RangeTblEntry) Children(f func(Node)) {
	if n.Alias != nil {
		f(n.Alias)
	}
	if n.Eref != nil {
		f(n.Eref)
	}
	if n.Tablesample != nil {
		f(n.Tablesample)
	}
	if n.Subquery != nil {
		f(n.Subquery)
	}
	for _, c := range n.Joinaliasvars {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Joinleftcols {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Joinrightcols {
		if c != nil {
			f(c)
		}
	}
	if n.JoinUsingAlias != nil {
		f(n.JoinUsingAlias)
	}
	for _, c := range n.Functions {
		if c != nil {
			f(c)
		}
	}
	if n.Tablefunc != nil {
		f(n.Tablefunc)
	}
	for _, c := range n.ValuesLists {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Coltypes {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Coltypmods {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Colcollations {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.SecurityQuals {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *RTEPermissionInfo) Children(f func(Node)) {}

// Children implements Node.
func (n *RangeTblFunction) Children(f func(Node)) {
	if n.Funcexpr != nil {
		f(n.Funcexpr)
	}
	for _, c := range n.Funccolnames {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Funccoltypes {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Funccoltypmods {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Funccolcollations {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *TableSampleClause) Children(f func(Node)) {
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
	if n.Repeatable != nil {
		f(n.Repeatable)
	}
}

// Children implements Node.
func (n *WithCheckOption) Children(f func(Node)) {
	if n.Qual != nil {
		f(n.Qual)
	}
}

// Children implements Node.
func (n *SortGroupClause) Children(f func(Node)) {}

// Children implements Node.
func (n *GroupingSet) Children(f func(Node)) {
	for _, c := range n.Content {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *WindowClause) Children(f func(Node)) {
	for _, c := range n.PartitionClause {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.OrderClause {
		if c != nil {
			f(c)
		}
	}
	if n.StartOffset != nil {
		f(n.StartOffset)
	}
	if n.EndOffset != nil {
		f(n.EndOffset)
	}
}

// Children implements Node.
func (n *RowMarkClause) Children(f func(Node)) {}

// Children implements Node.
func (n *WithClause) Children(f func(Node)) {
	for _, c := range n.Ctes {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *InferClause) Children(f func(Node)) {
	for _, c := range n.IndexElems {
		if c != nil {
			f(c)
		}
	}
	if n.WhereClause != nil {
		f(n.WhereClause)
	}
}

// Children implements Node.
func (n *OnConflictClause) Children(f func(Node)) {
	if n.Infer != nil {
		f(n.Infer)
	}
	for _, c := range n.TargetList {
		if c != nil {
			f(c)
		}
	}
	if n.WhereClause != nil {
		f(n.WhereClause)
	}
}

// Children implements Node.
func (n *CTESearchClause) Children(f func(Node)) {
	for _, c := range n.SearchColList {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CTECycleClause) Children(f func(Node)) {
	for _, c := range n.CycleColList {
		if c != nil {
			f(c)
		}
	}
	if n.CycleMarkValue != nil {
		f(n.CycleMarkValue)
	}
	if n.CycleMarkDefault != nil {
		f(n.CycleMarkDefault)
	}
}

// Children implements Node.
func (n *CommonTableExpr) Children(f func(Node)) {
	for _, c := range n.Aliascolnames {
		if c != nil {
			f(c)
		}
	}
	if n.Ctequery != nil {
		f(n.Ctequery)
	}
	if n.SearchClause != nil {
		f(n.SearchClause)
	}
	if n.CycleClause != nil {
		f(n.CycleClause)
	}
	for _, c := range n.Ctecolnames {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Ctecoltypes {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Ctecoltypmods {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Ctecolcollations {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *MergeWhenClause) Children(f func(Node)) {
	if n.Condition != nil {
		f(n.Condition)
	}
	for _, c := range n.TargetList {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Values {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *TriggerTransition) Children(f func(Node)) {}

// Children implements Node.
func (n *JsonOutput) Children(f func(Node)) {
	if n.TypeName != nil {
		f(n.TypeName)
	}
	if n.Returning != nil {
		f(n.Returning)
	}
}

// Children implements Node.
func (n *JsonArgument) Children(f func(Node)) {
	if n.Val != nil {
		f(n.Val)
	}
}

// Children implements Node.
func (n *JsonFuncExpr) Children(f func(Node)) {
	if n.ContextItem != nil {
		f(n.ContextItem)
	}
	if n.Pathspec != nil {
		f(n.Pathspec)
	}
	for _, c := range n.Passing {
		if c != nil {
			f(c)
		}
	}
	if n.Output != nil {
		f(n.Output)
	}
	if n.OnEmpty != nil {
		f(n.OnEmpty)
	}
	if n.OnError != nil {
		f(n.OnError)
	}
}

// Children implements Node.
func (n *JsonTablePathSpec) Children(f func(Node)) {
	if n.String != nil {
		f(n.String)
	}
}

// Children implements Node.
func (n *JsonTable) Children(f func(Node)) {
	if n.ContextItem != nil {
		f(n.ContextItem)
	}
	if n.Pathspec != nil {
		f(n.Pathspec)
	}
	for _, c := range n.Passing {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Columns {
		if c != nil {
			f(c)
		}
	}
	if n.OnError != nil {
		f(n.OnError)
	}
	if n.Alias != nil {
		f(n.Alias)
	}
}

// Children implements Node.
func (n *JsonTableColumn) Children(f func(Node)) {
	if n.TypeName != nil {
		f(n.TypeName)
	}
	if n.Pathspec != nil {
		f(n.Pathspec)
	}
	if n.Format != nil {
		f(n.Format)
	}
	for _, c := range n.Columns {
		if c != nil {
			f(c)
		}
	}
	if n.OnEmpty != nil {
		f(n.OnEmpty)
	}
	if n.OnError != nil {
		f(n.OnError)
	}
}

// Children implements Node.
func (n *JsonKeyValue) Children(f func(Node)) {
	if n.Key != nil {
		f(n.Key)
	}
	if n.Value != nil {
		f(n.Value)
	}
}

// Children implements Node.
func (n *JsonParseExpr) Children(f func(Node)) {
	if n.Expr != nil {
		f(n.Expr)
	}
	if n.Output != nil {
		f(n.Output)
	}
}

// Children implements Node.
func (n *JsonScalarExpr) Children(f func(Node)) {
	if n.Expr != nil {
		f(n.Expr)
	}
	if n.Output != nil {
		f(n.Output)
	}
}

// Children implements Node.
func (n *JsonSerializeExpr) Children(f func(Node)) {
	if n.Expr != nil {
		f(n.Expr)
	}
	if n.Output != nil {
		f(n.Output)
	}
}

// Children implements Node.
func (n *JsonObjectConstructor) Children(f func(Node)) {
	for _, c := range n.Exprs {
		if c != nil {
			f(c)
		}
	}
	if n.Output != nil {
		f(n.Output)
	}
}

// Children implements Node.
func (n *JsonArrayConstructor) Children(f func(Node)) {
	for _, c := range n.Exprs {
		if c != nil {
			f(c)
		}
	}
	if n.Output != nil {
		f(n.Output)
	}
}

// Children implements Node.
func (n *JsonArrayQueryConstructor) Children(f func(Node)) {
	if n.Query != nil {
		f(n.Query)
	}
	if n.Output != nil {
		f(n.Output)
	}
	if n.Format != nil {
		f(n.Format)
	}
}

// Children implements Node.
func (n *JsonAggConstructor) Children(f func(Node)) {
	if n.Output != nil {
		f(n.Output)
	}
	if n.AggFilter != nil {
		f(n.AggFilter)
	}
	for _, c := range n.AggOrder {
		if c != nil {
			f(c)
		}
	}
	if n.Over != nil {
		f(n.Over)
	}
}

// Children implements Node.
func (n *JsonObjectAgg) Children(f func(Node)) {
	if n.Constructor != nil {
		f(n.Constructor)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *JsonArrayAgg) Children(f func(Node)) {
	if n.Constructor != nil {
		f(n.Constructor)
	}
	if n.Arg != nil {
		f(n.Arg)
	}
}

// Children implements Node.
func (n *RawStmt) Children(f func(Node)) {
	if n.Stmt != nil {
		f(n.Stmt)
	}
}

// Children implements Node.
func (n *InsertStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	for _, c := range n.Cols {
		if c != nil {
			f(c)
		}
	}
	if n.SelectStmt != nil {
		f(n.SelectStmt)
	}
	if n.OnConflictClause != nil {
		f(n.OnConflictClause)
	}
	for _, c := range n.ReturningList {
		if c != nil {
			f(c)
		}
	}
	if n.WithClause != nil {
		f(n.WithClause)
	}
}

// Children implements Node.
func (n *DeleteStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	for _, c := range n.UsingClause {
		if c != nil {
			f(c)
		}
	}
	if n.WhereClause != nil {
		f(n.WhereClause)
	}
	for _, c := range n.ReturningList {
		if c != nil {
			f(c)
		}
	}
	if n.WithClause != nil {
		f(n.WithClause)
	}
}

// Children implements Node.
func (n *UpdateStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	for _, c := range n.TargetList {
		if c != nil {
			f(c)
		}
	}
	if n.WhereClause != nil {
		f(n.WhereClause)
	}
	for _, c := range n.FromClause {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.ReturningList {
		if c != nil {
			f(c)
		}
	}
	if n.WithClause != nil {
		f(n.WithClause)
	}
}

// Children implements Node.
func (n *MergeStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	if n.SourceRelation != nil {
		f(n.SourceRelation)
	}
	if n.JoinCondition != nil {
		f(n.JoinCondition)
	}
	for _, c := range n.MergeWhenClauses {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.ReturningList {
		if c != nil {
			f(c)
		}
	}
	if n.WithClause != nil {
		f(n.WithClause)
	}
}

// Children implements Node.
func (n *SelectStmt) Children(f func(Node)) {
	for _, c := range n.DistinctClause {
		if c != nil {
			f(c)
		}
	}
	if n.IntoClause != nil {
		f(n.IntoClause)
	}
	for _, c := range n.TargetList {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.FromClause {
		if c != nil {
			f(c)
		}
	}
	if n.WhereClause != nil {
		f(n.WhereClause)
	}
	for _, c := range n.GroupClause {
		if c != nil {
			f(c)
		}
	}
	if n.HavingClause != nil {
		f(n.HavingClause)
	}
	for _, c := range n.WindowClause {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.ValuesLists {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.SortClause {
		if c != nil {
			f(c)
		}
	}
	if n.LimitOffset != nil {
		f(n.LimitOffset)
	}
	if n.LimitCount != nil {
		f(n.LimitCount)
	}
	for _, c := range n.LockingClause {
		if c != nil {
			f(c)
		}
	}
	if n.WithClause != nil {
		f(n.WithClause)
	}
	if n.Larg != nil {
		f(n.Larg)
	}
	if n.Rarg != nil {
		f(n.Rarg)
	}
}

// Children implements Node.
func (n *SetOperationStmt) Children(f func(Node)) {
	if n.Larg != nil {
		f(n.Larg)
	}
	if n.Rarg != nil {
		f(n.Rarg)
	}
	for _, c := range n.ColTypes {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.ColTypmods {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.ColCollations {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.GroupClauses {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *ReturnStmt) Children(f func(Node)) {
	if n.Returnval != nil {
		f(n.Returnval)
	}
}

// Children implements Node.
func (n *PLAssignStmt) Children(f func(Node)) {
	for _, c := range n.Indirection {
		if c != nil {
			f(c)
		}
	}
	if n.Val != nil {
		f(n.Val)
	}
}

// Children implements Node.
func (n *CreateSchemaStmt) Children(f func(Node)) {
	if n.Authrole != nil {
		f(n.Authrole)
	}
	for _, c := range n.SchemaElts {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterTableStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	for _, c := range n.Cmds {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *ReplicaIdentityStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *AlterTableCmd) Children(f func(Node)) {
	if n.Newowner != nil {
		f(n.Newowner)
	}
	if n.Def != nil {
		f(n.Def)
	}
}

// Children implements Node.
func (n *AlterCollationStmt) Children(f func(Node)) {
	for _, c := range n.Collname {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterDomainStmt) Children(f func(Node)) {
	for _, c := range n.TypeName {
		if c != nil {
			f(c)
		}
	}
	if n.Def != nil {
		f(n.Def)
	}
}

// Children implements Node.
func (n *GrantStmt) Children(f func(Node)) {
	for _, c := range n.Objects {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Privileges {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Grantees {
		if c != nil {
			f(c)
		}
	}
	if n.Grantor != nil {
		f(n.Grantor)
	}
}

// Children implements Node.
func (n *ObjectWithArgs) Children(f func(Node)) {
	for _, c := range n.Objname {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Objargs {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Objfuncargs {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AccessPriv) Children(f func(Node)) {
	for _, c := range n.Cols {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *GrantRoleStmt) Children(f func(Node)) {
	for _, c := range n.GrantedRoles {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.GranteeRoles {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Opt {
		if c != nil {
			f(c)
		}
	}
	if n.Grantor != nil {
		f(n.Grantor)
	}
}

// Children implements Node.
func (n *AlterDefaultPrivilegesStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
	if n.Action != nil {
		f(n.Action)
	}
}

// Children implements Node.
func (n *CopyStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	if n.Query != nil {
		f(n.Query)
	}
	for _, c := range n.Attlist {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
	if n.WhereClause != nil {
		f(n.WhereClause)
	}
}

// Children implements Node.
func (n *VariableSetStmt) Children(f func(Node)) {
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *VariableShowStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *CreateStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	for _, c := range n.TableElts {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.InhRelations {
		if c != nil {
			f(c)
		}
	}
	if n.Partbound != nil {
		f(n.Partbound)
	}
	if n.Partspec != nil {
		f(n.Partspec)
	}
	if n.OfTypename != nil {
		f(n.OfTypename)
	}
	for _, c := range n.Constraints {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *Constraint) Children(f func(Node)) {
	if n.RawExpr != nil {
		f(n.RawExpr)
	}
	for _, c := range n.Keys {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Including {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Exclusions {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
	if n.WhereClause != nil {
		f(n.WhereClause)
	}
	if n.Pktable != nil {
		f(n.Pktable)
	}
	for _, c := range n.FkAttrs {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.PkAttrs {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.FkDelSetCols {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.OldConpfeqop {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateTableSpaceStmt) Children(f func(Node)) {
	if n.Owner != nil {
		f(n.Owner)
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *DropTableSpaceStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *AlterTableSpaceOptionsStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterTableMoveAllStmt) Children(f func(Node)) {
	for _, c := range n.Roles {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateExtensionStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterExtensionStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterExtensionContentsStmt) Children(f func(Node)) {
	if n.Object != nil {
		f(n.Object)
	}
}

// Children implements Node.
func (n *CreateFdwStmt) Children(f func(Node)) {
	for _, c := range n.FuncOptions {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterFdwStmt) Children(f func(Node)) {
	for _, c := range n.FuncOptions {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateForeignServerStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterForeignServerStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateForeignTableStmt) Children(f func(Node)) {
	if n.BaseStmt != nil {
		f(n.BaseStmt)
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateUserMappingStmt) Children(f func(Node)) {
	if n.User != nil {
		f(n.User)
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterUserMappingStmt) Children(f func(Node)) {
	if n.User != nil {
		f(n.User)
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *DropUserMappingStmt) Children(f func(Node)) {
	if n.User != nil {
		f(n.User)
	}
}

// Children implements Node.
func (n *ImportForeignSchemaStmt) Children(f func(Node)) {
	for _, c := range n.TableList {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreatePolicyStmt) Children(f func(Node)) {
	if n.Table != nil {
		f(n.Table)
	}
	for _, c := range n.Roles {
		if c != nil {
			f(c)
		}
	}
	if n.Qual != nil {
		f(n.Qual)
	}
	if n.WithCheck != nil {
		f(n.WithCheck)
	}
}

// Children implements Node.
func (n *AlterPolicyStmt) Children(f func(Node)) {
	if n.Table != nil {
		f(n.Table)
	}
	for _, c := range n.Roles {
		if c != nil {
			f(c)
		}
	}
	if n.Qual != nil {
		f(n.Qual)
	}
	if n.WithCheck != nil {
		f(n.WithCheck)
	}
}

// Children implements Node.
func (n *CreateAmStmt) Children(f func(Node)) {
	for _, c := range n.HandlerName {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateTrigStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	for _, c := range n.Funcname {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Columns {
		if c != nil {
			f(c)
		}
	}
	if n.WhenClause != nil {
		f(n.WhenClause)
	}
	for _, c := range n.TransitionRels {
		if c != nil {
			f(c)
		}
	}
	if n.Constrrel != nil {
		f(n.Constrrel)
	}
}

// Children implements Node.
func (n *CreateEventTrigStmt) Children(f func(Node)) {
	for _, c := range n.Whenclause {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Funcname {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterEventTrigStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *CreatePLangStmt) Children(f func(Node)) {
	for _, c := range n.Plhandler {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Plinline {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Plvalidator {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateRoleStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterRoleStmt) Children(f func(Node)) {
	if n.Role != nil {
		f(n.Role)
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterRoleSetStmt) Children(f func(Node)) {
	if n.Role != nil {
		f(n.Role)
	}
	if n.Setstmt != nil {
		f(n.Setstmt)
	}
}

// Children implements Node.
func (n *DropRoleStmt) Children(f func(Node)) {
	for _, c := range n.Roles {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateSeqStmt) Children(f func(Node)) {
	if n.Sequence != nil {
		f(n.Sequence)
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterSeqStmt) Children(f func(Node)) {
	if n.Sequence != nil {
		f(n.Sequence)
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *DefineStmt) Children(f func(Node)) {
	for _, c := range n.Defnames {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Definition {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateDomainStmt) Children(f func(Node)) {
	for _, c := range n.Domainname {
		if c != nil {
			f(c)
		}
	}
	if n.TypeName != nil {
		f(n.TypeName)
	}
	if n.CollClause != nil {
		f(n.CollClause)
	}
	for _, c := range n.Constraints {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateOpClassStmt) Children(f func(Node)) {
	for _, c := range n.Opclassname {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Opfamilyname {
		if c != nil {
			f(c)
		}
	}
	if n.Datatype != nil {
		f(n.Datatype)
	}
	for _, c := range n.Items {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateOpClassItem) Children(f func(Node)) {
	if n.Name != nil {
		f(n.Name)
	}
	for _, c := range n.OrderFamily {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.ClassArgs {
		if c != nil {
			f(c)
		}
	}
	if n.Storedtype != nil {
		f(n.Storedtype)
	}
}

// Children implements Node.
func (n *CreateOpFamilyStmt) Children(f func(Node)) {
	for _, c := range n.Opfamilyname {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterOpFamilyStmt) Children(f func(Node)) {
	for _, c := range n.Opfamilyname {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Items {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *DropStmt) Children(f func(Node)) {
	for _, c := range n.Objects {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *TruncateStmt) Children(f func(Node)) {
	for _, c := range n.Relations {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CommentStmt) Children(f func(Node)) {
	if n.Object != nil {
		f(n.Object)
	}
}

// Children implements Node.
func (n *SecLabelStmt) Children(f func(Node)) {
	if n.Object != nil {
		f(n.Object)
	}
}

// Children implements Node.
func (n *DeclareCursorStmt) Children(f func(Node)) {
	if n.Query != nil {
		f(n.Query)
	}
}

// Children implements Node.
func (n *ClosePortalStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *FetchStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *IndexStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	for _, c := range n.IndexParams {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.IndexIncludingParams {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
	if n.WhereClause != nil {
		f(n.WhereClause)
	}
	for _, c := range n.ExcludeOpNames {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateStatsStmt) Children(f func(Node)) {
	for _, c := range n.Defnames {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.StatTypes {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Exprs {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Relations {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *StatsElem) Children(f func(Node)) {
	if n.Expr != nil {
		f(n.Expr)
	}
}

// Children implements Node.
func (n *AlterStatsStmt) Children(f func(Node)) {
	for _, c := range n.Defnames {
		if c != nil {
			f(c)
		}
	}
	if n.Stxstattarget != nil {
		f(n.Stxstattarget)
	}
}

// Children implements Node.
func (n *CreateFunctionStmt) Children(f func(Node)) {
	for _, c := range n.Funcname {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Parameters {
		if c != nil {
			f(c)
		}
	}
	if n.ReturnType != nil {
		f(n.ReturnType)
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
	if n.SqlBody != nil {
		f(n.SqlBody)
	}
}

// Children implements Node.
func (n *FunctionParameter) Children(f func(Node)) {
	if n.ArgType != nil {
		f(n.ArgType)
	}
	if n.Defexpr != nil {
		f(n.Defexpr)
	}
}

// Children implements Node.
func (n *AlterFunctionStmt) Children(f func(Node)) {
	if n.Func != nil {
		f(n.Func)
	}
	for _, c := range n.Actions {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *DoStmt) Children(f func(Node)) {
	for _, c := range n.Args {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *InlineCodeBlock) Children(f func(Node)) {}

// Children implements Node.
func (n *CallStmt) Children(f func(Node)) {
	if n.Funccall != nil {
		f(n.Funccall)
	}
	if n.Funcexpr != nil {
		f(n.Funcexpr)
	}
	for _, c := range n.Outargs {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CallContext) Children(f func(Node)) {}

// Children implements Node.
func (n *RenameStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	if n.Object != nil {
		f(n.Object)
	}
}

// Children implements Node.
func (n *AlterObjectDependsStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	if n.Object != nil {
		f(n.Object)
	}
	if n.Extname != nil {
		f(n.Extname)
	}
}

// Children implements Node.
func (n *AlterObjectSchemaStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	if n.Object != nil {
		f(n.Object)
	}
}

// Children implements Node.
func (n *AlterOwnerStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	if n.Object != nil {
		f(n.Object)
	}
	if n.Newowner != nil {
		f(n.Newowner)
	}
}

// Children implements Node.
func (n *AlterOperatorStmt) Children(f func(Node)) {
	if n.Opername != nil {
		f(n.Opername)
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterTypeStmt) Children(f func(Node)) {
	for _, c := range n.TypeName {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *RuleStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	if n.WhereClause != nil {
		f(n.WhereClause)
	}
	for _, c := range n.Actions {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *NotifyStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *ListenStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *UnlistenStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *TransactionStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CompositeTypeStmt) Children(f func(Node)) {
	if n.Typevar != nil {
		f(n.Typevar)
	}
	for _, c := range n.Coldeflist {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateEnumStmt) Children(f func(Node)) {
	for _, c := range n.TypeName {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Vals {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateRangeStmt) Children(f func(Node)) {
	for _, c := range n.TypeName {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Params {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterEnumStmt) Children(f func(Node)) {
	for _, c := range n.TypeName {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *ViewStmt) Children(f func(Node)) {
	if n.View != nil {
		f(n.View)
	}
	for _, c := range n.Aliases {
		if c != nil {
			f(c)
		}
	}
	if n.Query != nil {
		f(n.Query)
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *LoadStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *CreatedbStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterDatabaseStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterDatabaseRefreshCollStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *AlterDatabaseSetStmt) Children(f func(Node)) {
	if n.Setstmt != nil {
		f(n.Setstmt)
	}
}

// Children implements Node.
func (n *DropdbStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterSystemStmt) Children(f func(Node)) {
	if n.Setstmt != nil {
		f(n.Setstmt)
	}
}

// Children implements Node.
func (n *ClusterStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	for _, c := range n.Params {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *VacuumStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Rels {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *VacuumRelation) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	for _, c := range n.VaCols {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *ExplainStmt) Children(f func(Node)) {
	if n.Query != nil {
		f(n.Query)
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateTableAsStmt) Children(f func(Node)) {
	if n.Query != nil {
		f(n.Query)
	}
	if n.Into != nil {
		f(n.Into)
	}
}

// Children implements Node.
func (n *RefreshMatViewStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
}

// Children implements Node.
func (n *CheckPointStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *DiscardStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *LockStmt) Children(f func(Node)) {
	for _, c := range n.Relations {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *ConstraintsSetStmt) Children(f func(Node)) {
	for _, c := range n.Constraints {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *ReindexStmt) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	for _, c := range n.Params {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateConversionStmt) Children(f func(Node)) {
	for _, c := range n.ConversionName {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.FuncName {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateCastStmt) Children(f func(Node)) {
	if n.Sourcetype != nil {
		f(n.Sourcetype)
	}
	if n.Targettype != nil {
		f(n.Targettype)
	}
	if n.Func != nil {
		f(n.Func)
	}
}

// Children implements Node.
func (n *CreateTransformStmt) Children(f func(Node)) {
	if n.TypeName != nil {
		f(n.TypeName)
	}
	if n.Fromsql != nil {
		f(n.Fromsql)
	}
	if n.Tosql != nil {
		f(n.Tosql)
	}
}

// Children implements Node.
func (n *PrepareStmt) Children(f func(Node)) {
	for _, c := range n.Argtypes {
		if c != nil {
			f(c)
		}
	}
	if n.Query != nil {
		f(n.Query)
	}
}

// Children implements Node.
func (n *ExecuteStmt) Children(f func(Node)) {
	for _, c := range n.Params {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *DeallocateStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *DropOwnedStmt) Children(f func(Node)) {
	for _, c := range n.Roles {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *ReassignOwnedStmt) Children(f func(Node)) {
	for _, c := range n.Roles {
		if c != nil {
			f(c)
		}
	}
	if n.Newrole != nil {
		f(n.Newrole)
	}
}

// Children implements Node.
func (n *AlterTSDictionaryStmt) Children(f func(Node)) {
	for _, c := range n.Dictname {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterTSConfigurationStmt) Children(f func(Node)) {
	for _, c := range n.Cfgname {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Tokentype {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Dicts {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *PublicationTable) Children(f func(Node)) {
	if n.Relation != nil {
		f(n.Relation)
	}
	if n.WhereClause != nil {
		f(n.WhereClause)
	}
	for _, c := range n.Columns {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *PublicationObjSpec) Children(f func(Node)) {
	if n.Pubtable != nil {
		f(n.Pubtable)
	}
}

// Children implements Node.
func (n *CreatePublicationStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Pubobjects {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterPublicationStmt) Children(f func(Node)) {
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Pubobjects {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *CreateSubscriptionStmt) Children(f func(Node)) {
	for _, c := range n.Publication {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *AlterSubscriptionStmt) Children(f func(Node)) {
	for _, c := range n.Publication {
		if c != nil {
			f(c)
		}
	}
	for _, c := range n.Options {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *DropSubscriptionStmt) Children(f func(Node)) {}

// Children implements Node.
func (n *Integer) Children(f func(Node)) {}

// Children implements Node.
func (n *Float) Children(f func(Node)) {}

// Children implements Node.
func (n *Boolean) Children(f func(Node)) {}

// Children implements Node.
func (n *String) Children(f func(Node)) {}

// Children implements Node.
func (n *BitString) Children(f func(Node)) {}

// Children implements Node.
func (n *List) Children(f func(Node)) {
	for _, c := range n.Items {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *IntList) Children(f func(Node)) {
	for _, c := range n.Items {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *OidList) Children(f func(Node)) {
	for _, c := range n.Items {
		if c != nil {
			f(c)
		}
	}
}

// Children implements Node.
func (n *A_Const) Children(f func(Node)) {
	if n.Val != nil {
		f(n.Val)
	}
}
