// Code generated by oracle/cmd/genast from the node descriptions of
// libpg_query (pg_query.proto); DO NOT EDIT.
//
// The nodes follow PostgreSQL's src/include/nodes/parsenodes.h and
// primnodes.h.
//
// Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
// Portions Copyright (c) 1994, Regents of the University of California
//
// PostgreSQL License: see ../../LICENSE.PostgreSQL. The descriptions come
// from libpg_query (BSD-3-Clause, Copyright (c) 2015, Lukas Fittl).

package ast

import "fmt"

// A_Expr_Kind is the PostgreSQL enum A_Expr_Kind.
type A_Expr_Kind int32

const (
	AEXPR_OP              A_Expr_Kind = 0
	AEXPR_OP_ANY          A_Expr_Kind = 1
	AEXPR_OP_ALL          A_Expr_Kind = 2
	AEXPR_DISTINCT        A_Expr_Kind = 3
	AEXPR_NOT_DISTINCT    A_Expr_Kind = 4
	AEXPR_NULLIF          A_Expr_Kind = 5
	AEXPR_IN              A_Expr_Kind = 6
	AEXPR_LIKE            A_Expr_Kind = 7
	AEXPR_ILIKE           A_Expr_Kind = 8
	AEXPR_SIMILAR         A_Expr_Kind = 9
	AEXPR_BETWEEN         A_Expr_Kind = 10
	AEXPR_NOT_BETWEEN     A_Expr_Kind = 11
	AEXPR_BETWEEN_SYM     A_Expr_Kind = 12
	AEXPR_NOT_BETWEEN_SYM A_Expr_Kind = 13
)

func (e A_Expr_Kind) String() string {
	switch e {
	case AEXPR_OP:
		return "AEXPR_OP"
	case AEXPR_OP_ANY:
		return "AEXPR_OP_ANY"
	case AEXPR_OP_ALL:
		return "AEXPR_OP_ALL"
	case AEXPR_DISTINCT:
		return "AEXPR_DISTINCT"
	case AEXPR_NOT_DISTINCT:
		return "AEXPR_NOT_DISTINCT"
	case AEXPR_NULLIF:
		return "AEXPR_NULLIF"
	case AEXPR_IN:
		return "AEXPR_IN"
	case AEXPR_LIKE:
		return "AEXPR_LIKE"
	case AEXPR_ILIKE:
		return "AEXPR_ILIKE"
	case AEXPR_SIMILAR:
		return "AEXPR_SIMILAR"
	case AEXPR_BETWEEN:
		return "AEXPR_BETWEEN"
	case AEXPR_NOT_BETWEEN:
		return "AEXPR_NOT_BETWEEN"
	case AEXPR_BETWEEN_SYM:
		return "AEXPR_BETWEEN_SYM"
	case AEXPR_NOT_BETWEEN_SYM:
		return "AEXPR_NOT_BETWEEN_SYM"
	}
	return fmt.Sprintf("A_Expr_Kind(%d)", int32(e))
}

// AggSplit is the PostgreSQL enum AggSplit.
type AggSplit int32

const (
	AGGSPLIT_SIMPLE         AggSplit = 0
	AGGSPLIT_INITIAL_SERIAL AggSplit = 1
	AGGSPLIT_FINAL_DESERIAL AggSplit = 2
)

func (e AggSplit) String() string {
	switch e {
	case AGGSPLIT_SIMPLE:
		return "AGGSPLIT_SIMPLE"
	case AGGSPLIT_INITIAL_SERIAL:
		return "AGGSPLIT_INITIAL_SERIAL"
	case AGGSPLIT_FINAL_DESERIAL:
		return "AGGSPLIT_FINAL_DESERIAL"
	}
	return fmt.Sprintf("AggSplit(%d)", int32(e))
}

// AggStrategy is the PostgreSQL enum AggStrategy.
type AggStrategy int32

const (
	AGG_PLAIN  AggStrategy = 0
	AGG_SORTED AggStrategy = 1
	AGG_HASHED AggStrategy = 2
	AGG_MIXED  AggStrategy = 3
)

func (e AggStrategy) String() string {
	switch e {
	case AGG_PLAIN:
		return "AGG_PLAIN"
	case AGG_SORTED:
		return "AGG_SORTED"
	case AGG_HASHED:
		return "AGG_HASHED"
	case AGG_MIXED:
		return "AGG_MIXED"
	}
	return fmt.Sprintf("AggStrategy(%d)", int32(e))
}

// AlterPublicationAction is the PostgreSQL enum AlterPublicationAction.
type AlterPublicationAction int32

const (
	AP_AddObjects  AlterPublicationAction = 0
	AP_DropObjects AlterPublicationAction = 1
	AP_SetObjects  AlterPublicationAction = 2
)

func (e AlterPublicationAction) String() string {
	switch e {
	case AP_AddObjects:
		return "AP_AddObjects"
	case AP_DropObjects:
		return "AP_DropObjects"
	case AP_SetObjects:
		return "AP_SetObjects"
	}
	return fmt.Sprintf("AlterPublicationAction(%d)", int32(e))
}

// AlterSubscriptionType is the PostgreSQL enum AlterSubscriptionType.
type AlterSubscriptionType int32

const (
	ALTER_SUBSCRIPTION_OPTIONS          AlterSubscriptionType = 0
	ALTER_SUBSCRIPTION_CONNECTION       AlterSubscriptionType = 1
	ALTER_SUBSCRIPTION_SET_PUBLICATION  AlterSubscriptionType = 2
	ALTER_SUBSCRIPTION_ADD_PUBLICATION  AlterSubscriptionType = 3
	ALTER_SUBSCRIPTION_DROP_PUBLICATION AlterSubscriptionType = 4
	ALTER_SUBSCRIPTION_REFRESH          AlterSubscriptionType = 5
	ALTER_SUBSCRIPTION_ENABLED          AlterSubscriptionType = 6
	ALTER_SUBSCRIPTION_SKIP             AlterSubscriptionType = 7
)

func (e AlterSubscriptionType) String() string {
	switch e {
	case ALTER_SUBSCRIPTION_OPTIONS:
		return "ALTER_SUBSCRIPTION_OPTIONS"
	case ALTER_SUBSCRIPTION_CONNECTION:
		return "ALTER_SUBSCRIPTION_CONNECTION"
	case ALTER_SUBSCRIPTION_SET_PUBLICATION:
		return "ALTER_SUBSCRIPTION_SET_PUBLICATION"
	case ALTER_SUBSCRIPTION_ADD_PUBLICATION:
		return "ALTER_SUBSCRIPTION_ADD_PUBLICATION"
	case ALTER_SUBSCRIPTION_DROP_PUBLICATION:
		return "ALTER_SUBSCRIPTION_DROP_PUBLICATION"
	case ALTER_SUBSCRIPTION_REFRESH:
		return "ALTER_SUBSCRIPTION_REFRESH"
	case ALTER_SUBSCRIPTION_ENABLED:
		return "ALTER_SUBSCRIPTION_ENABLED"
	case ALTER_SUBSCRIPTION_SKIP:
		return "ALTER_SUBSCRIPTION_SKIP"
	}
	return fmt.Sprintf("AlterSubscriptionType(%d)", int32(e))
}

// AlterTSConfigType is the PostgreSQL enum AlterTSConfigType.
type AlterTSConfigType int32

const (
	ALTER_TSCONFIG_ADD_MAPPING             AlterTSConfigType = 0
	ALTER_TSCONFIG_ALTER_MAPPING_FOR_TOKEN AlterTSConfigType = 1
	ALTER_TSCONFIG_REPLACE_DICT            AlterTSConfigType = 2
	ALTER_TSCONFIG_REPLACE_DICT_FOR_TOKEN  AlterTSConfigType = 3
	ALTER_TSCONFIG_DROP_MAPPING            AlterTSConfigType = 4
)

func (e AlterTSConfigType) String() string {
	switch e {
	case ALTER_TSCONFIG_ADD_MAPPING:
		return "ALTER_TSCONFIG_ADD_MAPPING"
	case ALTER_TSCONFIG_ALTER_MAPPING_FOR_TOKEN:
		return "ALTER_TSCONFIG_ALTER_MAPPING_FOR_TOKEN"
	case ALTER_TSCONFIG_REPLACE_DICT:
		return "ALTER_TSCONFIG_REPLACE_DICT"
	case ALTER_TSCONFIG_REPLACE_DICT_FOR_TOKEN:
		return "ALTER_TSCONFIG_REPLACE_DICT_FOR_TOKEN"
	case ALTER_TSCONFIG_DROP_MAPPING:
		return "ALTER_TSCONFIG_DROP_MAPPING"
	}
	return fmt.Sprintf("AlterTSConfigType(%d)", int32(e))
}

// AlterTableType is the PostgreSQL enum AlterTableType.
type AlterTableType int32

const (
	AT_AddColumn                 AlterTableType = 0
	AT_AddColumnToView           AlterTableType = 1
	AT_ColumnDefault             AlterTableType = 2
	AT_CookedColumnDefault       AlterTableType = 3
	AT_DropNotNull               AlterTableType = 4
	AT_SetNotNull                AlterTableType = 5
	AT_SetExpression             AlterTableType = 6
	AT_DropExpression            AlterTableType = 7
	AT_CheckNotNull              AlterTableType = 8
	AT_SetStatistics             AlterTableType = 9
	AT_SetOptions                AlterTableType = 10
	AT_ResetOptions              AlterTableType = 11
	AT_SetStorage                AlterTableType = 12
	AT_SetCompression            AlterTableType = 13
	AT_DropColumn                AlterTableType = 14
	AT_AddIndex                  AlterTableType = 15
	AT_ReAddIndex                AlterTableType = 16
	AT_AddConstraint             AlterTableType = 17
	AT_ReAddConstraint           AlterTableType = 18
	AT_ReAddDomainConstraint     AlterTableType = 19
	AT_AlterConstraint           AlterTableType = 20
	AT_ValidateConstraint        AlterTableType = 21
	AT_AddIndexConstraint        AlterTableType = 22
	AT_DropConstraint            AlterTableType = 23
	AT_ReAddComment              AlterTableType = 24
	AT_AlterColumnType           AlterTableType = 25
	AT_AlterColumnGenericOptions AlterTableType = 26
	AT_ChangeOwner               AlterTableType = 27
	AT_ClusterOn                 AlterTableType = 28
	AT_DropCluster               AlterTableType = 29
	AT_SetLogged                 AlterTableType = 30
	AT_SetUnLogged               AlterTableType = 31
	AT_DropOids                  AlterTableType = 32
	AT_SetAccessMethod           AlterTableType = 33
	AT_SetTableSpace             AlterTableType = 34
	AT_SetRelOptions             AlterTableType = 35
	AT_ResetRelOptions           AlterTableType = 36
	AT_ReplaceRelOptions         AlterTableType = 37
	AT_EnableTrig                AlterTableType = 38
	AT_EnableAlwaysTrig          AlterTableType = 39
	AT_EnableReplicaTrig         AlterTableType = 40
	AT_DisableTrig               AlterTableType = 41
	AT_EnableTrigAll             AlterTableType = 42
	AT_DisableTrigAll            AlterTableType = 43
	AT_EnableTrigUser            AlterTableType = 44
	AT_DisableTrigUser           AlterTableType = 45
	AT_EnableRule                AlterTableType = 46
	AT_EnableAlwaysRule          AlterTableType = 47
	AT_EnableReplicaRule         AlterTableType = 48
	AT_DisableRule               AlterTableType = 49
	AT_AddInherit                AlterTableType = 50
	AT_DropInherit               AlterTableType = 51
	AT_AddOf                     AlterTableType = 52
	AT_DropOf                    AlterTableType = 53
	AT_ReplicaIdentity           AlterTableType = 54
	AT_EnableRowSecurity         AlterTableType = 55
	AT_DisableRowSecurity        AlterTableType = 56
	AT_ForceRowSecurity          AlterTableType = 57
	AT_NoForceRowSecurity        AlterTableType = 58
	AT_GenericOptions            AlterTableType = 59
	AT_AttachPartition           AlterTableType = 60
	AT_DetachPartition           AlterTableType = 61
	AT_DetachPartitionFinalize   AlterTableType = 62
	AT_AddIdentity               AlterTableType = 63
	AT_SetIdentity               AlterTableType = 64
	AT_DropIdentity              AlterTableType = 65
	AT_ReAddStatistics           AlterTableType = 66
)

func (e AlterTableType) String() string {
	switch e {
	case AT_AddColumn:
		return "AT_AddColumn"
	case AT_AddColumnToView:
		return "AT_AddColumnToView"
	case AT_ColumnDefault:
		return "AT_ColumnDefault"
	case AT_CookedColumnDefault:
		return "AT_CookedColumnDefault"
	case AT_DropNotNull:
		return "AT_DropNotNull"
	case AT_SetNotNull:
		return "AT_SetNotNull"
	case AT_SetExpression:
		return "AT_SetExpression"
	case AT_DropExpression:
		return "AT_DropExpression"
	case AT_CheckNotNull:
		return "AT_CheckNotNull"
	case AT_SetStatistics:
		return "AT_SetStatistics"
	case AT_SetOptions:
		return "AT_SetOptions"
	case AT_ResetOptions:
		return "AT_ResetOptions"
	case AT_SetStorage:
		return "AT_SetStorage"
	case AT_SetCompression:
		return "AT_SetCompression"
	case AT_DropColumn:
		return "AT_DropColumn"
	case AT_AddIndex:
		return "AT_AddIndex"
	case AT_ReAddIndex:
		return "AT_ReAddIndex"
	case AT_AddConstraint:
		return "AT_AddConstraint"
	case AT_ReAddConstraint:
		return "AT_ReAddConstraint"
	case AT_ReAddDomainConstraint:
		return "AT_ReAddDomainConstraint"
	case AT_AlterConstraint:
		return "AT_AlterConstraint"
	case AT_ValidateConstraint:
		return "AT_ValidateConstraint"
	case AT_AddIndexConstraint:
		return "AT_AddIndexConstraint"
	case AT_DropConstraint:
		return "AT_DropConstraint"
	case AT_ReAddComment:
		return "AT_ReAddComment"
	case AT_AlterColumnType:
		return "AT_AlterColumnType"
	case AT_AlterColumnGenericOptions:
		return "AT_AlterColumnGenericOptions"
	case AT_ChangeOwner:
		return "AT_ChangeOwner"
	case AT_ClusterOn:
		return "AT_ClusterOn"
	case AT_DropCluster:
		return "AT_DropCluster"
	case AT_SetLogged:
		return "AT_SetLogged"
	case AT_SetUnLogged:
		return "AT_SetUnLogged"
	case AT_DropOids:
		return "AT_DropOids"
	case AT_SetAccessMethod:
		return "AT_SetAccessMethod"
	case AT_SetTableSpace:
		return "AT_SetTableSpace"
	case AT_SetRelOptions:
		return "AT_SetRelOptions"
	case AT_ResetRelOptions:
		return "AT_ResetRelOptions"
	case AT_ReplaceRelOptions:
		return "AT_ReplaceRelOptions"
	case AT_EnableTrig:
		return "AT_EnableTrig"
	case AT_EnableAlwaysTrig:
		return "AT_EnableAlwaysTrig"
	case AT_EnableReplicaTrig:
		return "AT_EnableReplicaTrig"
	case AT_DisableTrig:
		return "AT_DisableTrig"
	case AT_EnableTrigAll:
		return "AT_EnableTrigAll"
	case AT_DisableTrigAll:
		return "AT_DisableTrigAll"
	case AT_EnableTrigUser:
		return "AT_EnableTrigUser"
	case AT_DisableTrigUser:
		return "AT_DisableTrigUser"
	case AT_EnableRule:
		return "AT_EnableRule"
	case AT_EnableAlwaysRule:
		return "AT_EnableAlwaysRule"
	case AT_EnableReplicaRule:
		return "AT_EnableReplicaRule"
	case AT_DisableRule:
		return "AT_DisableRule"
	case AT_AddInherit:
		return "AT_AddInherit"
	case AT_DropInherit:
		return "AT_DropInherit"
	case AT_AddOf:
		return "AT_AddOf"
	case AT_DropOf:
		return "AT_DropOf"
	case AT_ReplicaIdentity:
		return "AT_ReplicaIdentity"
	case AT_EnableRowSecurity:
		return "AT_EnableRowSecurity"
	case AT_DisableRowSecurity:
		return "AT_DisableRowSecurity"
	case AT_ForceRowSecurity:
		return "AT_ForceRowSecurity"
	case AT_NoForceRowSecurity:
		return "AT_NoForceRowSecurity"
	case AT_GenericOptions:
		return "AT_GenericOptions"
	case AT_AttachPartition:
		return "AT_AttachPartition"
	case AT_DetachPartition:
		return "AT_DetachPartition"
	case AT_DetachPartitionFinalize:
		return "AT_DetachPartitionFinalize"
	case AT_AddIdentity:
		return "AT_AddIdentity"
	case AT_SetIdentity:
		return "AT_SetIdentity"
	case AT_DropIdentity:
		return "AT_DropIdentity"
	case AT_ReAddStatistics:
		return "AT_ReAddStatistics"
	}
	return fmt.Sprintf("AlterTableType(%d)", int32(e))
}

// BoolExprType is the PostgreSQL enum BoolExprType.
type BoolExprType int32

const (
	AND_EXPR BoolExprType = 0
	OR_EXPR  BoolExprType = 1
	NOT_EXPR BoolExprType = 2
)

func (e BoolExprType) String() string {
	switch e {
	case AND_EXPR:
		return "AND_EXPR"
	case OR_EXPR:
		return "OR_EXPR"
	case NOT_EXPR:
		return "NOT_EXPR"
	}
	return fmt.Sprintf("BoolExprType(%d)", int32(e))
}

// BoolTestType is the PostgreSQL enum BoolTestType.
type BoolTestType int32

const (
	IS_TRUE        BoolTestType = 0
	IS_NOT_TRUE    BoolTestType = 1
	IS_FALSE       BoolTestType = 2
	IS_NOT_FALSE   BoolTestType = 3
	IS_UNKNOWN     BoolTestType = 4
	IS_NOT_UNKNOWN BoolTestType = 5
)

func (e BoolTestType) String() string {
	switch e {
	case IS_TRUE:
		return "IS_TRUE"
	case IS_NOT_TRUE:
		return "IS_NOT_TRUE"
	case IS_FALSE:
		return "IS_FALSE"
	case IS_NOT_FALSE:
		return "IS_NOT_FALSE"
	case IS_UNKNOWN:
		return "IS_UNKNOWN"
	case IS_NOT_UNKNOWN:
		return "IS_NOT_UNKNOWN"
	}
	return fmt.Sprintf("BoolTestType(%d)", int32(e))
}

// CTEMaterialize is the PostgreSQL enum CTEMaterialize.
type CTEMaterialize int32

const (
	CTEMaterializeDefault CTEMaterialize = 0
	CTEMaterializeAlways  CTEMaterialize = 1
	CTEMaterializeNever   CTEMaterialize = 2
)

func (e CTEMaterialize) String() string {
	switch e {
	case CTEMaterializeDefault:
		return "CTEMaterializeDefault"
	case CTEMaterializeAlways:
		return "CTEMaterializeAlways"
	case CTEMaterializeNever:
		return "CTEMaterializeNever"
	}
	return fmt.Sprintf("CTEMaterialize(%d)", int32(e))
}

// CmdType is the PostgreSQL enum CmdType.
type CmdType int32

const (
	CMD_UNKNOWN CmdType = 0
	CMD_SELECT  CmdType = 1
	CMD_UPDATE  CmdType = 2
	CMD_INSERT  CmdType = 3
	CMD_DELETE  CmdType = 4
	CMD_MERGE   CmdType = 5
	CMD_UTILITY CmdType = 6
	CMD_NOTHING CmdType = 7
)

func (e CmdType) String() string {
	switch e {
	case CMD_UNKNOWN:
		return "CMD_UNKNOWN"
	case CMD_SELECT:
		return "CMD_SELECT"
	case CMD_UPDATE:
		return "CMD_UPDATE"
	case CMD_INSERT:
		return "CMD_INSERT"
	case CMD_DELETE:
		return "CMD_DELETE"
	case CMD_MERGE:
		return "CMD_MERGE"
	case CMD_UTILITY:
		return "CMD_UTILITY"
	case CMD_NOTHING:
		return "CMD_NOTHING"
	}
	return fmt.Sprintf("CmdType(%d)", int32(e))
}

// CoercionContext is the PostgreSQL enum CoercionContext.
type CoercionContext int32

const (
	COERCION_IMPLICIT   CoercionContext = 0
	COERCION_ASSIGNMENT CoercionContext = 1
	COERCION_PLPGSQL    CoercionContext = 2
	COERCION_EXPLICIT   CoercionContext = 3
)

func (e CoercionContext) String() string {
	switch e {
	case COERCION_IMPLICIT:
		return "COERCION_IMPLICIT"
	case COERCION_ASSIGNMENT:
		return "COERCION_ASSIGNMENT"
	case COERCION_PLPGSQL:
		return "COERCION_PLPGSQL"
	case COERCION_EXPLICIT:
		return "COERCION_EXPLICIT"
	}
	return fmt.Sprintf("CoercionContext(%d)", int32(e))
}

// CoercionForm is the PostgreSQL enum CoercionForm.
type CoercionForm int32

const (
	COERCE_EXPLICIT_CALL CoercionForm = 0
	COERCE_EXPLICIT_CAST CoercionForm = 1
	COERCE_IMPLICIT_CAST CoercionForm = 2
	COERCE_SQL_SYNTAX    CoercionForm = 3
)

func (e CoercionForm) String() string {
	switch e {
	case COERCE_EXPLICIT_CALL:
		return "COERCE_EXPLICIT_CALL"
	case COERCE_EXPLICIT_CAST:
		return "COERCE_EXPLICIT_CAST"
	case COERCE_IMPLICIT_CAST:
		return "COERCE_IMPLICIT_CAST"
	case COERCE_SQL_SYNTAX:
		return "COERCE_SQL_SYNTAX"
	}
	return fmt.Sprintf("CoercionForm(%d)", int32(e))
}

// ConstrType is the PostgreSQL enum ConstrType.
type ConstrType int32

const (
	CONSTR_NULL                ConstrType = 0
	CONSTR_NOTNULL             ConstrType = 1
	CONSTR_DEFAULT             ConstrType = 2
	CONSTR_IDENTITY            ConstrType = 3
	CONSTR_GENERATED           ConstrType = 4
	CONSTR_CHECK               ConstrType = 5
	CONSTR_PRIMARY             ConstrType = 6
	CONSTR_UNIQUE              ConstrType = 7
	CONSTR_EXCLUSION           ConstrType = 8
	CONSTR_FOREIGN             ConstrType = 9
	CONSTR_ATTR_DEFERRABLE     ConstrType = 10
	CONSTR_ATTR_NOT_DEFERRABLE ConstrType = 11
	CONSTR_ATTR_DEFERRED       ConstrType = 12
	CONSTR_ATTR_IMMEDIATE      ConstrType = 13
)

func (e ConstrType) String() string {
	switch e {
	case CONSTR_NULL:
		return "CONSTR_NULL"
	case CONSTR_NOTNULL:
		return "CONSTR_NOTNULL"
	case CONSTR_DEFAULT:
		return "CONSTR_DEFAULT"
	case CONSTR_IDENTITY:
		return "CONSTR_IDENTITY"
	case CONSTR_GENERATED:
		return "CONSTR_GENERATED"
	case CONSTR_CHECK:
		return "CONSTR_CHECK"
	case CONSTR_PRIMARY:
		return "CONSTR_PRIMARY"
	case CONSTR_UNIQUE:
		return "CONSTR_UNIQUE"
	case CONSTR_EXCLUSION:
		return "CONSTR_EXCLUSION"
	case CONSTR_FOREIGN:
		return "CONSTR_FOREIGN"
	case CONSTR_ATTR_DEFERRABLE:
		return "CONSTR_ATTR_DEFERRABLE"
	case CONSTR_ATTR_NOT_DEFERRABLE:
		return "CONSTR_ATTR_NOT_DEFERRABLE"
	case CONSTR_ATTR_DEFERRED:
		return "CONSTR_ATTR_DEFERRED"
	case CONSTR_ATTR_IMMEDIATE:
		return "CONSTR_ATTR_IMMEDIATE"
	}
	return fmt.Sprintf("ConstrType(%d)", int32(e))
}

// DefElemAction is the PostgreSQL enum DefElemAction.
type DefElemAction int32

const (
	DEFELEM_UNSPEC DefElemAction = 0
	DEFELEM_SET    DefElemAction = 1
	DEFELEM_ADD    DefElemAction = 2
	DEFELEM_DROP   DefElemAction = 3
)

func (e DefElemAction) String() string {
	switch e {
	case DEFELEM_UNSPEC:
		return "DEFELEM_UNSPEC"
	case DEFELEM_SET:
		return "DEFELEM_SET"
	case DEFELEM_ADD:
		return "DEFELEM_ADD"
	case DEFELEM_DROP:
		return "DEFELEM_DROP"
	}
	return fmt.Sprintf("DefElemAction(%d)", int32(e))
}

// DiscardMode is the PostgreSQL enum DiscardMode.
type DiscardMode int32

const (
	DISCARD_ALL       DiscardMode = 0
	DISCARD_PLANS     DiscardMode = 1
	DISCARD_SEQUENCES DiscardMode = 2
	DISCARD_TEMP      DiscardMode = 3
)

func (e DiscardMode) String() string {
	switch e {
	case DISCARD_ALL:
		return "DISCARD_ALL"
	case DISCARD_PLANS:
		return "DISCARD_PLANS"
	case DISCARD_SEQUENCES:
		return "DISCARD_SEQUENCES"
	case DISCARD_TEMP:
		return "DISCARD_TEMP"
	}
	return fmt.Sprintf("DiscardMode(%d)", int32(e))
}

// DropBehavior is the PostgreSQL enum DropBehavior.
type DropBehavior int32

const (
	DROP_RESTRICT DropBehavior = 0
	DROP_CASCADE  DropBehavior = 1
)

func (e DropBehavior) String() string {
	switch e {
	case DROP_RESTRICT:
		return "DROP_RESTRICT"
	case DROP_CASCADE:
		return "DROP_CASCADE"
	}
	return fmt.Sprintf("DropBehavior(%d)", int32(e))
}

// FetchDirection is the PostgreSQL enum FetchDirection.
type FetchDirection int32

const (
	FETCH_FORWARD  FetchDirection = 0
	FETCH_BACKWARD FetchDirection = 1
	FETCH_ABSOLUTE FetchDirection = 2
	FETCH_RELATIVE FetchDirection = 3
)

func (e FetchDirection) String() string {
	switch e {
	case FETCH_FORWARD:
		return "FETCH_FORWARD"
	case FETCH_BACKWARD:
		return "FETCH_BACKWARD"
	case FETCH_ABSOLUTE:
		return "FETCH_ABSOLUTE"
	case FETCH_RELATIVE:
		return "FETCH_RELATIVE"
	}
	return fmt.Sprintf("FetchDirection(%d)", int32(e))
}

// FunctionParameterMode is the PostgreSQL enum FunctionParameterMode.
type FunctionParameterMode int32

const (
	FUNC_PARAM_IN       FunctionParameterMode = 0
	FUNC_PARAM_OUT      FunctionParameterMode = 1
	FUNC_PARAM_INOUT    FunctionParameterMode = 2
	FUNC_PARAM_VARIADIC FunctionParameterMode = 3
	FUNC_PARAM_TABLE    FunctionParameterMode = 4
	FUNC_PARAM_DEFAULT  FunctionParameterMode = 5
)

func (e FunctionParameterMode) String() string {
	switch e {
	case FUNC_PARAM_IN:
		return "FUNC_PARAM_IN"
	case FUNC_PARAM_OUT:
		return "FUNC_PARAM_OUT"
	case FUNC_PARAM_INOUT:
		return "FUNC_PARAM_INOUT"
	case FUNC_PARAM_VARIADIC:
		return "FUNC_PARAM_VARIADIC"
	case FUNC_PARAM_TABLE:
		return "FUNC_PARAM_TABLE"
	case FUNC_PARAM_DEFAULT:
		return "FUNC_PARAM_DEFAULT"
	}
	return fmt.Sprintf("FunctionParameterMode(%d)", int32(e))
}

// GrantTargetType is the PostgreSQL enum GrantTargetType.
type GrantTargetType int32

const (
	ACL_TARGET_OBJECT        GrantTargetType = 0
	ACL_TARGET_ALL_IN_SCHEMA GrantTargetType = 1
	ACL_TARGET_DEFAULTS      GrantTargetType = 2
)

func (e GrantTargetType) String() string {
	switch e {
	case ACL_TARGET_OBJECT:
		return "ACL_TARGET_OBJECT"
	case ACL_TARGET_ALL_IN_SCHEMA:
		return "ACL_TARGET_ALL_IN_SCHEMA"
	case ACL_TARGET_DEFAULTS:
		return "ACL_TARGET_DEFAULTS"
	}
	return fmt.Sprintf("GrantTargetType(%d)", int32(e))
}

// GroupingSetKind is the PostgreSQL enum GroupingSetKind.
type GroupingSetKind int32

const (
	GROUPING_SET_EMPTY  GroupingSetKind = 0
	GROUPING_SET_SIMPLE GroupingSetKind = 1
	GROUPING_SET_ROLLUP GroupingSetKind = 2
	GROUPING_SET_CUBE   GroupingSetKind = 3
	GROUPING_SET_SETS   GroupingSetKind = 4
)

func (e GroupingSetKind) String() string {
	switch e {
	case GROUPING_SET_EMPTY:
		return "GROUPING_SET_EMPTY"
	case GROUPING_SET_SIMPLE:
		return "GROUPING_SET_SIMPLE"
	case GROUPING_SET_ROLLUP:
		return "GROUPING_SET_ROLLUP"
	case GROUPING_SET_CUBE:
		return "GROUPING_SET_CUBE"
	case GROUPING_SET_SETS:
		return "GROUPING_SET_SETS"
	}
	return fmt.Sprintf("GroupingSetKind(%d)", int32(e))
}

// ImportForeignSchemaType is the PostgreSQL enum ImportForeignSchemaType.
type ImportForeignSchemaType int32

const (
	FDW_IMPORT_SCHEMA_ALL      ImportForeignSchemaType = 0
	FDW_IMPORT_SCHEMA_LIMIT_TO ImportForeignSchemaType = 1
	FDW_IMPORT_SCHEMA_EXCEPT   ImportForeignSchemaType = 2
)

func (e ImportForeignSchemaType) String() string {
	switch e {
	case FDW_IMPORT_SCHEMA_ALL:
		return "FDW_IMPORT_SCHEMA_ALL"
	case FDW_IMPORT_SCHEMA_LIMIT_TO:
		return "FDW_IMPORT_SCHEMA_LIMIT_TO"
	case FDW_IMPORT_SCHEMA_EXCEPT:
		return "FDW_IMPORT_SCHEMA_EXCEPT"
	}
	return fmt.Sprintf("ImportForeignSchemaType(%d)", int32(e))
}

// JoinType is the PostgreSQL enum JoinType.
type JoinType int32

const (
	JOIN_INNER        JoinType = 0
	JOIN_LEFT         JoinType = 1
	JOIN_FULL         JoinType = 2
	JOIN_RIGHT        JoinType = 3
	JOIN_SEMI         JoinType = 4
	JOIN_ANTI         JoinType = 5
	JOIN_RIGHT_ANTI   JoinType = 6
	JOIN_UNIQUE_OUTER JoinType = 7
	JOIN_UNIQUE_INNER JoinType = 8
)

func (e JoinType) String() string {
	switch e {
	case JOIN_INNER:
		return "JOIN_INNER"
	case JOIN_LEFT:
		return "JOIN_LEFT"
	case JOIN_FULL:
		return "JOIN_FULL"
	case JOIN_RIGHT:
		return "JOIN_RIGHT"
	case JOIN_SEMI:
		return "JOIN_SEMI"
	case JOIN_ANTI:
		return "JOIN_ANTI"
	case JOIN_RIGHT_ANTI:
		return "JOIN_RIGHT_ANTI"
	case JOIN_UNIQUE_OUTER:
		return "JOIN_UNIQUE_OUTER"
	case JOIN_UNIQUE_INNER:
		return "JOIN_UNIQUE_INNER"
	}
	return fmt.Sprintf("JoinType(%d)", int32(e))
}

// JsonBehaviorType is the PostgreSQL enum JsonBehaviorType.
type JsonBehaviorType int32

const (
	JSON_BEHAVIOR_NULL         JsonBehaviorType = 0
	JSON_BEHAVIOR_ERROR        JsonBehaviorType = 1
	JSON_BEHAVIOR_EMPTY        JsonBehaviorType = 2
	JSON_BEHAVIOR_TRUE         JsonBehaviorType = 3
	JSON_BEHAVIOR_FALSE        JsonBehaviorType = 4
	JSON_BEHAVIOR_UNKNOWN      JsonBehaviorType = 5
	JSON_BEHAVIOR_EMPTY_ARRAY  JsonBehaviorType = 6
	JSON_BEHAVIOR_EMPTY_OBJECT JsonBehaviorType = 7
	JSON_BEHAVIOR_DEFAULT      JsonBehaviorType = 8
)

func (e JsonBehaviorType) String() string {
	switch e {
	case JSON_BEHAVIOR_NULL:
		return "JSON_BEHAVIOR_NULL"
	case JSON_BEHAVIOR_ERROR:
		return "JSON_BEHAVIOR_ERROR"
	case JSON_BEHAVIOR_EMPTY:
		return "JSON_BEHAVIOR_EMPTY"
	case JSON_BEHAVIOR_TRUE:
		return "JSON_BEHAVIOR_TRUE"
	case JSON_BEHAVIOR_FALSE:
		return "JSON_BEHAVIOR_FALSE"
	case JSON_BEHAVIOR_UNKNOWN:
		return "JSON_BEHAVIOR_UNKNOWN"
	case JSON_BEHAVIOR_EMPTY_ARRAY:
		return "JSON_BEHAVIOR_EMPTY_ARRAY"
	case JSON_BEHAVIOR_EMPTY_OBJECT:
		return "JSON_BEHAVIOR_EMPTY_OBJECT"
	case JSON_BEHAVIOR_DEFAULT:
		return "JSON_BEHAVIOR_DEFAULT"
	}
	return fmt.Sprintf("JsonBehaviorType(%d)", int32(e))
}

// JsonConstructorType is the PostgreSQL enum JsonConstructorType.
type JsonConstructorType int32

const (
	JSCTOR_JSON_OBJECT    JsonConstructorType = 0
	JSCTOR_JSON_ARRAY     JsonConstructorType = 1
	JSCTOR_JSON_OBJECTAGG JsonConstructorType = 2
	JSCTOR_JSON_ARRAYAGG  JsonConstructorType = 3
	JSCTOR_JSON_PARSE     JsonConstructorType = 4
	JSCTOR_JSON_SCALAR    JsonConstructorType = 5
	JSCTOR_JSON_SERIALIZE JsonConstructorType = 6
)

func (e JsonConstructorType) String() string {
	switch e {
	case JSCTOR_JSON_OBJECT:
		return "JSCTOR_JSON_OBJECT"
	case JSCTOR_JSON_ARRAY:
		return "JSCTOR_JSON_ARRAY"
	case JSCTOR_JSON_OBJECTAGG:
		return "JSCTOR_JSON_OBJECTAGG"
	case JSCTOR_JSON_ARRAYAGG:
		return "JSCTOR_JSON_ARRAYAGG"
	case JSCTOR_JSON_PARSE:
		return "JSCTOR_JSON_PARSE"
	case JSCTOR_JSON_SCALAR:
		return "JSCTOR_JSON_SCALAR"
	case JSCTOR_JSON_SERIALIZE:
		return "JSCTOR_JSON_SERIALIZE"
	}
	return fmt.Sprintf("JsonConstructorType(%d)", int32(e))
}

// JsonEncoding is the PostgreSQL enum JsonEncoding.
type JsonEncoding int32

const (
	JS_ENC_DEFAULT JsonEncoding = 0
	JS_ENC_UTF8    JsonEncoding = 1
	JS_ENC_UTF16   JsonEncoding = 2
	JS_ENC_UTF32   JsonEncoding = 3
)

func (e JsonEncoding) String() string {
	switch e {
	case JS_ENC_DEFAULT:
		return "JS_ENC_DEFAULT"
	case JS_ENC_UTF8:
		return "JS_ENC_UTF8"
	case JS_ENC_UTF16:
		return "JS_ENC_UTF16"
	case JS_ENC_UTF32:
		return "JS_ENC_UTF32"
	}
	return fmt.Sprintf("JsonEncoding(%d)", int32(e))
}

// JsonExprOp is the PostgreSQL enum JsonExprOp.
type JsonExprOp int32

const (
	JSON_EXISTS_OP JsonExprOp = 0
	JSON_QUERY_OP  JsonExprOp = 1
	JSON_VALUE_OP  JsonExprOp = 2
	JSON_TABLE_OP  JsonExprOp = 3
)

func (e JsonExprOp) String() string {
	switch e {
	case JSON_EXISTS_OP:
		return "JSON_EXISTS_OP"
	case JSON_QUERY_OP:
		return "JSON_QUERY_OP"
	case JSON_VALUE_OP:
		return "JSON_VALUE_OP"
	case JSON_TABLE_OP:
		return "JSON_TABLE_OP"
	}
	return fmt.Sprintf("JsonExprOp(%d)", int32(e))
}

// JsonFormatType is the PostgreSQL enum JsonFormatType.
type JsonFormatType int32

const (
	JS_FORMAT_DEFAULT JsonFormatType = 0
	JS_FORMAT_JSON    JsonFormatType = 1
	JS_FORMAT_JSONB   JsonFormatType = 2
)

func (e JsonFormatType) String() string {
	switch e {
	case JS_FORMAT_DEFAULT:
		return "JS_FORMAT_DEFAULT"
	case JS_FORMAT_JSON:
		return "JS_FORMAT_JSON"
	case JS_FORMAT_JSONB:
		return "JS_FORMAT_JSONB"
	}
	return fmt.Sprintf("JsonFormatType(%d)", int32(e))
}

// JsonQuotes is the PostgreSQL enum JsonQuotes.
type JsonQuotes int32

const (
	JS_QUOTES_UNSPEC JsonQuotes = 0
	JS_QUOTES_KEEP   JsonQuotes = 1
	JS_QUOTES_OMIT   JsonQuotes = 2
)

func (e JsonQuotes) String() string {
	switch e {
	case JS_QUOTES_UNSPEC:
		return "JS_QUOTES_UNSPEC"
	case JS_QUOTES_KEEP:
		return "JS_QUOTES_KEEP"
	case JS_QUOTES_OMIT:
		return "JS_QUOTES_OMIT"
	}
	return fmt.Sprintf("JsonQuotes(%d)", int32(e))
}

// JsonTableColumnType is the PostgreSQL enum JsonTableColumnType.
type JsonTableColumnType int32

const (
	JTC_FOR_ORDINALITY JsonTableColumnType = 0
	JTC_REGULAR        JsonTableColumnType = 1
	JTC_EXISTS         JsonTableColumnType = 2
	JTC_FORMATTED      JsonTableColumnType = 3
	JTC_NESTED         JsonTableColumnType = 4
)

func (e JsonTableColumnType) String() string {
	switch e {
	case JTC_FOR_ORDINALITY:
		return "JTC_FOR_ORDINALITY"
	case JTC_REGULAR:
		return "JTC_REGULAR"
	case JTC_EXISTS:
		return "JTC_EXISTS"
	case JTC_FORMATTED:
		return "JTC_FORMATTED"
	case JTC_NESTED:
		return "JTC_NESTED"
	}
	return fmt.Sprintf("JsonTableColumnType(%d)", int32(e))
}

// JsonValueType is the PostgreSQL enum JsonValueType.
type JsonValueType int32

const (
	JS_TYPE_ANY    JsonValueType = 0
	JS_TYPE_OBJECT JsonValueType = 1
	JS_TYPE_ARRAY  JsonValueType = 2
	JS_TYPE_SCALAR JsonValueType = 3
)

func (e JsonValueType) String() string {
	switch e {
	case JS_TYPE_ANY:
		return "JS_TYPE_ANY"
	case JS_TYPE_OBJECT:
		return "JS_TYPE_OBJECT"
	case JS_TYPE_ARRAY:
		return "JS_TYPE_ARRAY"
	case JS_TYPE_SCALAR:
		return "JS_TYPE_SCALAR"
	}
	return fmt.Sprintf("JsonValueType(%d)", int32(e))
}

// JsonWrapper is the PostgreSQL enum JsonWrapper.
type JsonWrapper int32

const (
	JSW_UNSPEC        JsonWrapper = 0
	JSW_NONE          JsonWrapper = 1
	JSW_CONDITIONAL   JsonWrapper = 2
	JSW_UNCONDITIONAL JsonWrapper = 3
)

func (e JsonWrapper) String() string {
	switch e {
	case JSW_UNSPEC:
		return "JSW_UNSPEC"
	case JSW_NONE:
		return "JSW_NONE"
	case JSW_CONDITIONAL:
		return "JSW_CONDITIONAL"
	case JSW_UNCONDITIONAL:
		return "JSW_UNCONDITIONAL"
	}
	return fmt.Sprintf("JsonWrapper(%d)", int32(e))
}

// LimitOption is the PostgreSQL enum LimitOption.
type LimitOption int32

const (
	LIMIT_OPTION_DEFAULT   LimitOption = 0
	LIMIT_OPTION_COUNT     LimitOption = 1
	LIMIT_OPTION_WITH_TIES LimitOption = 2
)

func (e LimitOption) String() string {
	switch e {
	case LIMIT_OPTION_DEFAULT:
		return "LIMIT_OPTION_DEFAULT"
	case LIMIT_OPTION_COUNT:
		return "LIMIT_OPTION_COUNT"
	case LIMIT_OPTION_WITH_TIES:
		return "LIMIT_OPTION_WITH_TIES"
	}
	return fmt.Sprintf("LimitOption(%d)", int32(e))
}

// LockClauseStrength is the PostgreSQL enum LockClauseStrength.
type LockClauseStrength int32

const (
	LCS_NONE           LockClauseStrength = 0
	LCS_FORKEYSHARE    LockClauseStrength = 1
	LCS_FORSHARE       LockClauseStrength = 2
	LCS_FORNOKEYUPDATE LockClauseStrength = 3
	LCS_FORUPDATE      LockClauseStrength = 4
)

func (e LockClauseStrength) String() string {
	switch e {
	case LCS_NONE:
		return "LCS_NONE"
	case LCS_FORKEYSHARE:
		return "LCS_FORKEYSHARE"
	case LCS_FORSHARE:
		return "LCS_FORSHARE"
	case LCS_FORNOKEYUPDATE:
		return "LCS_FORNOKEYUPDATE"
	case LCS_FORUPDATE:
		return "LCS_FORUPDATE"
	}
	return fmt.Sprintf("LockClauseStrength(%d)", int32(e))
}

// LockTupleMode is the PostgreSQL enum LockTupleMode.
type LockTupleMode int32

const (
	LockTupleKeyShare       LockTupleMode = 0
	LockTupleShare          LockTupleMode = 1
	LockTupleNoKeyExclusive LockTupleMode = 2
	LockTupleExclusive      LockTupleMode = 3
)

func (e LockTupleMode) String() string {
	switch e {
	case LockTupleKeyShare:
		return "LockTupleKeyShare"
	case LockTupleShare:
		return "LockTupleShare"
	case LockTupleNoKeyExclusive:
		return "LockTupleNoKeyExclusive"
	case LockTupleExclusive:
		return "LockTupleExclusive"
	}
	return fmt.Sprintf("LockTupleMode(%d)", int32(e))
}

// LockWaitPolicy is the PostgreSQL enum LockWaitPolicy.
type LockWaitPolicy int32

const (
	LockWaitBlock LockWaitPolicy = 0
	LockWaitSkip  LockWaitPolicy = 1
	LockWaitError LockWaitPolicy = 2
)

func (e LockWaitPolicy) String() string {
	switch e {
	case LockWaitBlock:
		return "LockWaitBlock"
	case LockWaitSkip:
		return "LockWaitSkip"
	case LockWaitError:
		return "LockWaitError"
	}
	return fmt.Sprintf("LockWaitPolicy(%d)", int32(e))
}

// MergeMatchKind is the PostgreSQL enum MergeMatchKind.
type MergeMatchKind int32

const (
	MERGE_WHEN_MATCHED               MergeMatchKind = 0
	MERGE_WHEN_NOT_MATCHED_BY_SOURCE MergeMatchKind = 1
	MERGE_WHEN_NOT_MATCHED_BY_TARGET MergeMatchKind = 2
)

func (e MergeMatchKind) String() string {
	switch e {
	case MERGE_WHEN_MATCHED:
		return "MERGE_WHEN_MATCHED"
	case MERGE_WHEN_NOT_MATCHED_BY_SOURCE:
		return "MERGE_WHEN_NOT_MATCHED_BY_SOURCE"
	case MERGE_WHEN_NOT_MATCHED_BY_TARGET:
		return "MERGE_WHEN_NOT_MATCHED_BY_TARGET"
	}
	return fmt.Sprintf("MergeMatchKind(%d)", int32(e))
}

// MinMaxOp is the PostgreSQL enum MinMaxOp.
type MinMaxOp int32

const (
	IS_GREATEST MinMaxOp = 0
	IS_LEAST    MinMaxOp = 1
)

func (e MinMaxOp) String() string {
	switch e {
	case IS_GREATEST:
		return "IS_GREATEST"
	case IS_LEAST:
		return "IS_LEAST"
	}
	return fmt.Sprintf("MinMaxOp(%d)", int32(e))
}

// NullTestType is the PostgreSQL enum NullTestType.
type NullTestType int32

const (
	IS_NULL     NullTestType = 0
	IS_NOT_NULL NullTestType = 1
)

func (e NullTestType) String() string {
	switch e {
	case IS_NULL:
		return "IS_NULL"
	case IS_NOT_NULL:
		return "IS_NOT_NULL"
	}
	return fmt.Sprintf("NullTestType(%d)", int32(e))
}

// ObjectType is the PostgreSQL enum ObjectType.
type ObjectType int32

const (
	OBJECT_ACCESS_METHOD         ObjectType = 0
	OBJECT_AGGREGATE             ObjectType = 1
	OBJECT_AMOP                  ObjectType = 2
	OBJECT_AMPROC                ObjectType = 3
	OBJECT_ATTRIBUTE             ObjectType = 4
	OBJECT_CAST                  ObjectType = 5
	OBJECT_COLUMN                ObjectType = 6
	OBJECT_COLLATION             ObjectType = 7
	OBJECT_CONVERSION            ObjectType = 8
	OBJECT_DATABASE              ObjectType = 9
	OBJECT_DEFAULT               ObjectType = 10
	OBJECT_DEFACL                ObjectType = 11
	OBJECT_DOMAIN                ObjectType = 12
	OBJECT_DOMCONSTRAINT         ObjectType = 13
	OBJECT_EVENT_TRIGGER         ObjectType = 14
	OBJECT_EXTENSION             ObjectType = 15
	OBJECT_FDW                   ObjectType = 16
	OBJECT_FOREIGN_SERVER        ObjectType = 17
	OBJECT_FOREIGN_TABLE         ObjectType = 18
	OBJECT_FUNCTION              ObjectType = 19
	OBJECT_INDEX                 ObjectType = 20
	OBJECT_LANGUAGE              ObjectType = 21
	OBJECT_LARGEOBJECT           ObjectType = 22
	OBJECT_MATVIEW               ObjectType = 23
	OBJECT_OPCLASS               ObjectType = 24
	OBJECT_OPERATOR              ObjectType = 25
	OBJECT_OPFAMILY              ObjectType = 26
	OBJECT_PARAMETER_ACL         ObjectType = 27
	OBJECT_POLICY                ObjectType = 28
	OBJECT_PROCEDURE             ObjectType = 29
	OBJECT_PUBLICATION           ObjectType = 30
	OBJECT_PUBLICATION_NAMESPACE ObjectType = 31
	OBJECT_PUBLICATION_REL       ObjectType = 32
	OBJECT_ROLE                  ObjectType = 33
	OBJECT_ROUTINE               ObjectType = 34
	OBJECT_RULE                  ObjectType = 35
	OBJECT_SCHEMA                ObjectType = 36
	OBJECT_SEQUENCE              ObjectType = 37
	OBJECT_SUBSCRIPTION          ObjectType = 38
	OBJECT_STATISTIC_EXT         ObjectType = 39
	OBJECT_TABCONSTRAINT         ObjectType = 40
	OBJECT_TABLE                 ObjectType = 41
	OBJECT_TABLESPACE            ObjectType = 42
	OBJECT_TRANSFORM             ObjectType = 43
	OBJECT_TRIGGER               ObjectType = 44
	OBJECT_TSCONFIGURATION       ObjectType = 45
	OBJECT_TSDICTIONARY          ObjectType = 46
	OBJECT_TSPARSER              ObjectType = 47
	OBJECT_TSTEMPLATE            ObjectType = 48
	OBJECT_TYPE                  ObjectType = 49
	OBJECT_USER_MAPPING          ObjectType = 50
	OBJECT_VIEW                  ObjectType = 51
)

func (e ObjectType) String() string {
	switch e {
	case OBJECT_ACCESS_METHOD:
		return "OBJECT_ACCESS_METHOD"
	case OBJECT_AGGREGATE:
		return "OBJECT_AGGREGATE"
	case OBJECT_AMOP:
		return "OBJECT_AMOP"
	case OBJECT_AMPROC:
		return "OBJECT_AMPROC"
	case OBJECT_ATTRIBUTE:
		return "OBJECT_ATTRIBUTE"
	case OBJECT_CAST:
		return "OBJECT_CAST"
	case OBJECT_COLUMN:
		return "OBJECT_COLUMN"
	case OBJECT_COLLATION:
		return "OBJECT_COLLATION"
	case OBJECT_CONVERSION:
		return "OBJECT_CONVERSION"
	case OBJECT_DATABASE:
		return "OBJECT_DATABASE"
	case OBJECT_DEFAULT:
		return "OBJECT_DEFAULT"
	case OBJECT_DEFACL:
		return "OBJECT_DEFACL"
	case OBJECT_DOMAIN:
		return "OBJECT_DOMAIN"
	case OBJECT_DOMCONSTRAINT:
		return "OBJECT_DOMCONSTRAINT"
	case OBJECT_EVENT_TRIGGER:
		return "OBJECT_EVENT_TRIGGER"
	case OBJECT_EXTENSION:
		return "OBJECT_EXTENSION"
	case OBJECT_FDW:
		return "OBJECT_FDW"
	case OBJECT_FOREIGN_SERVER:
		return "OBJECT_FOREIGN_SERVER"
	case OBJECT_FOREIGN_TABLE:
		return "OBJECT_FOREIGN_TABLE"
	case OBJECT_FUNCTION:
		return "OBJECT_FUNCTION"
	case OBJECT_INDEX:
		return "OBJECT_INDEX"
	case OBJECT_LANGUAGE:
		return "OBJECT_LANGUAGE"
	case OBJECT_LARGEOBJECT:
		return "OBJECT_LARGEOBJECT"
	case OBJECT_MATVIEW:
		return "OBJECT_MATVIEW"
	case OBJECT_OPCLASS:
		return "OBJECT_OPCLASS"
	case OBJECT_OPERATOR:
		return "OBJECT_OPERATOR"
	case OBJECT_OPFAMILY:
		return "OBJECT_OPFAMILY"
	case OBJECT_PARAMETER_ACL:
		return "OBJECT_PARAMETER_ACL"
	case OBJECT_POLICY:
		return "OBJECT_POLICY"
	case OBJECT_PROCEDURE:
		return "OBJECT_PROCEDURE"
	case OBJECT_PUBLICATION:
		return "OBJECT_PUBLICATION"
	case OBJECT_PUBLICATION_NAMESPACE:
		return "OBJECT_PUBLICATION_NAMESPACE"
	case OBJECT_PUBLICATION_REL:
		return "OBJECT_PUBLICATION_REL"
	case OBJECT_ROLE:
		return "OBJECT_ROLE"
	case OBJECT_ROUTINE:
		return "OBJECT_ROUTINE"
	case OBJECT_RULE:
		return "OBJECT_RULE"
	case OBJECT_SCHEMA:
		return "OBJECT_SCHEMA"
	case OBJECT_SEQUENCE:
		return "OBJECT_SEQUENCE"
	case OBJECT_SUBSCRIPTION:
		return "OBJECT_SUBSCRIPTION"
	case OBJECT_STATISTIC_EXT:
		return "OBJECT_STATISTIC_EXT"
	case OBJECT_TABCONSTRAINT:
		return "OBJECT_TABCONSTRAINT"
	case OBJECT_TABLE:
		return "OBJECT_TABLE"
	case OBJECT_TABLESPACE:
		return "OBJECT_TABLESPACE"
	case OBJECT_TRANSFORM:
		return "OBJECT_TRANSFORM"
	case OBJECT_TRIGGER:
		return "OBJECT_TRIGGER"
	case OBJECT_TSCONFIGURATION:
		return "OBJECT_TSCONFIGURATION"
	case OBJECT_TSDICTIONARY:
		return "OBJECT_TSDICTIONARY"
	case OBJECT_TSPARSER:
		return "OBJECT_TSPARSER"
	case OBJECT_TSTEMPLATE:
		return "OBJECT_TSTEMPLATE"
	case OBJECT_TYPE:
		return "OBJECT_TYPE"
	case OBJECT_USER_MAPPING:
		return "OBJECT_USER_MAPPING"
	case OBJECT_VIEW:
		return "OBJECT_VIEW"
	}
	return fmt.Sprintf("ObjectType(%d)", int32(e))
}

// OnCommitAction is the PostgreSQL enum OnCommitAction.
type OnCommitAction int32

const (
	ONCOMMIT_NOOP          OnCommitAction = 0
	ONCOMMIT_PRESERVE_ROWS OnCommitAction = 1
	ONCOMMIT_DELETE_ROWS   OnCommitAction = 2
	ONCOMMIT_DROP          OnCommitAction = 3
)

func (e OnCommitAction) String() string {
	switch e {
	case ONCOMMIT_NOOP:
		return "ONCOMMIT_NOOP"
	case ONCOMMIT_PRESERVE_ROWS:
		return "ONCOMMIT_PRESERVE_ROWS"
	case ONCOMMIT_DELETE_ROWS:
		return "ONCOMMIT_DELETE_ROWS"
	case ONCOMMIT_DROP:
		return "ONCOMMIT_DROP"
	}
	return fmt.Sprintf("OnCommitAction(%d)", int32(e))
}

// OnConflictAction is the PostgreSQL enum OnConflictAction.
type OnConflictAction int32

const (
	ONCONFLICT_NONE    OnConflictAction = 0
	ONCONFLICT_NOTHING OnConflictAction = 1
	ONCONFLICT_UPDATE  OnConflictAction = 2
)

func (e OnConflictAction) String() string {
	switch e {
	case ONCONFLICT_NONE:
		return "ONCONFLICT_NONE"
	case ONCONFLICT_NOTHING:
		return "ONCONFLICT_NOTHING"
	case ONCONFLICT_UPDATE:
		return "ONCONFLICT_UPDATE"
	}
	return fmt.Sprintf("OnConflictAction(%d)", int32(e))
}

// OverridingKind is the PostgreSQL enum OverridingKind.
type OverridingKind int32

const (
	OVERRIDING_NOT_SET      OverridingKind = 0
	OVERRIDING_USER_VALUE   OverridingKind = 1
	OVERRIDING_SYSTEM_VALUE OverridingKind = 2
)

func (e OverridingKind) String() string {
	switch e {
	case OVERRIDING_NOT_SET:
		return "OVERRIDING_NOT_SET"
	case OVERRIDING_USER_VALUE:
		return "OVERRIDING_USER_VALUE"
	case OVERRIDING_SYSTEM_VALUE:
		return "OVERRIDING_SYSTEM_VALUE"
	}
	return fmt.Sprintf("OverridingKind(%d)", int32(e))
}

// ParamKind is the PostgreSQL enum ParamKind.
type ParamKind int32

const (
	PARAM_EXTERN    ParamKind = 0
	PARAM_EXEC      ParamKind = 1
	PARAM_SUBLINK   ParamKind = 2
	PARAM_MULTIEXPR ParamKind = 3
)

func (e ParamKind) String() string {
	switch e {
	case PARAM_EXTERN:
		return "PARAM_EXTERN"
	case PARAM_EXEC:
		return "PARAM_EXEC"
	case PARAM_SUBLINK:
		return "PARAM_SUBLINK"
	case PARAM_MULTIEXPR:
		return "PARAM_MULTIEXPR"
	}
	return fmt.Sprintf("ParamKind(%d)", int32(e))
}

// PartitionRangeDatumKind is the PostgreSQL enum PartitionRangeDatumKind.
type PartitionRangeDatumKind int32

const (
	PARTITION_RANGE_DATUM_MINVALUE PartitionRangeDatumKind = 0
	PARTITION_RANGE_DATUM_VALUE    PartitionRangeDatumKind = 1
	PARTITION_RANGE_DATUM_MAXVALUE PartitionRangeDatumKind = 2
)

func (e PartitionRangeDatumKind) String() string {
	switch e {
	case PARTITION_RANGE_DATUM_MINVALUE:
		return "PARTITION_RANGE_DATUM_MINVALUE"
	case PARTITION_RANGE_DATUM_VALUE:
		return "PARTITION_RANGE_DATUM_VALUE"
	case PARTITION_RANGE_DATUM_MAXVALUE:
		return "PARTITION_RANGE_DATUM_MAXVALUE"
	}
	return fmt.Sprintf("PartitionRangeDatumKind(%d)", int32(e))
}

// PartitionStrategy is the PostgreSQL enum PartitionStrategy.
type PartitionStrategy int32

const (
	PARTITION_STRATEGY_LIST  PartitionStrategy = 0
	PARTITION_STRATEGY_RANGE PartitionStrategy = 1
	PARTITION_STRATEGY_HASH  PartitionStrategy = 2
)

func (e PartitionStrategy) String() string {
	switch e {
	case PARTITION_STRATEGY_LIST:
		return "PARTITION_STRATEGY_LIST"
	case PARTITION_STRATEGY_RANGE:
		return "PARTITION_STRATEGY_RANGE"
	case PARTITION_STRATEGY_HASH:
		return "PARTITION_STRATEGY_HASH"
	}
	return fmt.Sprintf("PartitionStrategy(%d)", int32(e))
}

// PublicationObjSpecType is the PostgreSQL enum PublicationObjSpecType.
type PublicationObjSpecType int32

const (
	PUBLICATIONOBJ_TABLE                PublicationObjSpecType = 0
	PUBLICATIONOBJ_TABLES_IN_SCHEMA     PublicationObjSpecType = 1
	PUBLICATIONOBJ_TABLES_IN_CUR_SCHEMA PublicationObjSpecType = 2
	PUBLICATIONOBJ_CONTINUATION         PublicationObjSpecType = 3
)

func (e PublicationObjSpecType) String() string {
	switch e {
	case PUBLICATIONOBJ_TABLE:
		return "PUBLICATIONOBJ_TABLE"
	case PUBLICATIONOBJ_TABLES_IN_SCHEMA:
		return "PUBLICATIONOBJ_TABLES_IN_SCHEMA"
	case PUBLICATIONOBJ_TABLES_IN_CUR_SCHEMA:
		return "PUBLICATIONOBJ_TABLES_IN_CUR_SCHEMA"
	case PUBLICATIONOBJ_CONTINUATION:
		return "PUBLICATIONOBJ_CONTINUATION"
	}
	return fmt.Sprintf("PublicationObjSpecType(%d)", int32(e))
}

// QuerySource is the PostgreSQL enum QuerySource.
type QuerySource int32

const (
	QSRC_ORIGINAL          QuerySource = 0
	QSRC_PARSER            QuerySource = 1
	QSRC_INSTEAD_RULE      QuerySource = 2
	QSRC_QUAL_INSTEAD_RULE QuerySource = 3
	QSRC_NON_INSTEAD_RULE  QuerySource = 4
)

func (e QuerySource) String() string {
	switch e {
	case QSRC_ORIGINAL:
		return "QSRC_ORIGINAL"
	case QSRC_PARSER:
		return "QSRC_PARSER"
	case QSRC_INSTEAD_RULE:
		return "QSRC_INSTEAD_RULE"
	case QSRC_QUAL_INSTEAD_RULE:
		return "QSRC_QUAL_INSTEAD_RULE"
	case QSRC_NON_INSTEAD_RULE:
		return "QSRC_NON_INSTEAD_RULE"
	}
	return fmt.Sprintf("QuerySource(%d)", int32(e))
}

// RTEKind is the PostgreSQL enum RTEKind.
type RTEKind int32

const (
	RTE_RELATION        RTEKind = 0
	RTE_SUBQUERY        RTEKind = 1
	RTE_JOIN            RTEKind = 2
	RTE_FUNCTION        RTEKind = 3
	RTE_TABLEFUNC       RTEKind = 4
	RTE_VALUES          RTEKind = 5
	RTE_CTE             RTEKind = 6
	RTE_NAMEDTUPLESTORE RTEKind = 7
	RTE_RESULT          RTEKind = 8
)

func (e RTEKind) String() string {
	switch e {
	case RTE_RELATION:
		return "RTE_RELATION"
	case RTE_SUBQUERY:
		return "RTE_SUBQUERY"
	case RTE_JOIN:
		return "RTE_JOIN"
	case RTE_FUNCTION:
		return "RTE_FUNCTION"
	case RTE_TABLEFUNC:
		return "RTE_TABLEFUNC"
	case RTE_VALUES:
		return "RTE_VALUES"
	case RTE_CTE:
		return "RTE_CTE"
	case RTE_NAMEDTUPLESTORE:
		return "RTE_NAMEDTUPLESTORE"
	case RTE_RESULT:
		return "RTE_RESULT"
	}
	return fmt.Sprintf("RTEKind(%d)", int32(e))
}

// ReindexObjectType is the PostgreSQL enum ReindexObjectType.
type ReindexObjectType int32

const (
	REINDEX_OBJECT_INDEX    ReindexObjectType = 0
	REINDEX_OBJECT_TABLE    ReindexObjectType = 1
	REINDEX_OBJECT_SCHEMA   ReindexObjectType = 2
	REINDEX_OBJECT_SYSTEM   ReindexObjectType = 3
	REINDEX_OBJECT_DATABASE ReindexObjectType = 4
)

func (e ReindexObjectType) String() string {
	switch e {
	case REINDEX_OBJECT_INDEX:
		return "REINDEX_OBJECT_INDEX"
	case REINDEX_OBJECT_TABLE:
		return "REINDEX_OBJECT_TABLE"
	case REINDEX_OBJECT_SCHEMA:
		return "REINDEX_OBJECT_SCHEMA"
	case REINDEX_OBJECT_SYSTEM:
		return "REINDEX_OBJECT_SYSTEM"
	case REINDEX_OBJECT_DATABASE:
		return "REINDEX_OBJECT_DATABASE"
	}
	return fmt.Sprintf("ReindexObjectType(%d)", int32(e))
}

// RoleSpecType is the PostgreSQL enum RoleSpecType.
type RoleSpecType int32

const (
	ROLESPEC_CSTRING      RoleSpecType = 0
	ROLESPEC_CURRENT_ROLE RoleSpecType = 1
	ROLESPEC_CURRENT_USER RoleSpecType = 2
	ROLESPEC_SESSION_USER RoleSpecType = 3
	ROLESPEC_PUBLIC       RoleSpecType = 4
)

func (e RoleSpecType) String() string {
	switch e {
	case ROLESPEC_CSTRING:
		return "ROLESPEC_CSTRING"
	case ROLESPEC_CURRENT_ROLE:
		return "ROLESPEC_CURRENT_ROLE"
	case ROLESPEC_CURRENT_USER:
		return "ROLESPEC_CURRENT_USER"
	case ROLESPEC_SESSION_USER:
		return "ROLESPEC_SESSION_USER"
	case ROLESPEC_PUBLIC:
		return "ROLESPEC_PUBLIC"
	}
	return fmt.Sprintf("RoleSpecType(%d)", int32(e))
}

// RoleStmtType is the PostgreSQL enum RoleStmtType.
type RoleStmtType int32

const (
	ROLESTMT_ROLE  RoleStmtType = 0
	ROLESTMT_USER  RoleStmtType = 1
	ROLESTMT_GROUP RoleStmtType = 2
)

func (e RoleStmtType) String() string {
	switch e {
	case ROLESTMT_ROLE:
		return "ROLESTMT_ROLE"
	case ROLESTMT_USER:
		return "ROLESTMT_USER"
	case ROLESTMT_GROUP:
		return "ROLESTMT_GROUP"
	}
	return fmt.Sprintf("RoleStmtType(%d)", int32(e))
}

// RowCompareType is the PostgreSQL enum RowCompareType.
type RowCompareType int32

const (
	ROWCOMPARE_LT RowCompareType = 0
	ROWCOMPARE_LE RowCompareType = 1
	ROWCOMPARE_EQ RowCompareType = 2
	ROWCOMPARE_GE RowCompareType = 3
	ROWCOMPARE_GT RowCompareType = 4
	ROWCOMPARE_NE RowCompareType = 5
)

func (e RowCompareType) String() string {
	switch e {
	case ROWCOMPARE_LT:
		return "ROWCOMPARE_LT"
	case ROWCOMPARE_LE:
		return "ROWCOMPARE_LE"
	case ROWCOMPARE_EQ:
		return "ROWCOMPARE_EQ"
	case ROWCOMPARE_GE:
		return "ROWCOMPARE_GE"
	case ROWCOMPARE_GT:
		return "ROWCOMPARE_GT"
	case ROWCOMPARE_NE:
		return "ROWCOMPARE_NE"
	}
	return fmt.Sprintf("RowCompareType(%d)", int32(e))
}

// SQLValueFunctionOp is the PostgreSQL enum SQLValueFunctionOp.
type SQLValueFunctionOp int32

const (
	SVFOP_CURRENT_DATE        SQLValueFunctionOp = 0
	SVFOP_CURRENT_TIME        SQLValueFunctionOp = 1
	SVFOP_CURRENT_TIME_N      SQLValueFunctionOp = 2
	SVFOP_CURRENT_TIMESTAMP   SQLValueFunctionOp = 3
	SVFOP_CURRENT_TIMESTAMP_N SQLValueFunctionOp = 4
	SVFOP_LOCALTIME           SQLValueFunctionOp = 5
	SVFOP_LOCALTIME_N         SQLValueFunctionOp = 6
	SVFOP_LOCALTIMESTAMP      SQLValueFunctionOp = 7
	SVFOP_LOCALTIMESTAMP_N    SQLValueFunctionOp = 8
	SVFOP_CURRENT_ROLE        SQLValueFunctionOp = 9
	SVFOP_CURRENT_USER        SQLValueFunctionOp = 10
	SVFOP_USER                SQLValueFunctionOp = 11
	SVFOP_SESSION_USER        SQLValueFunctionOp = 12
	SVFOP_CURRENT_CATALOG     SQLValueFunctionOp = 13
	SVFOP_CURRENT_SCHEMA      SQLValueFunctionOp = 14
)

func (e SQLValueFunctionOp) String() string {
	switch e {
	case SVFOP_CURRENT_DATE:
		return "SVFOP_CURRENT_DATE"
	case SVFOP_CURRENT_TIME:
		return "SVFOP_CURRENT_TIME"
	case SVFOP_CURRENT_TIME_N:
		return "SVFOP_CURRENT_TIME_N"
	case SVFOP_CURRENT_TIMESTAMP:
		return "SVFOP_CURRENT_TIMESTAMP"
	case SVFOP_CURRENT_TIMESTAMP_N:
		return "SVFOP_CURRENT_TIMESTAMP_N"
	case SVFOP_LOCALTIME:
		return "SVFOP_LOCALTIME"
	case SVFOP_LOCALTIME_N:
		return "SVFOP_LOCALTIME_N"
	case SVFOP_LOCALTIMESTAMP:
		return "SVFOP_LOCALTIMESTAMP"
	case SVFOP_LOCALTIMESTAMP_N:
		return "SVFOP_LOCALTIMESTAMP_N"
	case SVFOP_CURRENT_ROLE:
		return "SVFOP_CURRENT_ROLE"
	case SVFOP_CURRENT_USER:
		return "SVFOP_CURRENT_USER"
	case SVFOP_USER:
		return "SVFOP_USER"
	case SVFOP_SESSION_USER:
		return "SVFOP_SESSION_USER"
	case SVFOP_CURRENT_CATALOG:
		return "SVFOP_CURRENT_CATALOG"
	case SVFOP_CURRENT_SCHEMA:
		return "SVFOP_CURRENT_SCHEMA"
	}
	return fmt.Sprintf("SQLValueFunctionOp(%d)", int32(e))
}

// SetOpCmd is the PostgreSQL enum SetOpCmd.
type SetOpCmd int32

const (
	SETOPCMD_INTERSECT     SetOpCmd = 0
	SETOPCMD_INTERSECT_ALL SetOpCmd = 1
	SETOPCMD_EXCEPT        SetOpCmd = 2
	SETOPCMD_EXCEPT_ALL    SetOpCmd = 3
)

func (e SetOpCmd) String() string {
	switch e {
	case SETOPCMD_INTERSECT:
		return "SETOPCMD_INTERSECT"
	case SETOPCMD_INTERSECT_ALL:
		return "SETOPCMD_INTERSECT_ALL"
	case SETOPCMD_EXCEPT:
		return "SETOPCMD_EXCEPT"
	case SETOPCMD_EXCEPT_ALL:
		return "SETOPCMD_EXCEPT_ALL"
	}
	return fmt.Sprintf("SetOpCmd(%d)", int32(e))
}

// SetOpStrategy is the PostgreSQL enum SetOpStrategy.
type SetOpStrategy int32

const (
	SETOP_SORTED SetOpStrategy = 0
	SETOP_HASHED SetOpStrategy = 1
)

func (e SetOpStrategy) String() string {
	switch e {
	case SETOP_SORTED:
		return "SETOP_SORTED"
	case SETOP_HASHED:
		return "SETOP_HASHED"
	}
	return fmt.Sprintf("SetOpStrategy(%d)", int32(e))
}

// SetOperation is the PostgreSQL enum SetOperation.
type SetOperation int32

const (
	SETOP_NONE      SetOperation = 0
	SETOP_UNION     SetOperation = 1
	SETOP_INTERSECT SetOperation = 2
	SETOP_EXCEPT    SetOperation = 3
)

func (e SetOperation) String() string {
	switch e {
	case SETOP_NONE:
		return "SETOP_NONE"
	case SETOP_UNION:
		return "SETOP_UNION"
	case SETOP_INTERSECT:
		return "SETOP_INTERSECT"
	case SETOP_EXCEPT:
		return "SETOP_EXCEPT"
	}
	return fmt.Sprintf("SetOperation(%d)", int32(e))
}

// SetQuantifier is the PostgreSQL enum SetQuantifier.
type SetQuantifier int32

const (
	SET_QUANTIFIER_DEFAULT  SetQuantifier = 0
	SET_QUANTIFIER_ALL      SetQuantifier = 1
	SET_QUANTIFIER_DISTINCT SetQuantifier = 2
)

func (e SetQuantifier) String() string {
	switch e {
	case SET_QUANTIFIER_DEFAULT:
		return "SET_QUANTIFIER_DEFAULT"
	case SET_QUANTIFIER_ALL:
		return "SET_QUANTIFIER_ALL"
	case SET_QUANTIFIER_DISTINCT:
		return "SET_QUANTIFIER_DISTINCT"
	}
	return fmt.Sprintf("SetQuantifier(%d)", int32(e))
}

// SortByDir is the PostgreSQL enum SortByDir.
type SortByDir int32

const (
	SORTBY_DEFAULT SortByDir = 0
	SORTBY_ASC     SortByDir = 1
	SORTBY_DESC    SortByDir = 2
	SORTBY_USING   SortByDir = 3
)

func (e SortByDir) String() string {
	switch e {
	case SORTBY_DEFAULT:
		return "SORTBY_DEFAULT"
	case SORTBY_ASC:
		return "SORTBY_ASC"
	case SORTBY_DESC:
		return "SORTBY_DESC"
	case SORTBY_USING:
		return "SORTBY_USING"
	}
	return fmt.Sprintf("SortByDir(%d)", int32(e))
}

// SortByNulls is the PostgreSQL enum SortByNulls.
type SortByNulls int32

const (
	SORTBY_NULLS_DEFAULT SortByNulls = 0
	SORTBY_NULLS_FIRST   SortByNulls = 1
	SORTBY_NULLS_LAST    SortByNulls = 2
)

func (e SortByNulls) String() string {
	switch e {
	case SORTBY_NULLS_DEFAULT:
		return "SORTBY_NULLS_DEFAULT"
	case SORTBY_NULLS_FIRST:
		return "SORTBY_NULLS_FIRST"
	case SORTBY_NULLS_LAST:
		return "SORTBY_NULLS_LAST"
	}
	return fmt.Sprintf("SortByNulls(%d)", int32(e))
}

// SubLinkType is the PostgreSQL enum SubLinkType.
type SubLinkType int32

const (
	EXISTS_SUBLINK     SubLinkType = 0
	ALL_SUBLINK        SubLinkType = 1
	ANY_SUBLINK        SubLinkType = 2
	ROWCOMPARE_SUBLINK SubLinkType = 3
	EXPR_SUBLINK       SubLinkType = 4
	MULTIEXPR_SUBLINK  SubLinkType = 5
	ARRAY_SUBLINK      SubLinkType = 6
	CTE_SUBLINK        SubLinkType = 7
)

func (e SubLinkType) String() string {
	switch e {
	case EXISTS_SUBLINK:
		return "EXISTS_SUBLINK"
	case ALL_SUBLINK:
		return "ALL_SUBLINK"
	case ANY_SUBLINK:
		return "ANY_SUBLINK"
	case ROWCOMPARE_SUBLINK:
		return "ROWCOMPARE_SUBLINK"
	case EXPR_SUBLINK:
		return "EXPR_SUBLINK"
	case MULTIEXPR_SUBLINK:
		return "MULTIEXPR_SUBLINK"
	case ARRAY_SUBLINK:
		return "ARRAY_SUBLINK"
	case CTE_SUBLINK:
		return "CTE_SUBLINK"
	}
	return fmt.Sprintf("SubLinkType(%d)", int32(e))
}

// TableFuncType is the PostgreSQL enum TableFuncType.
type TableFuncType int32

const (
	TFT_XMLTABLE   TableFuncType = 0
	TFT_JSON_TABLE TableFuncType = 1
)

func (e TableFuncType) String() string {
	switch e {
	case TFT_XMLTABLE:
		return "TFT_XMLTABLE"
	case TFT_JSON_TABLE:
		return "TFT_JSON_TABLE"
	}
	return fmt.Sprintf("TableFuncType(%d)", int32(e))
}

// TableLikeOption is the PostgreSQL enum TableLikeOption.
type TableLikeOption int32

const (
	CREATE_TABLE_LIKE_COMMENTS    TableLikeOption = 0
	CREATE_TABLE_LIKE_COMPRESSION TableLikeOption = 1
	CREATE_TABLE_LIKE_CONSTRAINTS TableLikeOption = 2
	CREATE_TABLE_LIKE_DEFAULTS    TableLikeOption = 3
	CREATE_TABLE_LIKE_GENERATED   TableLikeOption = 4
	CREATE_TABLE_LIKE_IDENTITY    TableLikeOption = 5
	CREATE_TABLE_LIKE_INDEXES     TableLikeOption = 6
	CREATE_TABLE_LIKE_STATISTICS  TableLikeOption = 7
	CREATE_TABLE_LIKE_STORAGE     TableLikeOption = 8
	CREATE_TABLE_LIKE_ALL         TableLikeOption = 9
)

func (e TableLikeOption) String() string {
	switch e {
	case CREATE_TABLE_LIKE_COMMENTS:
		return "CREATE_TABLE_LIKE_COMMENTS"
	case CREATE_TABLE_LIKE_COMPRESSION:
		return "CREATE_TABLE_LIKE_COMPRESSION"
	case CREATE_TABLE_LIKE_CONSTRAINTS:
		return "CREATE_TABLE_LIKE_CONSTRAINTS"
	case CREATE_TABLE_LIKE_DEFAULTS:
		return "CREATE_TABLE_LIKE_DEFAULTS"
	case CREATE_TABLE_LIKE_GENERATED:
		return "CREATE_TABLE_LIKE_GENERATED"
	case CREATE_TABLE_LIKE_IDENTITY:
		return "CREATE_TABLE_LIKE_IDENTITY"
	case CREATE_TABLE_LIKE_INDEXES:
		return "CREATE_TABLE_LIKE_INDEXES"
	case CREATE_TABLE_LIKE_STATISTICS:
		return "CREATE_TABLE_LIKE_STATISTICS"
	case CREATE_TABLE_LIKE_STORAGE:
		return "CREATE_TABLE_LIKE_STORAGE"
	case CREATE_TABLE_LIKE_ALL:
		return "CREATE_TABLE_LIKE_ALL"
	}
	return fmt.Sprintf("TableLikeOption(%d)", int32(e))
}

// TransactionStmtKind is the PostgreSQL enum TransactionStmtKind.
type TransactionStmtKind int32

const (
	TRANS_STMT_BEGIN             TransactionStmtKind = 0
	TRANS_STMT_START             TransactionStmtKind = 1
	TRANS_STMT_COMMIT            TransactionStmtKind = 2
	TRANS_STMT_ROLLBACK          TransactionStmtKind = 3
	TRANS_STMT_SAVEPOINT         TransactionStmtKind = 4
	TRANS_STMT_RELEASE           TransactionStmtKind = 5
	TRANS_STMT_ROLLBACK_TO       TransactionStmtKind = 6
	TRANS_STMT_PREPARE           TransactionStmtKind = 7
	TRANS_STMT_COMMIT_PREPARED   TransactionStmtKind = 8
	TRANS_STMT_ROLLBACK_PREPARED TransactionStmtKind = 9
)

func (e TransactionStmtKind) String() string {
	switch e {
	case TRANS_STMT_BEGIN:
		return "TRANS_STMT_BEGIN"
	case TRANS_STMT_START:
		return "TRANS_STMT_START"
	case TRANS_STMT_COMMIT:
		return "TRANS_STMT_COMMIT"
	case TRANS_STMT_ROLLBACK:
		return "TRANS_STMT_ROLLBACK"
	case TRANS_STMT_SAVEPOINT:
		return "TRANS_STMT_SAVEPOINT"
	case TRANS_STMT_RELEASE:
		return "TRANS_STMT_RELEASE"
	case TRANS_STMT_ROLLBACK_TO:
		return "TRANS_STMT_ROLLBACK_TO"
	case TRANS_STMT_PREPARE:
		return "TRANS_STMT_PREPARE"
	case TRANS_STMT_COMMIT_PREPARED:
		return "TRANS_STMT_COMMIT_PREPARED"
	case TRANS_STMT_ROLLBACK_PREPARED:
		return "TRANS_STMT_ROLLBACK_PREPARED"
	}
	return fmt.Sprintf("TransactionStmtKind(%d)", int32(e))
}

// VariableSetKind is the PostgreSQL enum VariableSetKind.
type VariableSetKind int32

const (
	VAR_SET_VALUE   VariableSetKind = 0
	VAR_SET_DEFAULT VariableSetKind = 1
	VAR_SET_CURRENT VariableSetKind = 2
	VAR_SET_MULTI   VariableSetKind = 3
	VAR_RESET       VariableSetKind = 4
	VAR_RESET_ALL   VariableSetKind = 5
)

func (e VariableSetKind) String() string {
	switch e {
	case VAR_SET_VALUE:
		return "VAR_SET_VALUE"
	case VAR_SET_DEFAULT:
		return "VAR_SET_DEFAULT"
	case VAR_SET_CURRENT:
		return "VAR_SET_CURRENT"
	case VAR_SET_MULTI:
		return "VAR_SET_MULTI"
	case VAR_RESET:
		return "VAR_RESET"
	case VAR_RESET_ALL:
		return "VAR_RESET_ALL"
	}
	return fmt.Sprintf("VariableSetKind(%d)", int32(e))
}

// ViewCheckOption is the PostgreSQL enum ViewCheckOption.
type ViewCheckOption int32

const (
	NO_CHECK_OPTION       ViewCheckOption = 0
	LOCAL_CHECK_OPTION    ViewCheckOption = 1
	CASCADED_CHECK_OPTION ViewCheckOption = 2
)

func (e ViewCheckOption) String() string {
	switch e {
	case NO_CHECK_OPTION:
		return "NO_CHECK_OPTION"
	case LOCAL_CHECK_OPTION:
		return "LOCAL_CHECK_OPTION"
	case CASCADED_CHECK_OPTION:
		return "CASCADED_CHECK_OPTION"
	}
	return fmt.Sprintf("ViewCheckOption(%d)", int32(e))
}

// WCOKind is the PostgreSQL enum WCOKind.
type WCOKind int32

const (
	WCO_VIEW_CHECK             WCOKind = 0
	WCO_RLS_INSERT_CHECK       WCOKind = 1
	WCO_RLS_UPDATE_CHECK       WCOKind = 2
	WCO_RLS_CONFLICT_CHECK     WCOKind = 3
	WCO_RLS_MERGE_UPDATE_CHECK WCOKind = 4
	WCO_RLS_MERGE_DELETE_CHECK WCOKind = 5
)

func (e WCOKind) String() string {
	switch e {
	case WCO_VIEW_CHECK:
		return "WCO_VIEW_CHECK"
	case WCO_RLS_INSERT_CHECK:
		return "WCO_RLS_INSERT_CHECK"
	case WCO_RLS_UPDATE_CHECK:
		return "WCO_RLS_UPDATE_CHECK"
	case WCO_RLS_CONFLICT_CHECK:
		return "WCO_RLS_CONFLICT_CHECK"
	case WCO_RLS_MERGE_UPDATE_CHECK:
		return "WCO_RLS_MERGE_UPDATE_CHECK"
	case WCO_RLS_MERGE_DELETE_CHECK:
		return "WCO_RLS_MERGE_DELETE_CHECK"
	}
	return fmt.Sprintf("WCOKind(%d)", int32(e))
}

// XmlExprOp is the PostgreSQL enum XmlExprOp.
type XmlExprOp int32

const (
	IS_XMLCONCAT    XmlExprOp = 0
	IS_XMLELEMENT   XmlExprOp = 1
	IS_XMLFOREST    XmlExprOp = 2
	IS_XMLPARSE     XmlExprOp = 3
	IS_XMLPI        XmlExprOp = 4
	IS_XMLROOT      XmlExprOp = 5
	IS_XMLSERIALIZE XmlExprOp = 6
	IS_DOCUMENT     XmlExprOp = 7
)

func (e XmlExprOp) String() string {
	switch e {
	case IS_XMLCONCAT:
		return "IS_XMLCONCAT"
	case IS_XMLELEMENT:
		return "IS_XMLELEMENT"
	case IS_XMLFOREST:
		return "IS_XMLFOREST"
	case IS_XMLPARSE:
		return "IS_XMLPARSE"
	case IS_XMLPI:
		return "IS_XMLPI"
	case IS_XMLROOT:
		return "IS_XMLROOT"
	case IS_XMLSERIALIZE:
		return "IS_XMLSERIALIZE"
	case IS_DOCUMENT:
		return "IS_DOCUMENT"
	}
	return fmt.Sprintf("XmlExprOp(%d)", int32(e))
}

// XmlOptionType is the PostgreSQL enum XmlOptionType.
type XmlOptionType int32

const (
	XMLOPTION_DOCUMENT XmlOptionType = 0
	XMLOPTION_CONTENT  XmlOptionType = 1
)

func (e XmlOptionType) String() string {
	switch e {
	case XMLOPTION_DOCUMENT:
		return "XMLOPTION_DOCUMENT"
	case XMLOPTION_CONTENT:
		return "XMLOPTION_CONTENT"
	}
	return fmt.Sprintf("XmlOptionType(%d)", int32(e))
}
