// Code generated by oracle/cmd/genast from the node descriptions of
// libpg_query (pg_query.proto); DO NOT EDIT.
//
// The nodes follow PostgreSQL's src/include/nodes/parsenodes.h and
// primnodes.h.
//
// Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
// Portions Copyright (c) 1994, Regents of the University of California
//
// PostgreSQL License: see ../../LICENSE.PostgreSQL. The descriptions come
// from libpg_query (BSD-3-Clause, Copyright (c) 2015, Lukas Fittl).

package ast

// Node is a node of the parse tree. Every node type is a pointer to a struct.
type Node interface {
	// Children calls f for every node directly below the node, in field
	// order: fields of type Node, nodes of a specific type and the elements
	// of lists. Fields that are nil are skipped.
	Children(f func(Node))
}

// Alias is the parse tree node Alias.
type Alias struct {
	Aliasname string
	Colnames  []Node
}

// RangeVar is the parse tree node RangeVar.
type RangeVar struct {
	Catalogname    string
	Schemaname     string
	Relname        string
	Inh            bool
	Relpersistence string
	Alias          *Alias
	Location       int32
}

// TableFunc is the parse tree node TableFunc.
type TableFunc struct {
	Functype        TableFuncType
	NsUris          []Node
	NsNames         []Node
	Docexpr         Node
	Rowexpr         Node
	Colnames        []Node
	Coltypes        []Node
	Coltypmods      []Node
	Colcollations   []Node
	Colexprs        []Node
	Coldefexprs     []Node
	Colvalexprs     []Node
	Passingvalexprs []Node
	Notnulls        []uint64
	Plan            Node
	Ordinalitycol   int32
	Location        int32
}

// IntoClause is the parse tree node IntoClause.
type IntoClause struct {
	Rel            *RangeVar
	ColNames       []Node
	AccessMethod   string
	Options        []Node
	OnCommit       OnCommitAction
	TableSpaceName string
	ViewQuery      Node
	SkipData       bool
}

// Var is the parse tree node Var.
type Var struct {
	Xpr            Node
	Varno          int32
	Varattno       int32
	Vartype        uint32
	Vartypmod      int32
	Varcollid      uint32
	Varnullingrels []uint64
	Varlevelsup    uint32
	Location       int32
}

// Param is the parse tree node Param.
type Param struct {
	Xpr         Node
	Paramkind   ParamKind
	Paramid     int32
	Paramtype   uint32
	Paramtypmod int32
	Paramcollid uint32
	Location    int32
}

// Aggref is the parse tree node Aggref.
type Aggref struct {
	Xpr           Node
	Aggfnoid      uint32
	Aggtype       uint32
	Aggcollid     uint32
	Inputcollid   uint32
	Aggargtypes   []Node
	Aggdirectargs []Node
	Args          []Node
	Aggorder      []Node
	Aggdistinct   []Node
	Aggfilter     Node
	Aggstar       bool
	Aggvariadic   bool
	Aggkind       string
	Agglevelsup   uint32
	Aggsplit      AggSplit
	Aggno         int32
	Aggtransno    int32
	Location      int32
}

// GroupingFunc is the parse tree node GroupingFunc.
type GroupingFunc struct {
	Xpr         Node
	Args        []Node
	Refs        []Node
	Agglevelsup uint32
	Location    int32
}

// WindowFunc is the parse tree node WindowFunc.
type WindowFunc struct {
	Xpr          Node
	Winfnoid     uint32
	Wintype      uint32
	Wincollid    uint32
	Inputcollid  uint32
	Args         []Node
	Aggfilter    Node
	RunCondition []Node
	Winref       uint32
	Winstar      bool
	Winagg       bool
	Location     int32
}

// WindowFuncRunCondition is the parse tree node WindowFuncRunCondition.
type WindowFuncRunCondition struct {
	Xpr         Node
	Opno        uint32
	Inputcollid uint32
	WfuncLeft   bool
	Arg         Node
}

// MergeSupportFunc is the parse tree node MergeSupportFunc.
type MergeSupportFunc struct {
	Xpr       Node
	Msftype   uint32
	Msfcollid uint32
	Location  int32
}

// SubscriptingRef is the parse tree node SubscriptingRef.
type SubscriptingRef struct {
	Xpr              Node
	Refcontainertype uint32
	Refelemtype      uint32
	Refrestype       uint32
	Reftypmod        int32
	Refcollid        uint32
	Refupperindexpr  []Node
	Reflowerindexpr  []Node
	Refexpr          Node
	Refassgnexpr     Node
}

// FuncExpr is the parse tree node FuncExpr.
type FuncExpr struct {
	Xpr            Node
	Funcid         uint32
	Funcresulttype uint32
	Funcretset     bool
	Funcvariadic   bool
	Funcformat     CoercionForm
	Funccollid     uint32
	Inputcollid    uint32
	Args           []Node
	Location       int32
}

// NamedArgExpr is the parse tree node NamedArgExpr.
type NamedArgExpr struct {
	Xpr       Node
	Arg       Node
	Name      string
	Argnumber int32
	Location  int32
}

// OpExpr is the parse tree node OpExpr.
type OpExpr struct {
	Xpr          Node
	Opno         uint32
	Opresulttype uint32
	Opretset     bool
	Opcollid     uint32
	Inputcollid  uint32
	Args         []Node
	Location     int32
}

// DistinctExpr is the parse tree node DistinctExpr.
type DistinctExpr struct {
	Xpr          Node
	Opno         uint32
	Opresulttype uint32
	Opretset     bool
	Opcollid     uint32
	Inputcollid  uint32
	Args         []Node
	Location     int32
}

// NullIfExpr is the parse tree node NullIfExpr.
type NullIfExpr struct {
	Xpr          Node
	Opno         uint32
	Opresulttype uint32
	Opretset     bool
	Opcollid     uint32
	Inputcollid  uint32
	Args         []Node
	Location     int32
}

// ScalarArrayOpExpr is the parse tree node ScalarArrayOpExpr.
type ScalarArrayOpExpr struct {
	Xpr         Node
	Opno        uint32
	UseOr       bool
	Inputcollid uint32
	Args        []Node
	Location    int32
}

// BoolExpr is the parse tree node BoolExpr.
type BoolExpr struct {
	Xpr      Node
	Boolop   BoolExprType
	Args     []Node
	Location int32
}

// SubLink is the parse tree node SubLink.
type SubLink struct {
	Xpr         Node
	SubLinkType SubLinkType
	SubLinkId   int32
	Testexpr    Node
	OperName    []Node
	Subselect   Node
	Location    int32
}

// SubPlan is the parse tree node SubPlan.
type SubPlan struct {
	Xpr               Node
	SubLinkType       SubLinkType
	Testexpr          Node
	ParamIds          []Node
	PlanId            int32
	PlanName          string
	FirstColType      uint32
	FirstColTypmod    int32
	FirstColCollation uint32
	UseHashTable      bool
	UnknownEqFalse    bool
	ParallelSafe      bool
	SetParam          []Node
	ParParam          []Node
	Args              []Node
	StartupCost       float64
	PerCallCost       float64
}

// AlternativeSubPlan is the parse tree node AlternativeSubPlan.
type AlternativeSubPlan struct {
	Xpr      Node
	Subplans []Node
}

// FieldSelect is the parse tree node FieldSelect.
type FieldSelect struct {
	Xpr          Node
	Arg          Node
	Fieldnum     int32
	Resulttype   uint32
	Resulttypmod int32
	Resultcollid uint32
}

// FieldStore is the parse tree node FieldStore.
type FieldStore struct {
	Xpr        Node
	Arg        Node
	Newvals    []Node
	Fieldnums  []Node
	Resulttype uint32
}

// RelabelType is the parse tree node RelabelType.
type RelabelType struct {
	Xpr           Node
	Arg           Node
	Resulttype    uint32
	Resulttypmod  int32
	Resultcollid  uint32
	Relabelformat CoercionForm
	Location      int32
}

// CoerceViaIO is the parse tree node CoerceViaIO.
type CoerceViaIO struct {
	Xpr          Node
	Arg          Node
	Resulttype   uint32
	Resultcollid uint32
	Coerceformat CoercionForm
	Location     int32
}

// ArrayCoerceExpr is the parse tree node ArrayCoerceExpr.
type ArrayCoerceExpr struct {
	Xpr          Node
	Arg          Node
	Elemexpr     Node
	Resulttype   uint32
	Resulttypmod int32
	Resultcollid uint32
	Coerceformat CoercionForm
	Location     int32
}

// ConvertRowtypeExpr is the parse tree node ConvertRowtypeExpr.
type ConvertRowtypeExpr struct {
	Xpr           Node
	Arg           Node
	Resulttype    uint32
	Convertformat CoercionForm
	Location      int32
}

// CollateExpr is the parse tree node CollateExpr.
type CollateExpr struct {
	Xpr      Node
	Arg      Node
	CollOid  uint32
	Location int32
}

// CaseExpr is the parse tree node CaseExpr.
type CaseExpr struct {
	Xpr        Node
	Casetype   uint32
	Casecollid uint32
	Arg        Node
	Args       []Node
	Defresult  Node
	Location   int32
}

// CaseWhen is the parse tree node CaseWhen.
type CaseWhen struct {
	Xpr      Node
	Expr     Node
	Result   Node
	Location int32
}

// CaseTestExpr is the parse tree node CaseTestExpr.
type CaseTestExpr struct {
	Xpr       Node
	TypeId    uint32
	TypeMod   int32
	Collation uint32
}

// ArrayExpr is the parse tree node ArrayExpr.
type ArrayExpr struct {
	Xpr           Node
	ArrayTypeid   uint32
	ArrayCollid   uint32
	ElementTypeid uint32
	Elements      []Node
	Multidims     bool
	Location      int32
}

// RowExpr is the parse tree node RowExpr.
type RowExpr struct {
	Xpr       Node
	Args      []Node
	RowTypeid uint32
	RowFormat CoercionForm
	Colnames  []Node
	Location  int32
}

// RowCompareExpr is the parse tree node RowCompareExpr.
type RowCompareExpr struct {
	Xpr          Node
	Rctype       RowCompareType
	Opnos        []Node
	Opfamilies   []Node
	Inputcollids []Node
	Largs        []Node
	Rargs        []Node
}

// CoalesceExpr is the parse tree node CoalesceExpr.
type CoalesceExpr struct {
	Xpr            Node
	Coalescetype   uint32
	Coalescecollid uint32
	Args           []Node
	Location       int32
}

// MinMaxExpr is the parse tree node MinMaxExpr.
type MinMaxExpr struct {
	Xpr          Node
	Minmaxtype   uint32
	Minmaxcollid uint32
	Inputcollid  uint32
	Op           MinMaxOp
	Args         []Node
	Location     int32
}

// SQLValueFunction is the parse tree node SQLValueFunction.
type SQLValueFunction struct {
	Xpr      Node
	Op       SQLValueFunctionOp
	Type     uint32
	Typmod   int32
	Location int32
}

// XmlExpr is the parse tree node XmlExpr.
type XmlExpr struct {
	Xpr       Node
	Op        XmlExprOp
	Name      string
	NamedArgs []Node
	ArgNames  []Node
	Args      []Node
	Xmloption XmlOptionType
	Indent    bool
	Type      uint32
	Typmod    int32
	Location  int32
}

// JsonFormat is the parse tree node JsonFormat.
type JsonFormat struct {
	FormatType JsonFormatType
	Encoding   JsonEncoding
	Location   int32
}

// JsonReturning is the parse tree node JsonReturning.
type JsonReturning struct {
	Format *JsonFormat
	Typid  uint32
	Typmod int32
}

// JsonValueExpr is the parse tree node JsonValueExpr.
type JsonValueExpr struct {
	RawExpr       Node
	FormattedExpr Node
	Format        *JsonFormat
}

// JsonConstructorExpr is the parse tree node JsonConstructorExpr.
type JsonConstructorExpr struct {
	Xpr          Node
	Type         JsonConstructorType
	Args         []Node
	Func         Node
	Coercion     Node
	Returning    *JsonReturning
	AbsentOnNull bool
	Unique       bool
	Location     int32
}

// JsonIsPredicate is the parse tree node JsonIsPredicate.
type JsonIsPredicate struct {
	Expr       Node
	Format     *JsonFormat
	ItemType   JsonValueType
	UniqueKeys bool
	Location   int32
}

// JsonBehavior is the parse tree node JsonBehavior.
type JsonBehavior struct {
	Btype    JsonBehaviorType
	Expr     Node
	Coerce   bool
	Location int32
}

// JsonExpr is the parse tree node JsonExpr.
type JsonExpr struct {
	Xpr             Node
	Op              JsonExprOp
	ColumnName      string
	FormattedExpr   Node
	Format          *JsonFormat
	PathSpec        Node
	Returning       *JsonReturning
	PassingNames    []Node
	PassingValues   []Node
	OnEmpty         *JsonBehavior
	OnError         *JsonBehavior
	UseIoCoercion   bool
	UseJsonCoercion bool
	Wrapper         JsonWrapper
	OmitQuotes      bool
	Collation       uint32
	Location        int32
}

// JsonTablePath is the parse tree node JsonTablePath.
type JsonTablePath struct {
	Name string
}

// JsonTablePathScan is the parse tree node JsonTablePathScan.
type JsonTablePathScan struct {
	Plan         Node
	Path         *JsonTablePath
	ErrorOnError bool
	Child        Node
	ColMin       int32
	ColMax       int32
}

// JsonTableSiblingJoin is the parse tree node JsonTableSiblingJoin.
type JsonTableSiblingJoin struct {
	Plan  Node
	Lplan Node
	Rplan Node
}

// NullTest is the parse tree node NullTest.
type NullTest struct {
	Xpr          Node
	Arg          Node
	Nulltesttype NullTestType
	Argisrow     bool
	Location     int32
}

// BooleanTest is the parse tree node BooleanTest.
type BooleanTest struct {
	Xpr          Node
	Arg          Node
	Booltesttype BoolTestType
	Location     int32
}

// MergeAction is the parse tree node MergeAction.
type MergeAction struct {
	MatchKind    MergeMatchKind
	CommandType  CmdType
	Override     OverridingKind
	Qual         Node
	TargetList   []Node
	UpdateColnos []Node
}

// CoerceToDomain is the parse tree node CoerceToDomain.
type CoerceToDomain struct {
	Xpr            Node
	Arg            Node
	Resulttype     uint32
	Resulttypmod   int32
	Resultcollid   uint32
	Coercionformat CoercionForm
	Location       int32
}

// CoerceToDomainValue is the parse tree node CoerceToDomainValue.
type CoerceToDomainValue struct {
	Xpr       Node
	TypeId    uint32
	TypeMod   int32
	Collation uint32
	Location  int32
}

// SetToDefault is the parse tree node SetToDefault.
type SetToDefault struct {
	Xpr       Node
	TypeId    uint32
	TypeMod   int32
	Collation uint32
	Location  int32
}

// CurrentOfExpr is the parse tree node CurrentOfExpr.
type CurrentOfExpr struct {
	Xpr         Node
	Cvarno      uint32
	CursorName  string
	CursorParam int32
}

// NextValueExpr is the parse tree node NextValueExpr.
type NextValueExpr struct {
	Xpr    Node
	Seqid  uint32
	TypeId uint32
}

// InferenceElem is the parse tree node InferenceElem.
type InferenceElem struct {
	Xpr          Node
	Expr         Node
	Infercollid  uint32
	Inferopclass uint32
}

// TargetEntry is the parse tree node TargetEntry.
type TargetEntry struct {
	Xpr             Node
	Expr            Node
	Resno           int32
	Resname         string
	Ressortgroupref uint32
	Resorigtbl      uint32
	Resorigcol      int32
	Resjunk         bool
}

// RangeTblRef is the parse tree node RangeTblRef.
type RangeTblRef struct {
	Rtindex int32
}

// JoinExpr is the parse tree node JoinExpr.
type JoinExpr struct {
	Jointype       JoinType
	IsNatural      bool
	Larg           Node
	Rarg           Node
	UsingClause    []Node
	JoinUsingAlias *Alias
	Quals          Node
	Alias          *Alias
	Rtindex        int32
}

// FromExpr is the parse tree node FromExpr.
type FromExpr struct {
	Fromlist []Node
	Quals    Node
}

// OnConflictExpr is the parse tree node OnConflictExpr.
type OnConflictExpr struct {
	Action          OnConflictAction
	ArbiterElems    []Node
	ArbiterWhere    Node
	Constraint      uint32
	OnConflictSet   []Node
	OnConflictWhere Node
	ExclRelIndex    int32
	ExclRelTlist    []Node
}

// Query is the parse tree node Query.
type Query struct {
	CommandType         CmdType
	QuerySource         QuerySource
	CanSetTag           bool
	UtilityStmt         Node
	ResultRelation      int32
	HasAggs             bool
	HasWindowFuncs      bool
	HasTargetSrfs       bool
	HasSubLinks         bool
	HasDistinctOn       bool
	HasRecursive        bool
	HasModifyingCte     bool
	HasForUpdate        bool
	HasRowSecurity      bool
	IsReturn            bool
	CteList             []Node
	Rtable              []Node
	Rteperminfos        []Node
	Jointree            *FromExpr
	MergeActionList     []Node
	MergeTargetRelation int32
	MergeJoinCondition  Node
	TargetList          []Node
	Override            OverridingKind
	OnConflict          *OnConflictExpr
	ReturningList       []Node
	GroupClause         []Node
	GroupDistinct       bool
	GroupingSets        []Node
	HavingQual          Node
	WindowClause        []Node
	DistinctClause      []Node
	SortClause          []Node
	LimitOffset         Node
	LimitCount          Node
	LimitOption         LimitOption
	RowMarks            []Node
	SetOperations       Node
	ConstraintDeps      []Node
	WithCheckOptions    []Node
	StmtLocation        int32
	StmtLen             int32
}

// TypeName is the parse tree node TypeName.
type TypeName struct {
	Names       []Node
	TypeOid     uint32
	Setof       bool
	PctType     bool
	Typmods     []Node
	Typemod     int32
	ArrayBounds []Node
	Location    int32
}

// ColumnRef is the parse tree node ColumnRef.
type ColumnRef struct {
	Fields   []Node
	Location int32
}

// ParamRef is the parse tree node ParamRef.
type ParamRef struct {
	Number   int32
	Location int32
}

// A_Expr is the parse tree node A_Expr.
type A_Expr struct {
	Kind     A_Expr_Kind
	Name     []Node
	Lexpr    Node
	Rexpr    Node
	Location int32
}

// TypeCast is the parse tree node TypeCast.
type TypeCast struct {
	Arg      Node
	TypeName *TypeName
	Location int32
}

// CollateClause is the parse tree node CollateClause.
type CollateClause struct {
	Arg      Node
	Collname []Node
	Location int32
}

// RoleSpec is the parse tree node RoleSpec.
type RoleSpec struct {
	Roletype RoleSpecType
	Rolename string
	Location int32
}

// FuncCall is the parse tree node FuncCall.
type FuncCall struct {
	Funcname       []Node
	Args           []Node
	AggOrder       []Node
	AggFilter      Node
	Over           *WindowDef
	AggWithinGroup bool
	AggStar        bool
	AggDistinct    bool
	FuncVariadic   bool
	Funcformat     CoercionForm
	Location       int32
}

// A_Star is the parse tree node A_Star.
type A_Star struct {
}

// A_Indices is the parse tree node A_Indices.
type A_Indices struct {
	IsSlice bool
	Lidx    Node
	Uidx    Node
}

// A_Indirection is the parse tree node A_Indirection.
type A_Indirection struct {
	Arg         Node
	Indirection []Node
}

// A_ArrayExpr is the parse tree node A_ArrayExpr.
type A_ArrayExpr struct {
	Elements []Node
	Location int32
}

// ResTarget is the parse tree node ResTarget.
type ResTarget struct {
	Name        string
	Indirection []Node
	Val         Node
	Location    int32
}

// MultiAssignRef is the parse tree node MultiAssignRef.
type MultiAssignRef struct {
	Source   Node
	Colno    int32
	Ncolumns int32
}

// SortBy is the parse tree node SortBy.
type SortBy struct {
	Node        Node
	SortbyDir   SortByDir
	SortbyNulls SortByNulls
	UseOp       []Node
	Location    int32
}

// WindowDef is the parse tree node WindowDef.
type WindowDef struct {
	Name            string
	Refname         string
	PartitionClause []Node
	OrderClause     []Node
	FrameOptions    int32
	StartOffset     Node
	EndOffset       Node
	Location        int32
}

// RangeSubselect is the parse tree node RangeSubselect.
type RangeSubselect struct {
	Lateral  bool
	Subquery Node
	Alias    *Alias
}

// RangeFunction is the parse tree node RangeFunction.
type RangeFunction struct {
	Lateral    bool
	Ordinality bool
	IsRowsfrom bool
	Functions  []Node
	Alias      *Alias
	Coldeflist []Node
}

// RangeTableFunc is the parse tree node RangeTableFunc.
type RangeTableFunc struct {
	Lateral    bool
	Docexpr    Node
	Rowexpr    Node
	Namespaces []Node
	Columns    []Node
	Alias      *Alias
	Location   int32
}

// RangeTableFuncCol is the parse tree node RangeTableFuncCol.
type RangeTableFuncCol struct {
	Colname       string
	TypeName      *TypeName
	ForOrdinality bool
	IsNotNull     bool
	Colexpr       Node
	Coldefexpr    Node
	Location      int32
}

// RangeTableSample is the parse tree node RangeTableSample.
type RangeTableSample struct {
	Relation   Node
	Method     []Node
	Args       []Node
	Repeatable Node
	Location   int32
}

// ColumnDef is the parse tree node ColumnDef.
type ColumnDef struct {
	Colname          string
	TypeName         *TypeName
	Compression      string
	Inhcount         int32
	IsLocal          bool
	IsNotNull        bool
	IsFromType       bool
	Storage          string
	StorageName      string
	RawDefault       Node
	CookedDefault    Node
	Identity         string
	IdentitySequence *RangeVar
	Generated        string
	CollClause       *CollateClause
	CollOid          uint32
	Constraints      []Node
	Fdwoptions       []Node
	Location         int32
}

// TableLikeClause is the parse tree node TableLikeClause.
type TableLikeClause struct {
	Relation    *RangeVar
	Options     uint32
	RelationOid uint32
}

// IndexElem is the parse tree node IndexElem.
type IndexElem struct {
	Name          string
	Expr          Node
	Indexcolname  string
	Collation     []Node
	Opclass       []Node
	Opclassopts   []Node
	Ordering      SortByDir
	NullsOrdering SortByNulls
}

// DefElem is the parse tree node DefElem.
type DefElem struct {
	Defnamespace string
	Defname      string
	Arg          Node
	Defaction    DefElemAction
	Location     int32
}

// LockingClause is the parse tree node LockingClause.
type LockingClause struct {
	LockedRels []Node
	Strength   LockClauseStrength
	WaitPolicy LockWaitPolicy
}

// XmlSerialize is the parse tree node XmlSerialize.
type XmlSerialize struct {
	Xmloption XmlOptionType
	Expr      Node
	TypeName  *TypeName
	Indent    bool
	Location  int32
}

// PartitionElem is the parse tree node PartitionElem.
type PartitionElem struct {
	Name      string
	Expr      Node
	Collation []Node
	Opclass   []Node
	Location  int32
}

// PartitionSpec is the parse tree node PartitionSpec.
type PartitionSpec struct {
	Strategy   PartitionStrategy
	PartParams []Node
	Location   int32
}

// PartitionBoundSpec is the parse tree node PartitionBoundSpec.
type PartitionBoundSpec struct {
	Strategy    string
	IsDefault   bool
	Modulus     int32
	Remainder   int32
	Listdatums  []Node
	Lowerdatums []Node
	Upperdatums []Node
	Location    int32
}

// PartitionRangeDatum is the parse tree node PartitionRangeDatum.
type PartitionRangeDatum struct {
	Kind     PartitionRangeDatumKind
	Value    Node
	Location int32
}

// SinglePartitionSpec is the parse tree node SinglePartitionSpec.
type SinglePartitionSpec struct {
}

// PartitionCmd is the parse tree node PartitionCmd.
type PartitionCmd struct {
	Name       *RangeVar
	Bound      *PartitionBoundSpec
	Concurrent bool
}

// RangeTblEntry is the parse tree node RangeTblEntry.
type RangeTblEntry struct {
	Alias           *Alias
	Eref            *Alias
	Rtekind         RTEKind
	Relid           uint32
	Inh             bool
	Relkind         string
	Rellockmode     int32
	Perminfoindex   uint32
	Tablesample     *TableSampleClause
	Subquery        *Query
	SecurityBarrier bool
	Jointype        JoinType
	Joinmergedcols  int32
	Joinaliasvars   []Node
	Joinleftcols    []Node
	Joinrightcols   []Node
	JoinUsingAlias  *Alias
	Functions       []Node
	Funcordinality  bool
	Tablefunc       *TableFunc
	ValuesLists     []Node
	Ctename         string
	Ctelevelsup     uint32
	SelfReference   bool
	Coltypes        []Node
	Coltypmods      []Node
	Colcollations   []Node
	Enrname         string
	Enrtuples       float64
	Lateral         bool
	InFromCl        bool
	SecurityQuals   []Node
}

// RTEPermissionInfo is the parse tree node RTEPermissionInfo.
type RTEPermissionInfo struct {
	Relid         uint32
	Inh           bool
	RequiredPerms uint64
	CheckAsUser   uint32
	SelectedCols  []uint64
	InsertedCols  []uint64
	UpdatedCols   []uint64
}

// RangeTblFunction is the parse tree node RangeTblFunction.
type RangeTblFunction struct {
	Funcexpr          Node
	Funccolcount      int32
	Funccolnames      []Node
	Funccoltypes      []Node
	Funccoltypmods    []Node
	Funccolcollations []Node
	Funcparams        []uint64
}

// TableSampleClause is the parse tree node TableSampleClause.
type TableSampleClause struct {
	Tsmhandler uint32
	Args       []Node
	Repeatable Node
}

// WithCheckOption is the parse tree node WithCheckOption.
type WithCheckOption struct {
	Kind     WCOKind
	Relname  string
	Polname  string
	Qual     Node
	Cascaded bool
}

// SortGroupClause is the parse tree node SortGroupClause.
type SortGroupClause struct {
	TleSortGroupRef uint32
	Eqop            uint32
	Sortop          uint32
	NullsFirst      bool
	Hashable        bool
}

// GroupingSet is the parse tree node GroupingSet.
type GroupingSet struct {
	Kind     GroupingSetKind
	Content  []Node
	Location int32
}

// WindowClause is the parse tree node WindowClause.
type WindowClause struct {
	Name              string
	Refname           string
	PartitionClause   []Node
	OrderClause       []Node
	FrameOptions      int32
	StartOffset       Node
	EndOffset         Node
	StartInRangeFunc  uint32
	EndInRangeFunc    uint32
	InRangeColl       uint32
	InRangeAsc        bool
	InRangeNullsFirst bool
	Winref            uint32
	CopiedOrder       bool
}

// RowMarkClause is the parse tree node RowMarkClause.
type RowMarkClause struct {
	Rti        uint32
	Strength   LockClauseStrength
	WaitPolicy LockWaitPolicy
	PushedDown bool
}

// WithClause is the parse tree node WithClause.
type WithClause struct {
	Ctes      []Node
	Recursive bool
	Location  int32
}

// InferClause is the parse tree node InferClause.
type InferClause struct {
	IndexElems  []Node
	WhereClause Node
	Conname     string
	Location    int32
}

// OnConflictClause is the parse tree node OnConflictClause.
type OnConflictClause struct {
	Action      OnConflictAction
	Infer       *InferClause
	TargetList  []Node
	WhereClause Node
	Location    int32
}

// CTESearchClause is the parse tree node CTESearchClause.
type CTESearchClause struct {
	SearchColList      []Node
	SearchBreadthFirst bool
	SearchSeqColumn    string
	Location           int32
}

// CTECycleClause is the parse tree node CTECycleClause.
type CTECycleClause struct {
	CycleColList       []Node
	CycleMarkColumn    string
	CycleMarkValue     Node
	CycleMarkDefault   Node
	CyclePathColumn    string
	Location           int32
	CycleMarkType      uint32
	CycleMarkTypmod    int32
	CycleMarkCollation uint32
	CycleMarkNeop      uint32
}

// CommonTableExpr is the parse tree node CommonTableExpr.
type CommonTableExpr struct {
	Ctename          string
	Aliascolnames    []Node
	Ctematerialized  CTEMaterialize
	Ctequery         Node
	SearchClause     *CTESearchClause
	CycleClause      *CTECycleClause
	Location         int32
	Cterecursive     bool
	Cterefcount      int32
	Ctecolnames      []Node
	Ctecoltypes      []Node
	Ctecoltypmods    []Node
	Ctecolcollations []Node
}

// MergeWhenClause is the parse tree node MergeWhenClause.
type MergeWhenClause struct {
	MatchKind   MergeMatchKind
	CommandType CmdType
	Override    OverridingKind
	Condition   Node
	TargetList  []Node
	Values      []Node
}

// TriggerTransition is the parse tree node TriggerTransition.
type TriggerTransition struct {
	Name    string
	IsNew   bool
	IsTable bool
}

// JsonOutput is the parse tree node JsonOutput.
type JsonOutput struct {
	TypeName  *TypeName
	Returning *JsonReturning
}

// JsonArgument is the parse tree node JsonArgument.
type JsonArgument struct {
	Val  *JsonValueExpr
	Name string
}

// JsonFuncExpr is the parse tree node JsonFuncExpr.
type JsonFuncExpr struct {
	Op          JsonExprOp
	ColumnName  string
	ContextItem *JsonValueExpr
	Pathspec    Node
	Passing     []Node
	Output      *JsonOutput
	OnEmpty     *JsonBehavior
	OnError     *JsonBehavior
	Wrapper     JsonWrapper
	Quotes      JsonQuotes
	Location    int32
}

// JsonTablePathSpec is the parse tree node JsonTablePathSpec.
type JsonTablePathSpec struct {
	String       Node
	Name         string
	NameLocation int32
	Location     int32
}

// JsonTable is the parse tree node JsonTable.
type JsonTable struct {
	ContextItem *JsonValueExpr
	Pathspec    *JsonTablePathSpec
	Passing     []Node
	Columns     []Node
	OnError     *JsonBehavior
	Alias       *Alias
	Lateral     bool
	Location    int32
}

// JsonTableColumn is the parse tree node JsonTableColumn.
type JsonTableColumn struct {
	Coltype  JsonTableColumnType
	Name     string
	TypeName *TypeName
	Pathspec *JsonTablePathSpec
	Format   *JsonFormat
	Wrapper  JsonWrapper
	Quotes   JsonQuotes
	Columns  []Node
	OnEmpty  *JsonBehavior
	OnError  *JsonBehavior
	Location int32
}

// JsonKeyValue is the parse tree node JsonKeyValue.
type JsonKeyValue struct {
	Key   Node
	Value *JsonValueExpr
}

// JsonParseExpr is the parse tree node JsonParseExpr.
type JsonParseExpr struct {
	Expr       *JsonValueExpr
	Output     *JsonOutput
	UniqueKeys bool
	Location   int32
}

// JsonScalarExpr is the parse tree node JsonScalarExpr.
type JsonScalarExpr struct {
	Expr     Node
	Output   *JsonOutput
	Location int32
}

// JsonSerializeExpr is the parse tree node JsonSerializeExpr.
type JsonSerializeExpr struct {
	Expr     *JsonValueExpr
	Output   *JsonOutput
	Location int32
}

// JsonObjectConstructor is the parse tree node JsonObjectConstructor.
type JsonObjectConstructor struct {
	Exprs        []Node
	Output       *JsonOutput
	AbsentOnNull bool
	Unique       bool
	Location     int32
}

// JsonArrayConstructor is the parse tree node JsonArrayConstructor.
type JsonArrayConstructor struct {
	Exprs        []Node
	Output       *JsonOutput
	AbsentOnNull bool
	Location     int32
}

// JsonArrayQueryConstructor is the parse tree node JsonArrayQueryConstructor.
type JsonArrayQueryConstructor struct {
	Query        Node
	Output       *JsonOutput
	Format       *JsonFormat
	AbsentOnNull bool
	Location     int32
}

// JsonAggConstructor is the parse tree node JsonAggConstructor.
type JsonAggConstructor struct {
	Output    *JsonOutput
	AggFilter Node
	AggOrder  []Node
	Over      *WindowDef
	Location  int32
}

// JsonObjectAgg is the parse tree node JsonObjectAgg.
type JsonObjectAgg struct {
	Constructor  *JsonAggConstructor
	Arg          *JsonKeyValue
	AbsentOnNull bool
	Unique       bool
}

// JsonArrayAgg is the parse tree node JsonArrayAgg.
type JsonArrayAgg struct {
	Constructor  *JsonAggConstructor
	Arg          *JsonValueExpr
	AbsentOnNull bool
}

// RawStmt is the parse tree node RawStmt.
type RawStmt struct {
	Stmt         Node
	StmtLocation int32
	StmtLen      int32
}

// InsertStmt is the parse tree node InsertStmt.
type InsertStmt struct {
	Relation         *RangeVar
	Cols             []Node
	SelectStmt       Node
	OnConflictClause *OnConflictClause
	ReturningList    []Node
	WithClause       *WithClause
	Override         OverridingKind
}

// DeleteStmt is the parse tree node DeleteStmt.
type DeleteStmt struct {
	Relation      *RangeVar
	UsingClause   []Node
	WhereClause   Node
	ReturningList []Node
	WithClause    *WithClause
}

// UpdateStmt is the parse tree node UpdateStmt.
type UpdateStmt struct {
	Relation      *RangeVar
	TargetList    []Node
	WhereClause   Node
	FromClause    []Node
	ReturningList []Node
	WithClause    *WithClause
}

// MergeStmt is the parse tree node MergeStmt.
type MergeStmt struct {
	Relation         *RangeVar
	SourceRelation   Node
	JoinCondition    Node
	MergeWhenClauses []Node
	ReturningList    []Node
	WithClause       *WithClause
}

// SelectStmt is the parse tree node SelectStmt.
type SelectStmt struct {
	DistinctClause []Node
	IntoClause     *IntoClause
	TargetList     []Node
	FromClause     []Node
	WhereClause    Node
	GroupClause    []Node
	GroupDistinct  bool
	HavingClause   Node
	WindowClause   []Node
	ValuesLists    []Node
	SortClause     []Node
	LimitOffset    Node
	LimitCount     Node
	LimitOption    LimitOption
	LockingClause  []Node
	WithClause     *WithClause
	Op             SetOperation
	All            bool
	Larg           *SelectStmt
	Rarg           *SelectStmt
}

// SetOperationStmt is the parse tree node SetOperationStmt.
type SetOperationStmt struct {
	Op            SetOperation
	All           bool
	Larg          Node
	Rarg          Node
	ColTypes      []Node
	ColTypmods    []Node
	ColCollations []Node
	GroupClauses  []Node
}

// ReturnStmt is the parse tree node ReturnStmt.
type ReturnStmt struct {
	Returnval Node
}

// PLAssignStmt is the parse tree node PLAssignStmt.
type PLAssignStmt struct {
	Name        string
	Indirection []Node
	Nnames      int32
	Val         *SelectStmt
	Location    int32
}

// CreateSchemaStmt is the parse tree node CreateSchemaStmt.
type CreateSchemaStmt struct {
	Schemaname  string
	Authrole    *RoleSpec
	SchemaElts  []Node
	IfNotExists bool
}

// AlterTableStmt is the parse tree node AlterTableStmt.
type AlterTableStmt struct {
	Relation  *RangeVar
	Cmds      []Node
	Objtype   ObjectType
	MissingOk bool
}

// ReplicaIdentityStmt is the parse tree node ReplicaIdentityStmt.
type ReplicaIdentityStmt struct {
	IdentityType string
	Name         string
}

// AlterTableCmd is the parse tree node AlterTableCmd.
type AlterTableCmd struct {
	Subtype   AlterTableType
	Name      string
	Num       int32
	Newowner  *RoleSpec
	Def       Node
	Behavior  DropBehavior
	MissingOk bool
	Recurse   bool
}

// AlterCollationStmt is the parse tree node AlterCollationStmt.
type AlterCollationStmt struct {
	Collname []Node
}

// AlterDomainStmt is the parse tree node AlterDomainStmt.
type AlterDomainStmt struct {
	Subtype   string
	TypeName  []Node
	Name      string
	Def       Node
	Behavior  DropBehavior
	MissingOk bool
}

// GrantStmt is the parse tree node GrantStmt.
type GrantStmt struct {
	IsGrant     bool
	Targtype    GrantTargetType
	Objtype     ObjectType
	Objects     []Node
	Privileges  []Node
	Grantees    []Node
	GrantOption bool
	Grantor     *RoleSpec
	Behavior    DropBehavior
}

// ObjectWithArgs is the parse tree node ObjectWithArgs.
type ObjectWithArgs struct {
	Objname         []Node
	Objargs         []Node
	Objfuncargs     []Node
	ArgsUnspecified bool
}

// AccessPriv is the parse tree node AccessPriv.
type AccessPriv struct {
	PrivName string
	Cols     []Node
}

// GrantRoleStmt is the parse tree node GrantRoleStmt.
type GrantRoleStmt struct {
	GrantedRoles []Node
	GranteeRoles []Node
	IsGrant      bool
	Opt          []Node
	Grantor      *RoleSpec
	Behavior     DropBehavior
}

// AlterDefaultPrivilegesStmt is the parse tree node AlterDefaultPrivilegesStmt.
type AlterDefaultPrivilegesStmt struct {
	Options []Node
	Action  *GrantStmt
}

// CopyStmt is the parse tree node CopyStmt.
type CopyStmt struct {
	Relation    *RangeVar
	Query       Node
	Attlist     []Node
	IsFrom      bool
	IsProgram   bool
	Filename    string
	Options     []Node
	WhereClause Node
}

// VariableSetStmt is the parse tree node VariableSetStmt.
type VariableSetStmt struct {
	Kind    VariableSetKind
	Name    string
	Args    []Node
	IsLocal bool
}

// VariableShowStmt is the parse tree node VariableShowStmt.
type VariableShowStmt struct {
	Name string
}

// CreateStmt is the parse tree node CreateStmt.
type CreateStmt struct {
	Relation       *RangeVar
	TableElts      []Node
	InhRelations   []Node
	Partbound      *PartitionBoundSpec
	Partspec       *PartitionSpec
	OfTypename     *TypeName
	Constraints    []Node
	Options        []Node
	Oncommit       OnCommitAction
	Tablespacename string
	AccessMethod   string
	IfNotExists    bool
}

// Constraint is the parse tree node Constraint.
type Constraint struct {
	Contype            ConstrType
	Conname            string
	Deferrable         bool
	Initdeferred       bool
	SkipValidation     bool
	InitiallyValid     bool
	IsNoInherit        bool
	RawExpr            Node
	CookedExpr         string
	GeneratedWhen      string
	Inhcount           int32
	NullsNotDistinct   bool
	Keys               []Node
	Including          []Node
	Exclusions         []Node
	Options            []Node
	Indexname          string
	Indexspace         string
	ResetDefaultTblspc bool
	AccessMethod       string
	WhereClause        Node
	Pktable            *RangeVar
	FkAttrs            []Node
	PkAttrs            []Node
	FkMatchtype        string
	FkUpdAction        string
	FkDelAction        string
	FkDelSetCols       []Node
	OldConpfeqop       []Node
	OldPktableOid      uint32
	Location           int32
}

// CreateTableSpaceStmt is the parse tree node CreateTableSpaceStmt.
type CreateTableSpaceStmt struct {
	Tablespacename string
	Owner          *RoleSpec
	Location       string
	Options        []Node
}

// DropTableSpaceStmt is the parse tree node DropTableSpaceStmt.
type DropTableSpaceStmt struct {
	Tablespacename string
	MissingOk      bool
}

// AlterTableSpaceOptionsStmt is the parse tree node AlterTableSpaceOptionsStmt.
type AlterTableSpaceOptionsStmt struct {
	Tablespacename string
	Options        []Node
	IsReset        bool
}

// AlterTableMoveAllStmt is the parse tree node AlterTableMoveAllStmt.
type AlterTableMoveAllStmt struct {
	OrigTablespacename string
	Objtype            ObjectType
	Roles              []Node
	NewTablespacename  string
	Nowait             bool
}

// CreateExtensionStmt is the parse tree node CreateExtensionStmt.
type CreateExtensionStmt struct {
	Extname     string
	IfNotExists bool
	Options     []Node
}

// AlterExtensionStmt is the parse tree node AlterExtensionStmt.
type AlterExtensionStmt struct {
	Extname string
	Options []Node
}

// AlterExtensionContentsStmt is the parse tree node AlterExtensionContentsStmt.
type AlterExtensionContentsStmt struct {
	Extname string
	Action  int32
	Objtype ObjectType
	Object  Node
}

// CreateFdwStmt is the parse tree node CreateFdwStmt.
type CreateFdwStmt struct {
	Fdwname     string
	FuncOptions []Node
	Options     []Node
}

// AlterFdwStmt is the parse tree node AlterFdwStmt.
type AlterFdwStmt struct {
	Fdwname     string
	FuncOptions []Node
	Options     []Node
}

// CreateForeignServerStmt is the parse tree node CreateForeignServerStmt.
type CreateForeignServerStmt struct {
	Servername  string
	Servertype  string
	Version     string
	Fdwname     string
	IfNotExists bool
	Options     []Node
}

// AlterForeignServerStmt is the parse tree node AlterForeignServerStmt.
type AlterForeignServerStmt struct {
	Servername string
	Version    string
	Options    []Node
	HasVersion bool
}

// CreateForeignTableStmt is the parse tree node CreateForeignTableStmt.
type CreateForeignTableStmt struct {
	BaseStmt   *CreateStmt
	Servername string
	Options    []Node
}

// CreateUserMappingStmt is the parse tree node CreateUserMappingStmt.
type CreateUserMappingStmt struct {
	User        *RoleSpec
	Servername  string
	IfNotExists bool
	Options     []Node
}

// AlterUserMappingStmt is the parse tree node AlterUserMappingStmt.
type AlterUserMappingStmt struct {
	User       *RoleSpec
	Servername string
	Options    []Node
}

// DropUserMappingStmt is the parse tree node DropUserMappingStmt.
type DropUserMappingStmt struct {
	User       *RoleSpec
	Servername string
	MissingOk  bool
}

// ImportForeignSchemaStmt is the parse tree node ImportForeignSchemaStmt.
type ImportForeignSchemaStmt struct {
	ServerName   string
	RemoteSchema string
	LocalSchema  string
	ListType     ImportForeignSchemaType
	TableList    []Node
	Options      []Node
}

// CreatePolicyStmt is the parse tree node CreatePolicyStmt.
type CreatePolicyStmt struct {
	PolicyName string
	Table      *RangeVar
	CmdName    string
	Permissive bool
	Roles      []Node
	Qual       Node
	WithCheck  Node
}

// AlterPolicyStmt is the parse tree node AlterPolicyStmt.
type AlterPolicyStmt struct {
	PolicyName string
	Table      *RangeVar
	Roles      []Node
	Qual       Node
	WithCheck  Node
}

// CreateAmStmt is the parse tree node CreateAmStmt.
type CreateAmStmt struct {
	Amname      string
	HandlerName []Node
	Amtype      string
}

// CreateTrigStmt is the parse tree node CreateTrigStmt.
type CreateTrigStmt struct {
	Replace        bool
	Isconstraint   bool
	Trigname       string
	Relation       *RangeVar
	Funcname       []Node
	Args           []Node
	Row            bool
	Timing         int32
	Events         int32
	Columns        []Node
	WhenClause     Node
	TransitionRels []Node
	Deferrable     bool
	Initdeferred   bool
	Constrrel      *RangeVar
}

// CreateEventTrigStmt is the parse tree node CreateEventTrigStmt.
type CreateEventTrigStmt struct {
	Trigname   string
	Eventname  string
	Whenclause []Node
	Funcname   []Node
}

// AlterEventTrigStmt is the parse tree node AlterEventTrigStmt.
type AlterEventTrigStmt struct {
	Trigname  string
	Tgenabled string
}

// CreatePLangStmt is the parse tree node CreatePLangStmt.
type CreatePLangStmt struct {
	Replace     bool
	Plname      string
	Plhandler   []Node
	Plinline    []Node
	Plvalidator []Node
	Pltrusted   bool
}

// CreateRoleStmt is the parse tree node CreateRoleStmt.
type CreateRoleStmt struct {
	StmtType RoleStmtType
	Role     string
	Options  []Node
}

// AlterRoleStmt is the parse tree node AlterRoleStmt.
type AlterRoleStmt struct {
	Role    *RoleSpec
	Options []Node
	Action  int32
}

// AlterRoleSetStmt is the parse tree node AlterRoleSetStmt.
type AlterRoleSetStmt struct {
	Role     *RoleSpec
	Database string
	Setstmt  *VariableSetStmt
}

// DropRoleStmt is the parse tree node DropRoleStmt.
type DropRoleStmt struct {
	Roles     []Node
	MissingOk bool
}

// CreateSeqStmt is the parse tree node CreateSeqStmt.
type CreateSeqStmt struct {
	Sequence    *RangeVar
	Options     []Node
	OwnerId     uint32
	ForIdentity bool
	IfNotExists bool
}

// AlterSeqStmt is the parse tree node AlterSeqStmt.
type AlterSeqStmt struct {
	Sequence    *RangeVar
	Options     []Node
	ForIdentity bool
	MissingOk   bool
}

// DefineStmt is the parse tree node DefineStmt.
type DefineStmt struct {
	Kind        ObjectType
	Oldstyle    bool
	Defnames    []Node
	Args        []Node
	Definition  []Node
	IfNotExists bool
	Replace     bool
}

// CreateDomainStmt is the parse tree node CreateDomainStmt.
type CreateDomainStmt struct {
	Domainname  []Node
	TypeName    *TypeName
	CollClause  *CollateClause
	Constraints []Node
}

// CreateOpClassStmt is the parse tree node CreateOpClassStmt.
type CreateOpClassStmt struct {
	Opclassname  []Node
	Opfamilyname []Node
	Amname       string
	Datatype     *TypeName
	Items        []Node
	IsDefault    bool
}

// CreateOpClassItem is the parse tree node CreateOpClassItem.
type CreateOpClassItem struct {
	Itemtype    int32
	Name        *ObjectWithArgs
	Number      int32
	OrderFamily []Node
	ClassArgs   []Node
	Storedtype  *TypeName
}

// CreateOpFamilyStmt is the parse tree node CreateOpFamilyStmt.
type CreateOpFamilyStmt struct {
	Opfamilyname []Node
	Amname       string
}

// AlterOpFamilyStmt is the parse tree node AlterOpFamilyStmt.
type AlterOpFamilyStmt struct {
	Opfamilyname []Node
	Amname       string
	IsDrop       bool
	Items        []Node
}

// DropStmt is the parse tree node DropStmt.
type DropStmt struct {
	Objects    []Node
	RemoveType ObjectType
	Behavior   DropBehavior
	MissingOk  bool
	Concurrent bool
}

// TruncateStmt is the parse tree node TruncateStmt.
type TruncateStmt struct {
	Relations   []Node
	RestartSeqs bool
	Behavior    DropBehavior
}

// CommentStmt is the parse tree node CommentStmt.
type CommentStmt struct {
	Objtype ObjectType
	Object  Node
	Comment string
}

// SecLabelStmt is the parse tree node SecLabelStmt.
type SecLabelStmt struct {
	Objtype  ObjectType
	Object   Node
	Provider string
	Label    string
}

// DeclareCursorStmt is the parse tree node DeclareCursorStmt.
type DeclareCursorStmt struct {
	Portalname string
	Options    int32
	Query      Node
}

// ClosePortalStmt is the parse tree node ClosePortalStmt.
type ClosePortalStmt struct {
	Portalname string
}

// FetchStmt is the parse tree node FetchStmt.
type FetchStmt struct {
	Direction  FetchDirection
	HowMany    int64
	Portalname string
	Ismove     bool
}

// IndexStmt is the parse tree node IndexStmt.
type IndexStmt struct {
	Idxname                     string
	Relation                    *RangeVar
	AccessMethod                string
	TableSpace                  string
	IndexParams                 []Node
	IndexIncludingParams        []Node
	Options                     []Node
	WhereClause                 Node
	ExcludeOpNames              []Node
	Idxcomment                  string
	IndexOid                    uint32
	OldNumber                   uint32
	OldCreateSubid              uint32
	OldFirstRelfilelocatorSubid uint32
	Unique                      bool
	NullsNotDistinct            bool
	Primary                     bool
	Isconstraint                bool
	Deferrable                  bool
	Initdeferred                bool
	Transformed                 bool
	Concurrent                  bool
	IfNotExists                 bool
	ResetDefaultTblspc          bool
}

// CreateStatsStmt is the parse tree node CreateStatsStmt.
type CreateStatsStmt struct {
	Defnames    []Node
	StatTypes   []Node
	Exprs       []Node
	Relations   []Node
	Stxcomment  string
	Transformed bool
	IfNotExists bool
}

// StatsElem is the parse tree node StatsElem.
type StatsElem struct {
	Name string
	Expr Node
}

// AlterStatsStmt is the parse tree node AlterStatsStmt.
type AlterStatsStmt struct {
	Defnames      []Node
	Stxstattarget Node
	MissingOk     bool
}

// CreateFunctionStmt is the parse tree node CreateFunctionStmt.
type CreateFunctionStmt struct {
	IsProcedure bool
	Replace     bool
	Funcname    []Node
	Parameters  []Node
	ReturnType  *TypeName
	Options     []Node
	SqlBody     Node
}

// FunctionParameter is the parse tree node FunctionParameter.
type FunctionParameter struct {
	Name    string
	ArgType *TypeName
	Mode    FunctionParameterMode
	Defexpr Node
}

// AlterFunctionStmt is the parse tree node AlterFunctionStmt.
type AlterFunctionStmt struct {
	Objtype ObjectType
	Func    *ObjectWithArgs
	Actions []Node
}

// DoStmt is the parse tree node DoStmt.
type DoStmt struct {
	Args []Node
}

// InlineCodeBlock is the parse tree node InlineCodeBlock.
type InlineCodeBlock struct {
	SourceText    string
	LangOid       uint32
	LangIsTrusted bool
	Atomic        bool
}

// CallStmt is the parse tree node CallStmt.
type CallStmt struct {
	Funccall *FuncCall
	Funcexpr *FuncExpr
	Outargs  []Node
}

// CallContext is the parse tree node CallContext.
type CallContext struct {
	Atomic bool
}

// RenameStmt is the parse tree node RenameStmt.
type RenameStmt struct {
	RenameType   ObjectType
	RelationType ObjectType
	Relation     *RangeVar
	Object       Node
	Subname      string
	Newname      string
	Behavior     DropBehavior
	MissingOk    bool
}

// AlterObjectDependsStmt is the parse tree node AlterObjectDependsStmt.
type AlterObjectDependsStmt struct {
	ObjectType ObjectType
	Relation   *RangeVar
	Object     Node
	Extname    *String
	Remove     bool
}

// AlterObjectSchemaStmt is the parse tree node AlterObjectSchemaStmt.
type AlterObjectSchemaStmt struct {
	ObjectType ObjectType
	Relation   *RangeVar
	Object     Node
	Newschema  string
	MissingOk  bool
}

// AlterOwnerStmt is the parse tree node AlterOwnerStmt.
type AlterOwnerStmt struct {
	ObjectType ObjectType
	Relation   *RangeVar
	Object     Node
	Newowner   *RoleSpec
}

// AlterOperatorStmt is the parse tree node AlterOperatorStmt.
type AlterOperatorStmt struct {
	Opername *ObjectWithArgs
	Options  []Node
}

// AlterTypeStmt is the parse tree node AlterTypeStmt.
type AlterTypeStmt struct {
	TypeName []Node
	Options  []Node
}

// RuleStmt is the parse tree node RuleStmt.
type RuleStmt struct {
	Relation    *RangeVar
	Rulename    string
	WhereClause Node
	Event       CmdType
	Instead     bool
	Actions     []Node
	Replace     bool
}

// NotifyStmt is the parse tree node NotifyStmt.
type NotifyStmt struct {
	Conditionname string
	Payload       string
}

// ListenStmt is the parse tree node ListenStmt.
type ListenStmt struct {
	Conditionname string
}

// UnlistenStmt is the parse tree node UnlistenStmt.
type UnlistenStmt struct {
	Conditionname string
}

// TransactionStmt is the parse tree node TransactionStmt.
type TransactionStmt struct {
	Kind          TransactionStmtKind
	Options       []Node
	SavepointName string
	Gid           string
	Chain         bool
	Location      int32
}

// CompositeTypeStmt is the parse tree node CompositeTypeStmt.
type CompositeTypeStmt struct {
	Typevar    *RangeVar
	Coldeflist []Node
}

// CreateEnumStmt is the parse tree node CreateEnumStmt.
type CreateEnumStmt struct {
	TypeName []Node
	Vals     []Node
}

// CreateRangeStmt is the parse tree node CreateRangeStmt.
type CreateRangeStmt struct {
	TypeName []Node
	Params   []Node
}

// AlterEnumStmt is the parse tree node AlterEnumStmt.
type AlterEnumStmt struct {
	TypeName           []Node
	OldVal             string
	NewVal             string
	NewValNeighbor     string
	NewValIsAfter      bool
	SkipIfNewValExists bool
}

// ViewStmt is the parse tree node ViewStmt.
type ViewStmt struct {
	View            *RangeVar
	Aliases         []Node
	Query           Node
	Replace         bool
	Options         []Node
	WithCheckOption ViewCheckOption
}

// LoadStmt is the parse tree node LoadStmt.
type LoadStmt struct {
	Filename string
}

// CreatedbStmt is the parse tree node CreatedbStmt.
type CreatedbStmt struct {
	Dbname  string
	Options []Node
}

// AlterDatabaseStmt is the parse tree node AlterDatabaseStmt.
type AlterDatabaseStmt struct {
	Dbname  string
	Options []Node
}

// AlterDatabaseRefreshCollStmt is the parse tree node AlterDatabaseRefreshCollStmt.
type AlterDatabaseRefreshCollStmt struct {
	Dbname string
}

// AlterDatabaseSetStmt is the parse tree node AlterDatabaseSetStmt.
type AlterDatabaseSetStmt struct {
	Dbname  string
	Setstmt *VariableSetStmt
}

// DropdbStmt is the parse tree node DropdbStmt.
type DropdbStmt struct {
	Dbname    string
	MissingOk bool
	Options   []Node
}

// AlterSystemStmt is the parse tree node AlterSystemStmt.
type AlterSystemStmt struct {
	Setstmt *VariableSetStmt
}

// ClusterStmt is the parse tree node ClusterStmt.
type ClusterStmt struct {
	Relation  *RangeVar
	Indexname string
	Params    []Node
}

// VacuumStmt is the parse tree node VacuumStmt.
type VacuumStmt struct {
	Options     []Node
	Rels        []Node
	IsVacuumcmd bool
}

// VacuumRelation is the parse tree node VacuumRelation.
type VacuumRelation struct {
	Relation *RangeVar
	Oid      uint32
	VaCols   []Node
}

// ExplainStmt is the parse tree node ExplainStmt.
type ExplainStmt struct {
	Query   Node
	Options []Node
}

// CreateTableAsStmt is the parse tree node CreateTableAsStmt.
type CreateTableAsStmt struct {
	Query        Node
	Into         *IntoClause
	Objtype      ObjectType
	IsSelectInto bool
	IfNotExists  bool
}

// RefreshMatViewStmt is the parse tree node RefreshMatViewStmt.
type RefreshMatViewStmt struct {
	Concurrent bool
	SkipData   bool
	Relation   *RangeVar
}

// CheckPointStmt is the parse tree node CheckPointStmt.
type CheckPointStmt struct {
}

// DiscardStmt is the parse tree node DiscardStmt.
type DiscardStmt struct {
	Target DiscardMode
}

// LockStmt is the parse tree node LockStmt.
type LockStmt struct {
	Relations []Node
	Mode      int32
	Nowait    bool
}

// ConstraintsSetStmt is the parse tree node ConstraintsSetStmt.
type ConstraintsSetStmt struct {
	Constraints []Node
	Deferred    bool
}

// ReindexStmt is the parse tree node ReindexStmt.
type ReindexStmt struct {
	Kind     ReindexObjectType
	Relation *RangeVar
	Name     string
	Params   []Node
}

// CreateConversionStmt is the parse tree node CreateConversionStmt.
type CreateConversionStmt struct {
	ConversionName  []Node
	ForEncodingName string
	ToEncodingName  string
	FuncName        []Node
	Def             bool
}

// CreateCastStmt is the parse tree node CreateCastStmt.
type CreateCastStmt struct {
	Sourcetype *TypeName
	Targettype *TypeName
	Func       *ObjectWithArgs
	Context    CoercionContext
	Inout      bool
}

// CreateTransformStmt is the parse tree node CreateTransformStmt.
type CreateTransformStmt struct {
	Replace  bool
	TypeName *TypeName
	Lang     string
	Fromsql  *ObjectWithArgs
	Tosql    *ObjectWithArgs
}

// PrepareStmt is the parse tree node PrepareStmt.
type PrepareStmt struct {
	Name     string
	Argtypes []Node
	Query    Node
}

// ExecuteStmt is the parse tree node ExecuteStmt.
type ExecuteStmt struct {
	Name   string
	Params []Node
}

// DeallocateStmt is the parse tree node DeallocateStmt.
type DeallocateStmt struct {
	Name     string
	Isall    bool
	Location int32
}

// DropOwnedStmt is the parse tree node DropOwnedStmt.
type DropOwnedStmt struct {
	Roles    []Node
	Behavior DropBehavior
}

// ReassignOwnedStmt is the parse tree node ReassignOwnedStmt.
type ReassignOwnedStmt struct {
	Roles   []Node
	Newrole *RoleSpec
}

// AlterTSDictionaryStmt is the parse tree node AlterTSDictionaryStmt.
type AlterTSDictionaryStmt struct {
	Dictname []Node
	Options  []Node
}

// AlterTSConfigurationStmt is the parse tree node AlterTSConfigurationStmt.
type AlterTSConfigurationStmt struct {
	Kind      AlterTSConfigType
	Cfgname   []Node
	Tokentype []Node
	Dicts     []Node
	Override  bool
	Replace   bool
	MissingOk bool
}

// PublicationTable is the parse tree node PublicationTable.
type PublicationTable struct {
	Relation    *RangeVar
	WhereClause Node
	Columns     []Node
}

// PublicationObjSpec is the parse tree node PublicationObjSpec.
type PublicationObjSpec struct {
	Pubobjtype PublicationObjSpecType
	Name       string
	Pubtable   *PublicationTable
	Location   int32
}

// CreatePublicationStmt is the parse tree node CreatePublicationStmt.
type CreatePublicationStmt struct {
	Pubname      string
	Options      []Node
	Pubobjects   []Node
	ForAllTables bool
}

// AlterPublicationStmt is the parse tree node AlterPublicationStmt.
type AlterPublicationStmt struct {
	Pubname      string
	Options      []Node
	Pubobjects   []Node
	ForAllTables bool
	Action       AlterPublicationAction
}

// CreateSubscriptionStmt is the parse tree node CreateSubscriptionStmt.
type CreateSubscriptionStmt struct {
	Subname     string
	Conninfo    string
	Publication []Node
	Options     []Node
}

// AlterSubscriptionStmt is the parse tree node AlterSubscriptionStmt.
type AlterSubscriptionStmt struct {
	Kind        AlterSubscriptionType
	Subname     string
	Conninfo    string
	Publication []Node
	Options     []Node
}

// DropSubscriptionStmt is the parse tree node DropSubscriptionStmt.
type DropSubscriptionStmt struct {
	Subname   string
	MissingOk bool
	Behavior  DropBehavior
}

// Integer is the parse tree node Integer.
type Integer struct {
	Ival int32
}

// Float is the parse tree node Float.
type Float struct {
	Fval string
}

// Boolean is the parse tree node Boolean.
type Boolean struct {
	Boolval bool
}

// String is the parse tree node String.
type String struct {
	Sval string
	// Loc is the byte offset of the name in the text, -1 when unknown.
	Loc int32
}

// BitString is the parse tree node BitString.
type BitString struct {
	Bsval string
}

// List is the parse tree node List.
type List struct {
	Items []Node
}

// IntList is the parse tree node IntList.
type IntList struct {
	Items []Node
}

// OidList is the parse tree node OidList.
type OidList struct {
	Items []Node
}

// A_Const is the parse tree node A_Const.
type A_Const struct {
	// Val is an *Integer, *Float, *Boolean, *String or *BitString.
	Val      Node
	Isnull   bool
	Location int32
}
