// Code generated by oracle/cmd/gentokens; DO NOT EDIT.

// This file is derived from PostgreSQL (src/include/parser/kwlist.h and the
// token list of src/backend/parser/gram.y).
//
// Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
// Portions Copyright (c) 1994, Regents of the University of California
//
// PostgreSQL License: see ../../LICENSE.PostgreSQL.

package lex

// Token numbers of libpg_query (PostgreSQL 17). Tokens below 256 are single
// characters and are their own code.
const (
	IDENT                Token = 258
	UIDENT               Token = 259
	FCONST               Token = 260
	SCONST               Token = 261
	USCONST              Token = 262
	BCONST               Token = 263
	XCONST               Token = 264
	Op                   Token = 265
	ICONST               Token = 266
	PARAM                Token = 267
	TYPECAST             Token = 268
	DOT_DOT              Token = 269
	COLON_EQUALS         Token = 270
	EQUALS_GREATER       Token = 271
	LESS_EQUALS          Token = 272
	GREATER_EQUALS       Token = 273
	NOT_EQUALS           Token = 274
	SQL_COMMENT          Token = 275
	C_COMMENT            Token = 276
	ABORT_P              Token = 277
	ABSENT               Token = 278
	ABSOLUTE_P           Token = 279
	ACCESS               Token = 280
	ACTION               Token = 281
	ADD_P                Token = 282
	ADMIN                Token = 283
	AFTER                Token = 284
	AGGREGATE            Token = 285
	ALL                  Token = 286
	ALSO                 Token = 287
	ALTER                Token = 288
	ALWAYS               Token = 289
	ANALYSE              Token = 290
	ANALYZE              Token = 291
	AND                  Token = 292
	ANY                  Token = 293
	ARRAY                Token = 294
	AS                   Token = 295
	ASC                  Token = 296
	ASENSITIVE           Token = 297
	ASSERTION            Token = 298
	ASSIGNMENT           Token = 299
	ASYMMETRIC           Token = 300
	ATOMIC               Token = 301
	AT                   Token = 302
	ATTACH               Token = 303
	ATTRIBUTE            Token = 304
	AUTHORIZATION        Token = 305
	BACKWARD             Token = 306
	BEFORE               Token = 307
	BEGIN_P              Token = 308
	BETWEEN              Token = 309
	BIGINT               Token = 310
	BINARY               Token = 311
	BIT                  Token = 312
	BOOLEAN_P            Token = 313
	BOTH                 Token = 314
	BREADTH              Token = 315
	BY                   Token = 316
	CACHE                Token = 317
	CALL                 Token = 318
	CALLED               Token = 319
	CASCADE              Token = 320
	CASCADED             Token = 321
	CASE                 Token = 322
	CAST                 Token = 323
	CATALOG_P            Token = 324
	CHAIN                Token = 325
	CHAR_P               Token = 326
	CHARACTER            Token = 327
	CHARACTERISTICS      Token = 328
	CHECK                Token = 329
	CHECKPOINT           Token = 330
	CLASS                Token = 331
	CLOSE                Token = 332
	CLUSTER              Token = 333
	COALESCE             Token = 334
	COLLATE              Token = 335
	COLLATION            Token = 336
	COLUMN               Token = 337
	COLUMNS              Token = 338
	COMMENT              Token = 339
	COMMENTS             Token = 340
	COMMIT               Token = 341
	COMMITTED            Token = 342
	COMPRESSION          Token = 343
	CONCURRENTLY         Token = 344
	CONDITIONAL          Token = 345
	CONFIGURATION        Token = 346
	CONFLICT             Token = 347
	CONNECTION           Token = 348
	CONSTRAINT           Token = 349
	CONSTRAINTS          Token = 350
	CONTENT_P            Token = 351
	CONTINUE_P           Token = 352
	CONVERSION_P         Token = 353
	COPY                 Token = 354
	COST                 Token = 355
	CREATE               Token = 356
	CROSS                Token = 357
	CSV                  Token = 358
	CUBE                 Token = 359
	CURRENT_P            Token = 360
	CURRENT_CATALOG      Token = 361
	CURRENT_DATE         Token = 362
	CURRENT_ROLE         Token = 363
	CURRENT_SCHEMA       Token = 364
	CURRENT_TIME         Token = 365
	CURRENT_TIMESTAMP    Token = 366
	CURRENT_USER         Token = 367
	CURSOR               Token = 368
	CYCLE                Token = 369
	DATA_P               Token = 370
	DATABASE             Token = 371
	DAY_P                Token = 372
	DEALLOCATE           Token = 373
	DEC                  Token = 374
	DECIMAL_P            Token = 375
	DECLARE              Token = 376
	DEFAULT              Token = 377
	DEFAULTS             Token = 378
	DEFERRABLE           Token = 379
	DEFERRED             Token = 380
	DEFINER              Token = 381
	DELETE_P             Token = 382
	DELIMITER            Token = 383
	DELIMITERS           Token = 384
	DEPENDS              Token = 385
	DEPTH                Token = 386
	DESC                 Token = 387
	DETACH               Token = 388
	DICTIONARY           Token = 389
	DISABLE_P            Token = 390
	DISCARD              Token = 391
	DISTINCT             Token = 392
	DO                   Token = 393
	DOCUMENT_P           Token = 394
	DOMAIN_P             Token = 395
	DOUBLE_P             Token = 396
	DROP                 Token = 397
	EACH                 Token = 398
	ELSE                 Token = 399
	EMPTY_P              Token = 400
	ENABLE_P             Token = 401
	ENCODING             Token = 402
	ENCRYPTED            Token = 403
	END_P                Token = 404
	ENUM_P               Token = 405
	ERROR_P              Token = 406
	ESCAPE               Token = 407
	EVENT                Token = 408
	EXCEPT               Token = 409
	EXCLUDE              Token = 410
	EXCLUDING            Token = 411
	EXCLUSIVE            Token = 412
	EXECUTE              Token = 413
	EXISTS               Token = 414
	EXPLAIN              Token = 415
	EXPRESSION           Token = 416
	EXTENSION            Token = 417
	EXTERNAL             Token = 418
	EXTRACT              Token = 419
	FALSE_P              Token = 420
	FAMILY               Token = 421
	FETCH                Token = 422
	FILTER               Token = 423
	FINALIZE             Token = 424
	FIRST_P              Token = 425
	FLOAT_P              Token = 426
	FOLLOWING            Token = 427
	FOR                  Token = 428
	FORCE                Token = 429
	FOREIGN              Token = 430
	FORMAT               Token = 431
	FORWARD              Token = 432
	FREEZE               Token = 433
	FROM                 Token = 434
	FULL                 Token = 435
	FUNCTION             Token = 436
	FUNCTIONS            Token = 437
	GENERATED            Token = 438
	GLOBAL               Token = 439
	GRANT                Token = 440
	GRANTED              Token = 441
	GREATEST             Token = 442
	GROUP_P              Token = 443
	GROUPING             Token = 444
	GROUPS               Token = 445
	HANDLER              Token = 446
	HAVING               Token = 447
	HEADER_P             Token = 448
	HOLD                 Token = 449
	HOUR_P               Token = 450
	IDENTITY_P           Token = 451
	IF_P                 Token = 452
	ILIKE                Token = 453
	IMMEDIATE            Token = 454
	IMMUTABLE            Token = 455
	IMPLICIT_P           Token = 456
	IMPORT_P             Token = 457
	IN_P                 Token = 458
	INCLUDE              Token = 459
	INCLUDING            Token = 460
	INCREMENT            Token = 461
	INDENT               Token = 462
	INDEX                Token = 463
	INDEXES              Token = 464
	INHERIT              Token = 465
	INHERITS             Token = 466
	INITIALLY            Token = 467
	INLINE_P             Token = 468
	INNER_P              Token = 469
	INOUT                Token = 470
	INPUT_P              Token = 471
	INSENSITIVE          Token = 472
	INSERT               Token = 473
	INSTEAD              Token = 474
	INT_P                Token = 475
	INTEGER              Token = 476
	INTERSECT            Token = 477
	INTERVAL             Token = 478
	INTO                 Token = 479
	INVOKER              Token = 480
	IS                   Token = 481
	ISNULL               Token = 482
	ISOLATION            Token = 483
	JOIN                 Token = 484
	JSON                 Token = 485
	JSON_ARRAY           Token = 486
	JSON_ARRAYAGG        Token = 487
	JSON_EXISTS          Token = 488
	JSON_OBJECT          Token = 489
	JSON_OBJECTAGG       Token = 490
	JSON_QUERY           Token = 491
	JSON_SCALAR          Token = 492
	JSON_SERIALIZE       Token = 493
	JSON_TABLE           Token = 494
	JSON_VALUE           Token = 495
	KEEP                 Token = 496
	KEY                  Token = 497
	KEYS                 Token = 498
	LABEL                Token = 499
	LANGUAGE             Token = 500
	LARGE_P              Token = 501
	LAST_P               Token = 502
	LATERAL_P            Token = 503
	LEADING              Token = 504
	LEAKPROOF            Token = 505
	LEAST                Token = 506
	LEFT                 Token = 507
	LEVEL                Token = 508
	LIKE                 Token = 509
	LIMIT                Token = 510
	LISTEN               Token = 511
	LOAD                 Token = 512
	LOCAL                Token = 513
	LOCALTIME            Token = 514
	LOCALTIMESTAMP       Token = 515
	LOCATION             Token = 516
	LOCK_P               Token = 517
	LOCKED               Token = 518
	LOGGED               Token = 519
	MAPPING              Token = 520
	MATCH                Token = 521
	MATCHED              Token = 522
	MATERIALIZED         Token = 523
	MAXVALUE             Token = 524
	MERGE                Token = 525
	MERGE_ACTION         Token = 526
	METHOD               Token = 527
	MINUTE_P             Token = 528
	MINVALUE             Token = 529
	MODE                 Token = 530
	MONTH_P              Token = 531
	MOVE                 Token = 532
	NAME_P               Token = 533
	NAMES                Token = 534
	NATIONAL             Token = 535
	NATURAL              Token = 536
	NCHAR                Token = 537
	NESTED               Token = 538
	NEW                  Token = 539
	NEXT                 Token = 540
	NFC                  Token = 541
	NFD                  Token = 542
	NFKC                 Token = 543
	NFKD                 Token = 544
	NO                   Token = 545
	NONE                 Token = 546
	NORMALIZE            Token = 547
	NORMALIZED           Token = 548
	NOT                  Token = 549
	NOTHING              Token = 550
	NOTIFY               Token = 551
	NOTNULL              Token = 552
	NOWAIT               Token = 553
	NULL_P               Token = 554
	NULLIF               Token = 555
	NULLS_P              Token = 556
	NUMERIC              Token = 557
	OBJECT_P             Token = 558
	OF                   Token = 559
	OFF                  Token = 560
	OFFSET               Token = 561
	OIDS                 Token = 562
	OLD                  Token = 563
	OMIT                 Token = 564
	ON                   Token = 565
	ONLY                 Token = 566
	OPERATOR             Token = 567
	OPTION               Token = 568
	OPTIONS              Token = 569
	OR                   Token = 570
	ORDER                Token = 571
	ORDINALITY           Token = 572
	OTHERS               Token = 573
	OUT_P                Token = 574
	OUTER_P              Token = 575
	OVER                 Token = 576
	OVERLAPS             Token = 577
	OVERLAY              Token = 578
	OVERRIDING           Token = 579
	OWNED                Token = 580
	OWNER                Token = 581
	PARALLEL             Token = 582
	PARAMETER            Token = 583
	PARSER               Token = 584
	PARTIAL              Token = 585
	PARTITION            Token = 586
	PASSING              Token = 587
	PASSWORD             Token = 588
	PATH                 Token = 589
	PLACING              Token = 590
	PLAN                 Token = 591
	PLANS                Token = 592
	POLICY               Token = 593
	POSITION             Token = 594
	PRECEDING            Token = 595
	PRECISION            Token = 596
	PRESERVE             Token = 597
	PREPARE              Token = 598
	PREPARED             Token = 599
	PRIMARY              Token = 600
	PRIOR                Token = 601
	PRIVILEGES           Token = 602
	PROCEDURAL           Token = 603
	PROCEDURE            Token = 604
	PROCEDURES           Token = 605
	PROGRAM              Token = 606
	PUBLICATION          Token = 607
	QUOTE                Token = 608
	QUOTES               Token = 609
	RANGE                Token = 610
	READ                 Token = 611
	REAL                 Token = 612
	REASSIGN             Token = 613
	RECHECK              Token = 614
	RECURSIVE            Token = 615
	REF_P                Token = 616
	REFERENCES           Token = 617
	REFERENCING          Token = 618
	REFRESH              Token = 619
	REINDEX              Token = 620
	RELATIVE_P           Token = 621
	RELEASE              Token = 622
	RENAME               Token = 623
	REPEATABLE           Token = 624
	REPLACE              Token = 625
	REPLICA              Token = 626
	RESET                Token = 627
	RESTART              Token = 628
	RESTRICT             Token = 629
	RETURN               Token = 630
	RETURNING            Token = 631
	RETURNS              Token = 632
	REVOKE               Token = 633
	RIGHT                Token = 634
	ROLE                 Token = 635
	ROLLBACK             Token = 636
	ROLLUP               Token = 637
	ROUTINE              Token = 638
	ROUTINES             Token = 639
	ROW                  Token = 640
	ROWS                 Token = 641
	RULE                 Token = 642
	SAVEPOINT            Token = 643
	SCALAR               Token = 644
	SCHEMA               Token = 645
	SCHEMAS              Token = 646
	SCROLL               Token = 647
	SEARCH               Token = 648
	SECOND_P             Token = 649
	SECURITY             Token = 650
	SELECT               Token = 651
	SEQUENCE             Token = 652
	SEQUENCES            Token = 653
	SERIALIZABLE         Token = 654
	SERVER               Token = 655
	SESSION              Token = 656
	SESSION_USER         Token = 657
	SET                  Token = 658
	SETS                 Token = 659
	SETOF                Token = 660
	SHARE                Token = 661
	SHOW                 Token = 662
	SIMILAR              Token = 663
	SIMPLE               Token = 664
	SKIP                 Token = 665
	SMALLINT             Token = 666
	SNAPSHOT             Token = 667
	SOME                 Token = 668
	SOURCE               Token = 669
	SQL_P                Token = 670
	STABLE               Token = 671
	STANDALONE_P         Token = 672
	START                Token = 673
	STATEMENT            Token = 674
	STATISTICS           Token = 675
	STDIN                Token = 676
	STDOUT               Token = 677
	STORAGE              Token = 678
	STORED               Token = 679
	STRICT_P             Token = 680
	STRING_P             Token = 681
	STRIP_P              Token = 682
	SUBSCRIPTION         Token = 683
	SUBSTRING            Token = 684
	SUPPORT              Token = 685
	SYMMETRIC            Token = 686
	SYSID                Token = 687
	SYSTEM_P             Token = 688
	SYSTEM_USER          Token = 689
	TABLE                Token = 690
	TABLES               Token = 691
	TABLESAMPLE          Token = 692
	TABLESPACE           Token = 693
	TARGET               Token = 694
	TEMP                 Token = 695
	TEMPLATE             Token = 696
	TEMPORARY            Token = 697
	TEXT_P               Token = 698
	THEN                 Token = 699
	TIES                 Token = 700
	TIME                 Token = 701
	TIMESTAMP            Token = 702
	TO                   Token = 703
	TRAILING             Token = 704
	TRANSACTION          Token = 705
	TRANSFORM            Token = 706
	TREAT                Token = 707
	TRIGGER              Token = 708
	TRIM                 Token = 709
	TRUE_P               Token = 710
	TRUNCATE             Token = 711
	TRUSTED              Token = 712
	TYPE_P               Token = 713
	TYPES_P              Token = 714
	UESCAPE              Token = 715
	UNBOUNDED            Token = 716
	UNCONDITIONAL        Token = 717
	UNCOMMITTED          Token = 718
	UNENCRYPTED          Token = 719
	UNION                Token = 720
	UNIQUE               Token = 721
	UNKNOWN              Token = 722
	UNLISTEN             Token = 723
	UNLOGGED             Token = 724
	UNTIL                Token = 725
	UPDATE               Token = 726
	USER                 Token = 727
	USING                Token = 728
	VACUUM               Token = 729
	VALID                Token = 730
	VALIDATE             Token = 731
	VALIDATOR            Token = 732
	VALUE_P              Token = 733
	VALUES               Token = 734
	VARCHAR              Token = 735
	VARIADIC             Token = 736
	VARYING              Token = 737
	VERBOSE              Token = 738
	VERSION_P            Token = 739
	VIEW                 Token = 740
	VIEWS                Token = 741
	VOLATILE             Token = 742
	WHEN                 Token = 743
	WHERE                Token = 744
	WHITESPACE_P         Token = 745
	WINDOW               Token = 746
	WITH                 Token = 747
	WITHIN               Token = 748
	WITHOUT              Token = 749
	WORK                 Token = 750
	WRAPPER              Token = 751
	WRITE                Token = 752
	XML_P                Token = 753
	XMLATTRIBUTES        Token = 754
	XMLCONCAT            Token = 755
	XMLELEMENT           Token = 756
	XMLEXISTS            Token = 757
	XMLFOREST            Token = 758
	XMLNAMESPACES        Token = 759
	XMLPARSE             Token = 760
	XMLPI                Token = 761
	XMLROOT              Token = 762
	XMLSERIALIZE         Token = 763
	XMLTABLE             Token = 764
	YEAR_P               Token = 765
	YES_P                Token = 766
	ZONE                 Token = 767
	FORMAT_LA            Token = 768
	NOT_LA               Token = 769
	NULLS_LA             Token = 770
	WITH_LA              Token = 771
	WITHOUT_LA           Token = 772
	MODE_TYPE_NAME       Token = 773
	MODE_PLPGSQL_EXPR    Token = 774
	MODE_PLPGSQL_ASSIGN1 Token = 775
	MODE_PLPGSQL_ASSIGN2 Token = 776
	MODE_PLPGSQL_ASSIGN3 Token = 777
	UMINUS               Token = 778
)

// tokenNames maps token numbers from 256 up to their names.
var tokenNames = [...]string{
	258: "IDENT",
	259: "UIDENT",
	260: "FCONST",
	261: "SCONST",
	262: "USCONST",
	263: "BCONST",
	264: "XCONST",
	265: "Op",
	266: "ICONST",
	267: "PARAM",
	268: "TYPECAST",
	269: "DOT_DOT",
	270: "COLON_EQUALS",
	271: "EQUALS_GREATER",
	272: "LESS_EQUALS",
	273: "GREATER_EQUALS",
	274: "NOT_EQUALS",
	275: "SQL_COMMENT",
	276: "C_COMMENT",
	277: "ABORT_P",
	278: "ABSENT",
	279: "ABSOLUTE_P",
	280: "ACCESS",
	281: "ACTION",
	282: "ADD_P",
	283: "ADMIN",
	284: "AFTER",
	285: "AGGREGATE",
	286: "ALL",
	287: "ALSO",
	288: "ALTER",
	289: "ALWAYS",
	290: "ANALYSE",
	291: "ANALYZE",
	292: "AND",
	293: "ANY",
	294: "ARRAY",
	295: "AS",
	296: "ASC",
	297: "ASENSITIVE",
	298: "ASSERTION",
	299: "ASSIGNMENT",
	300: "ASYMMETRIC",
	301: "ATOMIC",
	302: "AT",
	303: "ATTACH",
	304: "ATTRIBUTE",
	305: "AUTHORIZATION",
	306: "BACKWARD",
	307: "BEFORE",
	308: "BEGIN_P",
	309: "BETWEEN",
	310: "BIGINT",
	311: "BINARY",
	312: "BIT",
	313: "BOOLEAN_P",
	314: "BOTH",
	315: "BREADTH",
	316: "BY",
	317: "CACHE",
	318: "CALL",
	319: "CALLED",
	320: "CASCADE",
	321: "CASCADED",
	322: "CASE",
	323: "CAST",
	324: "CATALOG_P",
	325: "CHAIN",
	326: "CHAR_P",
	327: "CHARACTER",
	328: "CHARACTERISTICS",
	329: "CHECK",
	330: "CHECKPOINT",
	331: "CLASS",
	332: "CLOSE",
	333: "CLUSTER",
	334: "COALESCE",
	335: "COLLATE",
	336: "COLLATION",
	337: "COLUMN",
	338: "COLUMNS",
	339: "COMMENT",
	340: "COMMENTS",
	341: "COMMIT",
	342: "COMMITTED",
	343: "COMPRESSION",
	344: "CONCURRENTLY",
	345: "CONDITIONAL",
	346: "CONFIGURATION",
	347: "CONFLICT",
	348: "CONNECTION",
	349: "CONSTRAINT",
	350: "CONSTRAINTS",
	351: "CONTENT_P",
	352: "CONTINUE_P",
	353: "CONVERSION_P",
	354: "COPY",
	355: "COST",
	356: "CREATE",
	357: "CROSS",
	358: "CSV",
	359: "CUBE",
	360: "CURRENT_P",
	361: "CURRENT_CATALOG",
	362: "CURRENT_DATE",
	363: "CURRENT_ROLE",
	364: "CURRENT_SCHEMA",
	365: "CURRENT_TIME",
	366: "CURRENT_TIMESTAMP",
	367: "CURRENT_USER",
	368: "CURSOR",
	369: "CYCLE",
	370: "DATA_P",
	371: "DATABASE",
	372: "DAY_P",
	373: "DEALLOCATE",
	374: "DEC",
	375: "DECIMAL_P",
	376: "DECLARE",
	377: "DEFAULT",
	378: "DEFAULTS",
	379: "DEFERRABLE",
	380: "DEFERRED",
	381: "DEFINER",
	382: "DELETE_P",
	383: "DELIMITER",
	384: "DELIMITERS",
	385: "DEPENDS",
	386: "DEPTH",
	387: "DESC",
	388: "DETACH",
	389: "DICTIONARY",
	390: "DISABLE_P",
	391: "DISCARD",
	392: "DISTINCT",
	393: "DO",
	394: "DOCUMENT_P",
	395: "DOMAIN_P",
	396: "DOUBLE_P",
	397: "DROP",
	398: "EACH",
	399: "ELSE",
	400: "EMPTY_P",
	401: "ENABLE_P",
	402: "ENCODING",
	403: "ENCRYPTED",
	404: "END_P",
	405: "ENUM_P",
	406: "ERROR_P",
	407: "ESCAPE",
	408: "EVENT",
	409: "EXCEPT",
	410: "EXCLUDE",
	411: "EXCLUDING",
	412: "EXCLUSIVE",
	413: "EXECUTE",
	414: "EXISTS",
	415: "EXPLAIN",
	416: "EXPRESSION",
	417: "EXTENSION",
	418: "EXTERNAL",
	419: "EXTRACT",
	420: "FALSE_P",
	421: "FAMILY",
	422: "FETCH",
	423: "FILTER",
	424: "FINALIZE",
	425: "FIRST_P",
	426: "FLOAT_P",
	427: "FOLLOWING",
	428: "FOR",
	429: "FORCE",
	430: "FOREIGN",
	431: "FORMAT",
	432: "FORWARD",
	433: "FREEZE",
	434: "FROM",
	435: "FULL",
	436: "FUNCTION",
	437: "FUNCTIONS",
	438: "GENERATED",
	439: "GLOBAL",
	440: "GRANT",
	441: "GRANTED",
	442: "GREATEST",
	443: "GROUP_P",
	444: "GROUPING",
	445: "GROUPS",
	446: "HANDLER",
	447: "HAVING",
	448: "HEADER_P",
	449: "HOLD",
	450: "HOUR_P",
	451: "IDENTITY_P",
	452: "IF_P",
	453: "ILIKE",
	454: "IMMEDIATE",
	455: "IMMUTABLE",
	456: "IMPLICIT_P",
	457: "IMPORT_P",
	458: "IN_P",
	459: "INCLUDE",
	460: "INCLUDING",
	461: "INCREMENT",
	462: "INDENT",
	463: "INDEX",
	464: "INDEXES",
	465: "INHERIT",
	466: "INHERITS",
	467: "INITIALLY",
	468: "INLINE_P",
	469: "INNER_P",
	470: "INOUT",
	471: "INPUT_P",
	472: "INSENSITIVE",
	473: "INSERT",
	474: "INSTEAD",
	475: "INT_P",
	476: "INTEGER",
	477: "INTERSECT",
	478: "INTERVAL",
	479: "INTO",
	480: "INVOKER",
	481: "IS",
	482: "ISNULL",
	483: "ISOLATION",
	484: "JOIN",
	485: "JSON",
	486: "JSON_ARRAY",
	487: "JSON_ARRAYAGG",
	488: "JSON_EXISTS",
	489: "JSON_OBJECT",
	490: "JSON_OBJECTAGG",
	491: "JSON_QUERY",
	492: "JSON_SCALAR",
	493: "JSON_SERIALIZE",
	494: "JSON_TABLE",
	495: "JSON_VALUE",
	496: "KEEP",
	497: "KEY",
	498: "KEYS",
	499: "LABEL",
	500: "LANGUAGE",
	501: "LARGE_P",
	502: "LAST_P",
	503: "LATERAL_P",
	504: "LEADING",
	505: "LEAKPROOF",
	506: "LEAST",
	507: "LEFT",
	508: "LEVEL",
	509: "LIKE",
	510: "LIMIT",
	511: "LISTEN",
	512: "LOAD",
	513: "LOCAL",
	514: "LOCALTIME",
	515: "LOCALTIMESTAMP",
	516: "LOCATION",
	517: "LOCK_P",
	518: "LOCKED",
	519: "LOGGED",
	520: "MAPPING",
	521: "MATCH",
	522: "MATCHED",
	523: "MATERIALIZED",
	524: "MAXVALUE",
	525: "MERGE",
	526: "MERGE_ACTION",
	527: "METHOD",
	528: "MINUTE_P",
	529: "MINVALUE",
	530: "MODE",
	531: "MONTH_P",
	532: "MOVE",
	533: "NAME_P",
	534: "NAMES",
	535: "NATIONAL",
	536: "NATURAL",
	537: "NCHAR",
	538: "NESTED",
	539: "NEW",
	540: "NEXT",
	541: "NFC",
	542: "NFD",
	543: "NFKC",
	544: "NFKD",
	545: "NO",
	546: "NONE",
	547: "NORMALIZE",
	548: "NORMALIZED",
	549: "NOT",
	550: "NOTHING",
	551: "NOTIFY",
	552: "NOTNULL",
	553: "NOWAIT",
	554: "NULL_P",
	555: "NULLIF",
	556: "NULLS_P",
	557: "NUMERIC",
	558: "OBJECT_P",
	559: "OF",
	560: "OFF",
	561: "OFFSET",
	562: "OIDS",
	563: "OLD",
	564: "OMIT",
	565: "ON",
	566: "ONLY",
	567: "OPERATOR",
	568: "OPTION",
	569: "OPTIONS",
	570: "OR",
	571: "ORDER",
	572: "ORDINALITY",
	573: "OTHERS",
	574: "OUT_P",
	575: "OUTER_P",
	576: "OVER",
	577: "OVERLAPS",
	578: "OVERLAY",
	579: "OVERRIDING",
	580: "OWNED",
	581: "OWNER",
	582: "PARALLEL",
	583: "PARAMETER",
	584: "PARSER",
	585: "PARTIAL",
	586: "PARTITION",
	587: "PASSING",
	588: "PASSWORD",
	589: "PATH",
	590: "PLACING",
	591: "PLAN",
	592: "PLANS",
	593: "POLICY",
	594: "POSITION",
	595: "PRECEDING",
	596: "PRECISION",
	597: "PRESERVE",
	598: "PREPARE",
	599: "PREPARED",
	600: "PRIMARY",
	601: "PRIOR",
	602: "PRIVILEGES",
	603: "PROCEDURAL",
	604: "PROCEDURE",
	605: "PROCEDURES",
	606: "PROGRAM",
	607: "PUBLICATION",
	608: "QUOTE",
	609: "QUOTES",
	610: "RANGE",
	611: "READ",
	612: "REAL",
	613: "REASSIGN",
	614: "RECHECK",
	615: "RECURSIVE",
	616: "REF_P",
	617: "REFERENCES",
	618: "REFERENCING",
	619: "REFRESH",
	620: "REINDEX",
	621: "RELATIVE_P",
	622: "RELEASE",
	623: "RENAME",
	624: "REPEATABLE",
	625: "REPLACE",
	626: "REPLICA",
	627: "RESET",
	628: "RESTART",
	629: "RESTRICT",
	630: "RETURN",
	631: "RETURNING",
	632: "RETURNS",
	633: "REVOKE",
	634: "RIGHT",
	635: "ROLE",
	636: "ROLLBACK",
	637: "ROLLUP",
	638: "ROUTINE",
	639: "ROUTINES",
	640: "ROW",
	641: "ROWS",
	642: "RULE",
	643: "SAVEPOINT",
	644: "SCALAR",
	645: "SCHEMA",
	646: "SCHEMAS",
	647: "SCROLL",
	648: "SEARCH",
	649: "SECOND_P",
	650: "SECURITY",
	651: "SELECT",
	652: "SEQUENCE",
	653: "SEQUENCES",
	654: "SERIALIZABLE",
	655: "SERVER",
	656: "SESSION",
	657: "SESSION_USER",
	658: "SET",
	659: "SETS",
	660: "SETOF",
	661: "SHARE",
	662: "SHOW",
	663: "SIMILAR",
	664: "SIMPLE",
	665: "SKIP",
	666: "SMALLINT",
	667: "SNAPSHOT",
	668: "SOME",
	669: "SOURCE",
	670: "SQL_P",
	671: "STABLE",
	672: "STANDALONE_P",
	673: "START",
	674: "STATEMENT",
	675: "STATISTICS",
	676: "STDIN",
	677: "STDOUT",
	678: "STORAGE",
	679: "STORED",
	680: "STRICT_P",
	681: "STRING_P",
	682: "STRIP_P",
	683: "SUBSCRIPTION",
	684: "SUBSTRING",
	685: "SUPPORT",
	686: "SYMMETRIC",
	687: "SYSID",
	688: "SYSTEM_P",
	689: "SYSTEM_USER",
	690: "TABLE",
	691: "TABLES",
	692: "TABLESAMPLE",
	693: "TABLESPACE",
	694: "TARGET",
	695: "TEMP",
	696: "TEMPLATE",
	697: "TEMPORARY",
	698: "TEXT_P",
	699: "THEN",
	700: "TIES",
	701: "TIME",
	702: "TIMESTAMP",
	703: "TO",
	704: "TRAILING",
	705: "TRANSACTION",
	706: "TRANSFORM",
	707: "TREAT",
	708: "TRIGGER",
	709: "TRIM",
	710: "TRUE_P",
	711: "TRUNCATE",
	712: "TRUSTED",
	713: "TYPE_P",
	714: "TYPES_P",
	715: "UESCAPE",
	716: "UNBOUNDED",
	717: "UNCONDITIONAL",
	718: "UNCOMMITTED",
	719: "UNENCRYPTED",
	720: "UNION",
	721: "UNIQUE",
	722: "UNKNOWN",
	723: "UNLISTEN",
	724: "UNLOGGED",
	725: "UNTIL",
	726: "UPDATE",
	727: "USER",
	728: "USING",
	729: "VACUUM",
	730: "VALID",
	731: "VALIDATE",
	732: "VALIDATOR",
	733: "VALUE_P",
	734: "VALUES",
	735: "VARCHAR",
	736: "VARIADIC",
	737: "VARYING",
	738: "VERBOSE",
	739: "VERSION_P",
	740: "VIEW",
	741: "VIEWS",
	742: "VOLATILE",
	743: "WHEN",
	744: "WHERE",
	745: "WHITESPACE_P",
	746: "WINDOW",
	747: "WITH",
	748: "WITHIN",
	749: "WITHOUT",
	750: "WORK",
	751: "WRAPPER",
	752: "WRITE",
	753: "XML_P",
	754: "XMLATTRIBUTES",
	755: "XMLCONCAT",
	756: "XMLELEMENT",
	757: "XMLEXISTS",
	758: "XMLFOREST",
	759: "XMLNAMESPACES",
	760: "XMLPARSE",
	761: "XMLPI",
	762: "XMLROOT",
	763: "XMLSERIALIZE",
	764: "XMLTABLE",
	765: "YEAR_P",
	766: "YES_P",
	767: "ZONE",
	768: "FORMAT_LA",
	769: "NOT_LA",
	770: "NULLS_LA",
	771: "WITH_LA",
	772: "WITHOUT_LA",
	773: "MODE_TYPE_NAME",
	774: "MODE_PLPGSQL_EXPR",
	775: "MODE_PLPGSQL_ASSIGN1",
	776: "MODE_PLPGSQL_ASSIGN2",
	777: "MODE_PLPGSQL_ASSIGN3",
	778: "UMINUS",
}
