// Command gentokens writes internal/lex/tokens_gen.go and keywords_gen.go.
//
// Token numbers and names come from the Token enum of libpg_query, so the
// lexer reports the same numbers as the oracle; the keyword list, with the
// keyword categories, comes from PostgreSQL's src/include/parser/kwlist.h.
//
//	go run ./cmd/gentokens -pgsrc $PGSRC -out ../internal/lex
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	pg "github.com/pganalyze/pg_query_go/v6"
)

const licence = `// This file is derived from PostgreSQL (src/include/parser/kwlist.h and the
// token list of src/backend/parser/gram.y).
//
// Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
// Portions Copyright (c) 1994, Regents of the University of California
//
// PostgreSQL License: see ../../LICENSE.PostgreSQL.
`

func main() {
	pgsrc := flag.String("pgsrc", os.Getenv("PGSRC"), "directory with the PostgreSQL 17 sources (tools/get-pgsrc.sh)")
	out := flag.String("out", "../internal/lex", "output directory")
	flag.Parse()
	if *pgsrc == "" {
		log.Fatal("-pgsrc or $PGSRC is required")
	}
	writeTokens(filepath.Join(*out, "tokens_gen.go"))
	writeKeywords(filepath.Join(*pgsrc, "src/include/parser/kwlist.h"), filepath.Join(*out, "keywords_gen.go"))
}

func writeTokens(path string) {
	var nums []int
	for n := range pg.Token_name {
		if n >= 256 {
			nums = append(nums, int(n))
		}
	}
	sort.Ints(nums)
	var b bytes.Buffer
	b.WriteString("// Code generated by oracle/cmd/gentokens; DO NOT EDIT.\n\n" + licence + "\npackage lex\n\n")
	b.WriteString("// Token numbers of libpg_query (PostgreSQL 17). Tokens below 256 are single\n// characters and are their own code.\nconst (\n")
	for _, n := range nums {
		fmt.Fprintf(&b, "\t%s Token = %d\n", pg.Token_name[int32(n)], n)
	}
	b.WriteString(")\n\n// tokenNames maps token numbers from 256 up to their names.\nvar tokenNames = [...]string{\n")
	for _, n := range nums {
		fmt.Fprintf(&b, "\t%d: %q,\n", n, pg.Token_name[int32(n)])
	}
	b.WriteString("}\n")
	write(path, b.Bytes())
}

var kwRe = regexp.MustCompile(`^PG_KEYWORD\("([^"]+)",\s*(\w+),\s*(\w+),\s*(\w+)\)`)

func writeKeywords(src, path string) {
	f, err := os.Open(src)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	type kw struct{ name, tok, kind, bare string }
	var kws []kw
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		if m := kwRe.FindStringSubmatch(sc.Text()); m != nil {
			kws = append(kws, kw{m[1], m[2], m[3], m[4]})
		}
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}
	if len(kws) < 400 {
		log.Fatalf("only %d keywords found in %s", len(kws), src)
	}
	sort.Slice(kws, func(i, j int) bool { return kws[i].name < kws[j].name })
	kinds := map[string]string{
		"UNRESERVED_KEYWORD":     "UnreservedKeyword",
		"COL_NAME_KEYWORD":       "ColNameKeyword",
		"TYPE_FUNC_NAME_KEYWORD": "TypeFuncNameKeyword",
		"RESERVED_KEYWORD":       "ReservedKeyword",
	}
	maxLen := 0
	var b bytes.Buffer
	b.WriteString("// Code generated by oracle/cmd/gentokens; DO NOT EDIT.\n\n" + licence + "\npackage lex\n\n")
	b.WriteString("// keywords lists the SQL keywords of PostgreSQL 17 sorted by name.\nvar keywords = [...]keyword{\n")
	for _, k := range kws {
		kind, ok := kinds[k.kind]
		if !ok {
			log.Fatalf("keyword %s: unknown category %s", k.name, k.kind)
		}
		if strings.ToLower(k.name) != k.name {
			log.Fatalf("keyword %s is not lower case", k.name)
		}
		if len(k.name) > maxLen {
			maxLen = len(k.name)
		}
		fmt.Fprintf(&b, "\t{%q, %s, %s, %v},\n", k.name, k.tok, kind, k.bare == "BARE_LABEL")
	}
	fmt.Fprintf(&b, "}\n\n// maxKeywordLen is the length of the longest keyword.\nconst maxKeywordLen = %d\n", maxLen)
	write(path, b.Bytes())
}

func write(path string, src []byte) {
	out, err := format.Source(src)
	if err != nil {
		log.Fatalf("%s: %v\n%s", path, err, src)
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("wrote", path)
}
