// Command genast writes the node types of the parse tree, internal/ast.
//
// The nodes of PostgreSQL's parse tree are described by the protobuf
// messages of libpg_query (pg_query.proto), which come from parsenodes.h and
// primnodes.h. The generator turns every message of the Node oneof into a Go
// struct with the field names protoc-gen-go would use, every enum into a Go
// type with PostgreSQL's own values (protobuf shifts them by one for the
// *_UNDEFINED value), and gives every node a Children method.
//
//	go run ./cmd/genast -out ../internal/ast
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/4itosik/pg_migrate_research/pgschema/oracle"
	pg "github.com/pganalyze/pg_query_go/v6"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const header = `// Code generated by oracle/cmd/genast from the node descriptions of
// libpg_query (pg_query.proto); DO NOT EDIT.
//
// The nodes follow PostgreSQL's src/include/nodes/parsenodes.h and
// primnodes.h.
//
// Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
// Portions Copyright (c) 1994, Regents of the University of California
//
// PostgreSQL License: see ../../LICENSE.PostgreSQL. The descriptions come
// from libpg_query (BSD-3-Clause, Copyright (c) 2015, Lukas Fittl;
// see ../../LICENSE.libpg_query).

package ast

`

// extras are fields the library adds to a node, which libpg_query's tree
// does not have. The comparison with libpg_query ignores them.
var extras = map[string][]string{
	"String": {"// Loc is the byte offset of the name in the text, -1 when unknown.\n\tLoc int32"},
}

// Messages that are not nodes of the parse tree.
var skip = map[string]bool{"Node": true, "ParseResult": true, "ScanResult": true, "ScanToken": true}

func main() {
	out := flag.String("out", "../internal/ast", "output directory")
	flag.Parse()
	fd := pg.File_pg_query_proto

	inNode := map[string]bool{}
	nodeMsg := fd.Messages().ByName("Node")
	var order []string
	for i := 0; i < nodeMsg.Fields().Len(); i++ {
		name := string(nodeMsg.Fields().Get(i).Message().Name())
		inNode[name] = true
		order = append(order, name)
	}

	var nodes, children bytes.Buffer
	nodes.WriteString(header)
	nodes.WriteString(`// Node is a node of the parse tree. Every node type is a pointer to a struct.
type Node interface {
	// Children calls f for every node directly below the node, in field
	// order: fields of type Node, nodes of a specific type and the elements
	// of lists. Fields that are nil are skipped.
	Children(f func(Node))
}

`)
	children.WriteString(header)
	for _, name := range order {
		if skip[name] {
			continue
		}
		m := fd.Messages().ByName(protoreflect.Name(name))
		genNode(&nodes, &children, m, inNode)
	}
	write(filepath.Join(*out, "nodes_gen.go"), nodes.Bytes())
	write(filepath.Join(*out, "children_gen.go"), children.Bytes())

	var enums bytes.Buffer
	enums.WriteString(header)
	genEnums(&enums, fd)
	write(filepath.Join(*out, "enums_gen.go"), enums.Bytes())
}

func goType(f protoreflect.FieldDescriptor, inNode map[string]bool) string {
	var t string
	switch f.Kind() {
	case protoreflect.BoolKind:
		t = "bool"
	case protoreflect.Int32Kind:
		t = "int32"
	case protoreflect.Int64Kind:
		t = "int64"
	case protoreflect.Uint32Kind:
		t = "uint32"
	case protoreflect.Uint64Kind:
		t = "uint64"
	case protoreflect.DoubleKind:
		t = "float64"
	case protoreflect.StringKind:
		t = "string"
	case protoreflect.EnumKind:
		t = string(f.Enum().Name())
	case protoreflect.MessageKind:
		name := string(f.Message().Name())
		switch {
		case name == "Node":
			t = "Node"
		case inNode[name]:
			t = "*" + name
		default:
			log.Fatalf("field %s: message %s is not a node", f.FullName(), name)
		}
	default:
		log.Fatalf("field %s: unsupported kind %v", f.FullName(), f.Kind())
	}
	if f.IsList() {
		return "[]" + t
	}
	return t
}

func genNode(w, c *bytes.Buffer, m protoreflect.MessageDescriptor, inNode map[string]bool) {
	name := string(m.Name())
	fmt.Fprintf(w, "// %s is the parse tree node %s.\ntype %s struct {\n", name, name, name)
	var kids []string // statements of Children
	oneofDone := false
	for i := 0; i < m.Fields().Len(); i++ {
		f := m.Fields().Get(i)
		if f.IsMap() {
			log.Fatalf("%s: map fields are not supported", f.FullName())
		}
		goName := oracle.GoCamelCase(string(f.Name()))
		if goName == "Children" {
			log.Fatalf("%s: field name clashes with the Children method", f.FullName())
		}
		if o := f.ContainingOneof(); o != nil && !o.IsSynthetic() {
			// A_Const: one field Val for the five alternatives
			if name != "A_Const" {
				log.Fatalf("%s: unexpected oneof", f.FullName())
			}
			if !oneofDone {
				fmt.Fprintf(w, "\t// Val is an *Integer, *Float, *Boolean, *String or *BitString.\n\tVal Node\n")
				kids = append(kids, "if n.Val != nil {\n\t\tf(n.Val)\n\t}")
				oneofDone = true
			}
			continue
		}
		t := goType(f, inNode)
		fmt.Fprintf(w, "\t%s %s\n", goName, t)
		switch {
		case f.Kind() != protoreflect.MessageKind:
		case f.IsList():
			kids = append(kids, fmt.Sprintf("for _, c := range n.%s {\n\t\tif c != nil {\n\t\t\tf(c)\n\t\t}\n\t}", goName))
		default:
			kids = append(kids, fmt.Sprintf("if n.%s != nil {\n\t\tf(n.%s)\n\t}", goName, goName))
		}
	}
	for _, e := range extras[name] {
		fmt.Fprintf(w, "\t%s\n", e)
	}
	w.WriteString("}\n\n")
	fmt.Fprintf(c, "// Children implements Node.\nfunc (n *%s) Children(f func(Node)) {", name)
	if len(kids) == 0 {
		c.WriteString("}\n\n")
		return
	}
	for _, k := range kids {
		fmt.Fprintf(c, "\n\t%s", k)
	}
	c.WriteString("\n}\n\n")
}

func genEnums(w *bytes.Buffer, fd protoreflect.FileDescriptor) {
	var names []string
	byName := map[string]protoreflect.EnumDescriptor{}
	for i := 0; i < fd.Enums().Len(); i++ {
		e := fd.Enums().Get(i)
		// Token and KeywordKind belong to the scanner, not to the tree
		if !strings.HasSuffix(string(e.Values().Get(0).Name()), "_UNDEFINED") {
			continue
		}
		names = append(names, string(e.Name()))
		byName[string(e.Name())] = e
	}
	sort.Strings(names)
	for _, n := range names {
		e := byName[n]
		fmt.Fprintf(w, "// %s is the PostgreSQL enum %s.\ntype %s int32\n\nconst (\n", n, n, n)
		for i := 1; i < e.Values().Len(); i++ { // value 0 is *_UNDEFINED
			v := e.Values().Get(i)
			fmt.Fprintf(w, "\t%s %s = %d\n", v.Name(), n, int(v.Number())-1)
		}
		fmt.Fprintf(w, ")\n\nfunc (e %s) String() string {\n\tswitch e {\n", n)
		for i := 1; i < e.Values().Len(); i++ {
			v := e.Values().Get(i)
			fmt.Fprintf(w, "\tcase %s:\n\t\treturn %q\n", v.Name(), string(v.Name()))
		}
		fmt.Fprintf(w, "\t}\n\treturn fmt.Sprintf(\"%s(%%d)\", int32(e))\n}\n\n", n)
	}
}

func write(path string, src []byte) {
	if strings.Contains(path, "enums_gen") {
		src = bytes.Replace(src, []byte("package ast\n"), []byte("package ast\n\nimport \"fmt\"\n"), 1)
	}
	out, err := format.Source(src)
	if err != nil {
		os.WriteFile(path+".broken", src, 0o644)
		log.Fatalf("%s: %v", path, err)
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("wrote", path, len(out), "bytes")
}
